# backend/app/core/form_configs/ds260_config.py

# Mapping of Form Field Keys to Original Question Text
# Generated automatically from ds260.ts

FIELD_MAPPING = {
    "S01-Q001": "Name Provided (Surnames, Given Names)",
    "S01-Q002": "Full Name in Native Language",
    "S01-Q003": "Other Names Used",
    "S01-Q004": "Sex",
    "S01-Q005": "Current Marital Status",
    "S01-Q006": "Date of Birth",
    "S01-Q007": "City of Birth",
    "S01-Q008": "State/Province of Birth",
    "S01-Q009": "Country/Region of Birth",
    "S01-Q010": "Country/Region of Origin (Nationality)",
    "S01-Q011": "Document Type",
    "S01-Q012": "Document ID (Passport Number)",
    "S01-Q013": "Country/Authority that Issued Document",
    "S01-Q014": "Issuance Date",
    "S01-Q015": "Expiration Date",
    "S01-Q016": "Do you hold or have you held any nationality other than the one you have indicated above?",
    "S01-Q016A": "Other Citizenship Country",
    "S01-Q017": "Present Address (Street Address, City, State/Province, Postal Code, Country, From Date)",
    "S01-Q018": "Have you lived anywhere other than this address since the age of sixteen?",
    "S01-Q018A": "Previous Addresses",
    "S01-Q019": "Primary Phone Number",
    "S01-Q020": "Secondary Phone Number",
    "S01-Q021": "Work Phone Number",
    "S01-Q022": "Other Telephone Numbers Used",
    "S01-Q023": "Email Address",
    "S01-Q024": "Other Email Addresses Used",
    "S01-Q025": "Social Media Provider/Platform",
    "S01-Q026": "Other Social Media Used",
    "S01-Q027": "Is your Mailing Address the same as your Present Address?",
    "S01-Q028": "Do you have an address in the United States where you intend to live?",
    "S01-Q029": "Name of person currently living at address",
    "S01-Q030": "U.S. Address (Street, City, State, ZIP Code)",
    "S01-Q031": "Is this address where you want your Permanent Residence Card (Green Card) mailed?",
    "S02-Q001": "Father's Surnames",
    "S02-Q002": "Father's Given Names",
    "S02-Q003": "Father's Date of Birth",
    "S02-Q004": "Father's City of Birth",
    "S02-Q005": "Father's State/Province of Birth",
    "S02-Q006": "Father's Country/Region of Birth",
    "S02-Q007": "Is your father still living?",
    "S02-Q007A": "Father's Year of Death",
    "S02-Q008": "Mother's Surnames at Birth",
    "S02-Q009": "Mother's Given Names",
    "S02-Q010": "Mother's Date of Birth",
    "S02-Q011": "Mother's City of Birth",
    "S02-Q012": "Mother's State/Province of Birth",
    "S02-Q013": "Mother's Country/Region of Birth",
    "S02-Q014": "Is your mother still living?",
    "S02-Q014A": "Mother's Year of Death",
    "S02-Q015": "Do you have any previous spouses?",
    "S02-Q016": "Number of Previous Spouses",
    "S02-Q017": "Previous Spouse Name (Full Name)",
    "S02-Q018": "Date of Birth (Previous Spouse)",
    "S02-Q019": "Date of Marriage",
    "S02-Q020": "Date Marriage Ended",
    "S02-Q021": "How was your marriage terminated?",
    "S02-Q022": "Country/Region where marriage was terminated",
    "S02-Q023": "Do you have any children?",
    "S02-Q024": "Number of Children",
    "S02-Q025": "Child Name (Full Name)",
    "S02-Q026": "Date of Birth (Child)",
    "S02-Q027": "City of Birth (Child)",
    "S02-Q028": "State of Birth (Child)",
    "S02-Q029": "Country/Region of Birth (Child)",
    "S02-Q030": "Does this child live with you?",
    "S02-Q031": "Address (Child)",
    "S02-Q032": "Is this child immigrating to the U.S. with you?",
    "S02-Q033": "Is this child immigrating to the U.S. at a later date to join you?",
    "S03-Q001": "Have you ever been in the U.S.?",
    "S03-Q002": "Were you issued an Alien Registration Number by the Department of Homeland Security?",
    "S03-Q003": "Provide information on your last five U.S. visits (Date Arrived, Length of Stay)",
    "S03-Q004": "Have you ever been issued a U.S. Visa?",
    "S03-Q005": "Date Visa Was Issued",
    "S03-Q006": "Visa Classification",
    "S03-Q007": "Visa Number",
    "S03-Q008": "Have any of your U.S. visas ever been lost or stolen?",
    "S03-Q009": "Have any of your U.S. visas ever been cancelled or revoked?",
    "S03-Q010": "Have you ever been refused a U.S. visa, been refused admission to the U.S., or withdrawn your application for admission at the port of entry?",
    "S04-Q001": "Primary Occupation",
    "S04-Q002": "Do you have any other occupations?",
    "S04-Q003": "In which occupation do you intend to work in the U.S.?",
    "S04-Q004": "Were you previously employed?",
    "S04-Q005": "Employer Name, Address, Job Title, Supervisor, Employment Dates",
    "S04-Q006": "Have you attended any educational institutions at a secondary level or above?",
    "S04-Q007": "Number of Educational Institutions Attended",
    "S04-Q008": "Name of Institution, Address, Course of Study, Degree/Diploma, Dates of Attendance",
    "S04-Q009": "Have you traveled to any countries/regions within the last five years?",
    "S04-Q010": "Have you ever served in the military?",
    "S04-Q011": "Have you belonged to, contributed to, or worked for any professional, social, or charitable organization?",
    "S04-Q012": "Do you have any specialized skills or training, including firearms, explosives, nuclear, biological, or chemical experience?",
    "S04-Q013": "Have you ever served in, been a member of, or been involved with a paramilitary unit, vigilante unit, rebel group, guerrilla group, or insurgent organization?",
    "S04-Q014": "Can you speak and/or read languages other than your native language?",
    "S05-Q001": "Petitioner is my:",
    "S05-Q002": "Petitioner Name",
    "S05-Q003": "Petitioner Address (Street, City, State, ZIP Code, Country)",
    "S05-Q004": "Petitioner Telephone",
    "S05-Q005": "Petitioner Mobile/Cell Telephone",
    "S05-Q006": "Petitioner Email Address",
    "S06-Q001": "Do you have a communicable disease of public health significance such as tuberculosis (TB)?",
    "S06-Q002": "Do you have documentation to establish that you have received vaccinations in accordance with U.S. law?",
    "S06-Q003": "Do you have a mental or physical disorder that poses or is likely to pose a threat to the safety or welfare of yourself or others?",
    "S06-Q004": "Are you or have you ever been a drug abuser or addict?",
    "S06-Q005": "Have you ever been arrested or convicted for any offense or crime, even though subject of a pardon, amnesty, or other similar action?",
    "S06-Q006": "Have you ever violated, or engaged in a conspiracy to violate, any law relating to controlled substances?",
    "S06-Q007": "Are you the spouse, son, or daughter of an individual who has violated any controlled substance trafficking law, and have knowingly benefited from the trafficking activities in the past five years?",
    "S06-Q008": "Are you coming to the United States to engage in prostitution or unlawful commercialized vice or have you been engaged in prostitution or procuring prostitutes within the past 10 years?",
    "S06-Q009": "Have you ever been involved in, or do you seek to engage in, money laundering?",
    "S06-Q010": "Have you ever committed or conspired to commit a human trafficking offense in the United States or outside the United States?",
    "S06-Q011": "Have you ever knowingly aided, abetted, assisted, or colluded with an individual who has been identified by the President of the United States as a person who plays a significant role in a severe form of trafficking in persons?",
    "S06-Q012": "Are you the spouse, son, or daughter of an individual who has committed or conspired to commit a human trafficking offense in the United States or outside the United States and have you within the last five years, knowingly benefited from the trafficking activities?",
    "S06-Q013": "Do you seek to engage in espionage, sabotage, export control violations, or any other illegal activity while in the United States?",
    "S06-Q014": "Do you seek to engage in terrorist activities while in the United States or have you ever engaged in terrorist activities?",
    "S06-Q015": "Have you ever or do you intend to provide financial assistance or other support to terrorists or terrorist organizations?",
    "S06-Q016": "Are you a member or representative of a terrorist organization?",
    "S06-Q017": "Are you the spouse, son, or daughter of an individual who has engaged in terrorist activity, including providing financial assistance or other support to terrorists or terrorist organizations, in the last five years?",
    "S06-Q018": "Have you ever ordered, incited, committed, assisted, or otherwise participated in genocide?",
    "S06-Q019": "Have you ever committed, ordered, incited, assisted, or otherwise participated in torture?",
    "S06-Q020": "Have you committed, ordered, incited, assisted, or otherwise participated in extrajudicial killings, political killings, or other acts of violence?",
    "S06-Q021": "Have you ever engaged in the recruitment of or the use of child soldiers?",
    "S06-Q022": "Have you, while serving as a government official, been responsible for or directly carried out, at any time, particularly severe violations of religious freedom?",
    "S06-Q023": "Are you a member of or affiliated with the Communist or other totalitarian party?",
    "S06-Q024": "Have you ever directly or indirectly assisted or supported any of the groups in Columbia known as the Revolutionary Armed Forces of Columbia (FARC), National Liberation Army (ELN), or United Self-Defense Forces of Columbia (AUC)?",
    "S06-Q025": "Have you ever, through abuse of governmental or political position converted for personal gain, confiscated or expropriated property in a foreign nation to which a United States national had claim of ownership?",
    "S06-Q026": "Are you the spouse, minor child, or agent of an individual who has through abuse of governmental or political position converted for personal gain, confiscated or expropriated property in a foreign nation to which a United States national had claim of ownership?",
    "S06-Q027": "Have you ever been directly involved in the establishment or enforcement of population controls forcing a woman to undergo an abortion against her free choice or a man or a woman to undergo sterilization against his or her free choice?",
    "S06-Q028": "Have you ever disclosed or trafficked in confidential U.S. business information obtained in connection with U.S. participation in the Chemical Weapons Convention?",
    "S06-Q029": "Are you the spouse, minor child, or agent of an individual who has disclosed or trafficked in confidential U.S. business information obtained in connection with U.S. participation in the Chemical Weapons Convention?",
    "S06-Q030": "Have you ever sought to obtain or assist others to obtain a visa, entry into the United States, or any other United States immigration benefit by fraud or willful misrepresentation or other unlawful means?",
    "S06-Q031": "Have you ever been removed or deported from any country?",
    "S06-Q041": "Have you ever withheld custody of a U.S. citizen child outside the United States from a person granted legal custody by a U.S. court?",
    "S06-Q042": "Have you ever intentionally assisted another person in withholding custody of a U.S. citizen child outside the United States from a person granted legal custody by a U.S. court?",
    "S06-Q043": "Have you voted in the United States in violation of any law or regulation?",
    "S06-Q044": "Have you ever renounced United States citizenship for the purpose of avoiding taxation?",
    "S06-Q045": "Have you attended a public elementary school or a public secondary school on student (F) status after November 30, 1996 without reimbursing the school?",
    "S06-Q046": "Do you seek to enter the United States for the purpose of performing skilled or unskilled labor but have not yet been certified by the Secretary of Labor?",
    "S06-Q047": "Are you a graduate of a foreign medical school seeking to perform medical services in the United States but have not yet passed the National Board of Medical Examiners examination or its equivalent?",
    "S06-Q048": "Are you a health care worker seeking to perform such work in the United States but have not yet received certification from the Commission on Graduates of Foreign Nursing Schools or from an equivalent approved independent credentialing organization?",
    "S06-Q049": "Are you permanently ineligible for U.S. citizenship?",
    "S06-Q050": "Have you ever departed the United States in order to evade military service during a time of war?",
    "S06-Q051": "Are you coming to the U.S. to practice polygamy?",
    "S06-Q052": "Are you a former exchange visitor (J) who has not yet fulfilled the two-year foreign residence requirement?",
    "S06-Q053": "Has the Secretary of Homeland Security of the United States ever determined that you knowingly made a frivolous application for asylum?",
    "S06-Q054": "Are you likely to become a public charge after you are admitted to the United States?",
    "S07-Q001": "Have you ever applied for a Social Security number?",
    "S07-Q002": "Do you want the Social Security Administration to issue a Social Security number and a card?",
    "S07-Q003": "Do you authorize disclosure of information from this form to the Department of Homeland Security, the Social Security Administration, and such other U.S. Government agencies as may be required for the purposes of assigning you a social security number (SSN) and issuing you a Social Security card and do you authorize the Social Security Administration to share your SSN with the Department of Homeland Security?",
    "S08-Q001": "Did anyone assist you in filling out this application?",
    "S08-Q002": "Preparer Surnames and Given Names",
    "S08-Q003": "Organization Name",
    "S08-Q004": "Preparer Address (Street, City, State, ZIP, Country)",
    "S08-Q005": "Relationship to You",
}

# Mapping of Form Field Keys to Section Names
SECTION_MAPPING = {
    "S01-Q001": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q002": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q003": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q004": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q005": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q006": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q007": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q008": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q009": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q010": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q011": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q012": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q013": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q014": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q015": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q016": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q016A": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q017": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q018": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q018A": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q019": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q020": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q021": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q022": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q023": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q024": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q025": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q026": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q027": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q028": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q029": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q030": "SECTION 1: PERSONAL INFORMATION",
    "S01-Q031": "SECTION 1: PERSONAL INFORMATION",
    "S02-Q001": "SECTION 2: FAMILY INFORMATION",
    "S02-Q002": "SECTION 2: FAMILY INFORMATION",
    "S02-Q003": "SECTION 2: FAMILY INFORMATION",
    "S02-Q004": "SECTION 2: FAMILY INFORMATION",
    "S02-Q005": "SECTION 2: FAMILY INFORMATION",
    "S02-Q006": "SECTION 2: FAMILY INFORMATION",
    "S02-Q007": "SECTION 2: FAMILY INFORMATION",
    "S02-Q007A": "SECTION 2: FAMILY INFORMATION",
    "S02-Q008": "SECTION 2: FAMILY INFORMATION",
    "S02-Q009": "SECTION 2: FAMILY INFORMATION",
    "S02-Q010": "SECTION 2: FAMILY INFORMATION",
    "S02-Q011": "SECTION 2: FAMILY INFORMATION",
    "S02-Q012": "SECTION 2: FAMILY INFORMATION",
    "S02-Q013": "SECTION 2: FAMILY INFORMATION",
    "S02-Q014": "SECTION 2: FAMILY INFORMATION",
    "S02-Q014A": "SECTION 2: FAMILY INFORMATION",
    "S02-Q015": "SECTION 2: FAMILY INFORMATION",
    "S02-Q016": "SECTION 2: FAMILY INFORMATION",
    "S02-Q017": "SECTION 2: FAMILY INFORMATION",
    "S02-Q018": "SECTION 2: FAMILY INFORMATION",
    "S02-Q019": "SECTION 2: FAMILY INFORMATION",
    "S02-Q020": "SECTION 2: FAMILY INFORMATION",
    "S02-Q021": "SECTION 2: FAMILY INFORMATION",
    "S02-Q022": "SECTION 2: FAMILY INFORMATION",
    "S02-Q023": "SECTION 2: FAMILY INFORMATION",
    "S02-Q024": "SECTION 2: FAMILY INFORMATION",
    "S02-Q025": "SECTION 2: FAMILY INFORMATION",
    "S02-Q026": "SECTION 2: FAMILY INFORMATION",
    "S02-Q027": "SECTION 2: FAMILY INFORMATION",
    "S02-Q028": "SECTION 2: FAMILY INFORMATION",
    "S02-Q029": "SECTION 2: FAMILY INFORMATION",
    "S02-Q030": "SECTION 2: FAMILY INFORMATION",
    "S02-Q031": "SECTION 2: FAMILY INFORMATION",
    "S02-Q032": "SECTION 2: FAMILY INFORMATION",
    "S02-Q033": "SECTION 2: FAMILY INFORMATION",
    "S03-Q001": "SECTION 3: PREVIOUS U.S. TRAVEL INFORMATION",
    "S03-Q002": "SECTION 3: PREVIOUS U.S. TRAVEL INFORMATION",
    "S03-Q003": "SECTION 3: PREVIOUS U.S. TRAVEL INFORMATION",
    "S03-Q004": "SECTION 3: PREVIOUS U.S. TRAVEL INFORMATION",
    "S03-Q005": "SECTION 3: PREVIOUS U.S. TRAVEL INFORMATION",
    "S03-Q006": "SECTION 3: PREVIOUS U.S. TRAVEL INFORMATION",
    "S03-Q007": "SECTION 3: PREVIOUS U.S. TRAVEL INFORMATION",
    "S03-Q008": "SECTION 3: PREVIOUS U.S. TRAVEL INFORMATION",
    "S03-Q009": "SECTION 3: PREVIOUS U.S. TRAVEL INFORMATION",
    "S03-Q010": "SECTION 3: PREVIOUS U.S. TRAVEL INFORMATION",
    "S04-Q001": "SECTION 4: WORK/EDUCATION/TRAINING INFORMATION",
    "S04-Q002": "SECTION 4: WORK/EDUCATION/TRAINING INFORMATION",
    "S04-Q003": "SECTION 4: WORK/EDUCATION/TRAINING INFORMATION",
    "S04-Q004": "SECTION 4: WORK/EDUCATION/TRAINING INFORMATION",
    "S04-Q005": "SECTION 4: WORK/EDUCATION/TRAINING INFORMATION",
    "S04-Q006": "SECTION 4: WORK/EDUCATION/TRAINING INFORMATION",
    "S04-Q007": "SECTION 4: WORK/EDUCATION/TRAINING INFORMATION",
    "S04-Q008": "SECTION 4: WORK/EDUCATION/TRAINING INFORMATION",
    "S04-Q009": "SECTION 4: WORK/EDUCATION/TRAINING INFORMATION",
    "S04-Q010": "SECTION 4: WORK/EDUCATION/TRAINING INFORMATION",
    "S04-Q011": "SECTION 4: WORK/EDUCATION/TRAINING INFORMATION",
    "S04-Q012": "SECTION 4: WORK/EDUCATION/TRAINING INFORMATION",
    "S04-Q013": "SECTION 4: WORK/EDUCATION/TRAINING INFORMATION",
    "S04-Q014": "SECTION 4: WORK/EDUCATION/TRAINING INFORMATION",
    "S05-Q001": "SECTION 5: PETITIONER INFORMATION",
    "S05-Q002": "SECTION 5: PETITIONER INFORMATION",
    "S05-Q003": "SECTION 5: PETITIONER INFORMATION",
    "S05-Q004": "SECTION 5: PETITIONER INFORMATION",
    "S05-Q005": "SECTION 5: PETITIONER INFORMATION",
    "S05-Q006": "SECTION 5: PETITIONER INFORMATION",
    "S06-Q001": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q002": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q003": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q004": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q005": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q006": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q007": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q008": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q009": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q010": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q011": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q012": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q013": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q014": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q015": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q016": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q017": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q018": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q019": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q020": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q021": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q022": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q023": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q024": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q025": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q026": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q027": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q028": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q029": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q030": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q031": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q041": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q042": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q043": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q044": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q045": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q046": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q047": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q048": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q049": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q050": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q051": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q052": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q053": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S06-Q054": "SECTION 6: SECURITY AND BACKGROUND INFORMATION",
    "S07-Q001": "SECTION 7: SOCIAL SECURITY NUMBER INFORMATION",
    "S07-Q002": "SECTION 7: SOCIAL SECURITY NUMBER INFORMATION",
    "S07-Q003": "SECTION 7: SOCIAL SECURITY NUMBER INFORMATION",
    "S08-Q001": "SECTION 8: PREPARER OF APPLICATION",
    "S08-Q002": "SECTION 8: PREPARER OF APPLICATION",
    "S08-Q003": "SECTION 8: PREPARER OF APPLICATION",
    "S08-Q004": "SECTION 8: PREPARER OF APPLICATION",
    "S08-Q005": "SECTION 8: PREPARER OF APPLICATION",
}
