export interface PKMCenter {
  name: string;
  address: string;
  district: string;
  lat: number;
  lng: number;
}

export const pkmCenters: PKMCenter[] = [
  { name: "PKM, Near General Bus Stand, Attock", address: "PKM, Near General Bus Stand, Attock", district: "Attock", lat: 33.7667, lng: 72.3667 },
  { name: "PKM, Near Thana City A Division, Bahawalnagar", address: "PKM, Near Thana City A Division, Bahawalnagar", district: "Bahawalnagar", lat: 29.9983, lng: 73.2527 },
  { name: "PKM Saraiky chock, Cantt Bahawalpur", address: "PKM Saraiky chock, Cantt Bahawalpur", district: "Bahawalpur", lat: 29.3956, lng: 71.6836 },
  { name: "PKM Hasilpur Bahawalpur", address: "PKM Hasilpur Bahawalpur", district: "Bahawalpur", lat: 29.6972, lng: 72.5483 },
  { name: "PKM Ahmadpur East, Bahawalpur", address: "PKM Ahmadpur East, Bahawalpur", district: "Bahawalpur", lat: 29.1431, lng: 71.2575 },
  { name: "PKM, DPO Office, Kacheri Road, Bhakkar", address: "PKM, DPO Office, Kacheri Road, Bhakkar", district: "Bhakkar", lat: 31.6269, lng: 71.0667 },
  { name: "PKM, Ishara Chowk (Old 15 Chowk), Talagang Road, Chakwal City", address: "PKM, Ishara Chowk (Old 15 Chowk), Talagang Road, Chakwal City", district: "Chakwal", lat: 32.9333, lng: 72.8667 },
  { name: "PKM Talagang, Chakwal", address: "PKM Talagang, Chakwal", district: "Chakwal", lat: 32.9297, lng: 72.4206 },
  { name: "PKM, Near Lari Adda(Bus Stand), Sargodha Road, Chiniot", address: "PKM, Near Lari Adda(Bus Stand), Sargodha Road, Chiniot", district: "Chiniot", lat: 31.72, lng: 72.9789 },
  { name: "PKM, Near Police Station Civil Line, Dera Ghazi Khan", address: "PKM, Near Police Station Civil Line, Dera Ghazi Khan", district: "DG Khan", lat: 30.05, lng: 70.6333 },
  { name: "PKM Taunsa, Dera Ghazi Khan", address: "PKM Taunsa, Dera Ghazi Khan", district: "DG Khan", lat: 30.7042, lng: 70.6558 },
  { name: "PKM Jaranwala, Faisalabad", address: "PKM Jaranwala, Faisalabad", district: "Faisalabad", lat: 31.3342, lng: 73.4194 },
  { name: "PKM FCCI, Faisalabad", address: "PKM FCCI, Faisalabad", district: "Faisalabad", lat: 31.4504, lng: 73.1350 },
  { name: "PKM, Rescue 15, Opposite Main Gate Agriculture University, Jail Road, Faisalabad", address: "PKM, Rescue 15, Opposite Main Gate Agriculture University, Jail Road, Faisalabad", district: "Faisalabad", lat: 31.4284, lng: 73.0762 },
  { name: "PKM, Ashraf Marth Shaheed Police Lines, Gujranwala", address: "PKM, Ashraf Marth Shaheed Police Lines, Gujranwala", district: "Gujranwala", lat: 32.1877, lng: 74.1945 },
  { name: "PKM Kamoki, Gujranwala", address: "PKM Kamoki, Gujranwala", district: "Gujranwala", lat: 32.01, lng: 74.22 },
  { name: "PKM Wazirabad, Gujranwala", address: "PKM Wazirabad, Gujranwala", district: "Gujranwala", lat: 32.44, lng: 74.12 },
  { name: "PKM, Near Police Line, Gujrat", address: "PKM, Near Police Line, Gujrat", district: "Gujrat", lat: 32.5736, lng: 74.0789 },
  { name: "PKM Kharian, Gujrat", address: "PKM Kharian, Gujrat", district: "Gujrat", lat: 32.81, lng: 73.88 },
  { name: "PKM, Near Fawara Chowk, In front of New Police Station, Hafizabad", address: "PKM, Near Fawara Chowk, In front of New Police Station, Hafizabad", district: "Hafizabad", lat: 32.0689, lng: 73.6861 },
  { name: "PKM Pindi Bhattian, Hafizabad", address: "PKM Pindi Bhattian, Hafizabad", district: "Hafizabad", lat: 31.8953, lng: 73.2728 },
  { name: "PKM, Opposite of Main Gate, District Jail, Jhang", address: "PKM, Opposite of Main Gate, District Jail, Jhang", district: "Jhang", lat: 31.2678, lng: 72.3189 },
  { name: "PKM Sohawa, Jhelum", address: "PKM Sohawa, Jhelum", district: "Jhelum", lat: 33.1256, lng: 73.4211 },
  { name: "PKM Pind Dadan Khan, Jhelum", address: "PKM Pind Dadan Khan, Jhelum", district: "Jhelum", lat: 32.5858, lng: 73.0458 },
  { name: "PKM, Near City Police Station, Adjacent to traffic office, Jada Road, Jhelum", address: "PKM, Near City Police Station, Adjacent to traffic office, Jada Road, Jhelum", district: "Jhelum", lat: 32.9333, lng: 73.7167 },
  { name: "PKM Pattoki, District Kasur", address: "PKM Pattoki, District Kasur", district: "Kasur", lat: 31.0214, lng: 73.8533 },
  { name: "PKM, DPO office, District Kasur", address: "PKM, DPO office, District Kasur", district: "Kasur", lat: 31.1167, lng: 74.4333 },
  { name: "PKM, Police khidmat markaz, Near Police Station, Katchery Road, Khanewal", address: "PKM, Police khidmat markaz, Near Police Station, Katchery Road, Khanewal", district: "Khanewal", lat: 30.3, lng: 71.9333 },
  { name: "PKM Mian Channu, Khanewal", address: "PKM Mian Channu, Khanewal", district: "Khanewal", lat: 30.4397, lng: 72.3553 },
  { name: "Police Khidmat Markaz Khushab at DPO office Jauharabad", address: "Police Khidmat Markaz Khushab at DPO office Jauharabad", district: "Khushab", lat: 32.2906, lng: 72.2828 },
  { name: "The Lahore Chamber of Commerce & Industry", address: "11-Shara-e-Aiwan-e-Sanat-o-Tijarat, Lahore", district: "Lahore", lat: 31.5497, lng: 74.3436 },
  { name: "Police Khidmat Markaz, Sector A, Bahria Town, Lahore", address: "Police Khidmat Markaz, Sector A, Bahria Town, Lahore", district: "Lahore", lat: 31.3688, lng: 74.1842 },
  { name: "PKM, Gate No. 5, Greater Iqbal Park", address: "PKM, Gate No. 5, Greater Iqbal Park near Lady Wilson, Lahore", district: "Lahore", lat: 31.5917, lng: 74.3086 },
  { name: "PKM, Moon market, Iqbal town, Lahore", address: "PKM, Moon market, Iqbal town, Lahore", district: "Lahore", lat: 31.5175, lng: 74.2881 },
  { name: "PKM, DIG Operations Office, Lahore", address: "PKM, DIG Operations Office, Lahore", district: "Lahore", lat: 31.5647, lng: 74.3164 },
  { name: "PKM, Near Liberty parking area exit point, Gulberg 3, Lahore", address: "PKM, Near Liberty parking area exit point, Gulberg 3, Lahore", district: "Lahore", lat: 31.5133, lng: 74.3433 },
  { name: "PKM, DPO Office, Near District Kachahri, Karor Road, Layyah", address: "PKM, DPO Office, Near District Kachahri, Karor Road, Layyah", district: "Layyah", lat: 30.9611, lng: 70.9394 },
  { name: "PKM, Rescue 15 Office, Saddar chowk, Lodhran", address: "PKM, Rescue 15 Office, Saddar chowk, Main Bahawalpur Multan Road, Lodhran", district: "Lodhran", lat: 29.5408, lng: 71.6336 },
  { name: "PKM Malakwal, Mandi Bahauddin", address: "PKM Malakwal, Mandi Bahauddin", district: "Mandi Bahauddin", lat: 32.55, lng: 73.2167 },
  { name: "PKM Phalia, Mandi Bahauddin", address: "PKM Phalia, Mandi Bahauddin", district: "Mandi Bahauddin", lat: 32.4333, lng: 73.5833 },
  { name: "PKM, DPO Office, District Complex, Mandi Bahauddin", address: "PKM, DPO Office, District Complex, Mandi Bahauddin", district: "Mandi Bahauddin", lat: 32.5833, lng: 73.4833 },
  { name: "PKM, Jahaz Chok, Mianwali", address: "PKM, Jahaz Chok, Mianwali", district: "Mianwali", lat: 32.5833, lng: 71.5333 },
  { name: "PKM Kukran Wala Kalabagh, Mianwali", address: "PKM Kukran Wala Kalabagh, Mianwali", district: "Mianwali", lat: 32.9667, lng: 71.55 },
  { name: "PKM Katcha Pacca Morr Kundian, Mianwali", address: "PKM Katcha Pacca Morr Kundian, Mianwali", district: "Mianwali", lat: 32.45, lng: 71.4667 },
  { name: "PKM Harnoli Morr, Mianwali", address: "PKM Harnoli Morr, Mianwali", district: "Mianwali", lat: 32.2833, lng: 71.55 },
  { name: "PKM, Police 15 Center, Qilla Kohna Qsim Bagh, Multan", address: "PKM, Police 15 Center, Qilla Kohna Qsim Bagh, Multan", district: "Multan", lat: 30.1978, lng: 71.4697 },
  { name: "PKM Kot Addu, Muzaffargarh", address: "PKM Kot Addu, Muzaffargarh", district: "Muzaffargarh", lat: 30.4667, lng: 70.9667 },
  { name: "PKM, Near Police Station, D.G.Khan Road, Muzaffargarh", address: "PKM, Near Police Station, D.G.Khan Road, Muzaffargarh", district: "Muzaffargarh", lat: 30.08, lng: 71.19 },
  { name: "PKM, Rescue 15 Office, Nankana Sahib", address: "PKM, Rescue 15 Office, Near Bus stand, Nankana Sahib", district: "Nankana Sahib", lat: 31.4489, lng: 73.7125 },
  { name: "PKM, Near old D.C.O house, Narowal", address: "PKM, Near old D.C.O house, Main Circular Road, Narowal", district: "Narowal", lat: 32.1, lng: 74.8833 },
  { name: "PKM Renala Khurrd, Okara", address: "PKM Renala Khurrd, Okara", district: "Okara", lat: 30.8833, lng: 73.6 },
  { name: "PKM, Traffic Head Quarter, Okara", address: "PKM, Traffic Head Quarter, Near Sanam Cinema, M.A Jinnah Road, Okara", district: "Okara", lat: 30.81, lng: 73.4594 },
  { name: "PKM, DPO office, Pakpattan", address: "PKM, DPO office, Pakpattan", district: "Pakpattan", lat: 30.35, lng: 73.4 },
  { name: "PKM SDPO Office Sadiqabad, Rahim yar khan", address: "PKM SDPO Office Sadiqabad, Rahim yar khan", district: "Rahim Yar Khan", lat: 28.31, lng: 70.13 },
  { name: "PKM, DPO office, Rahim yar khan", address: "PKM, DPO office, Near district court, Rahim yar khan", district: "Rahim Yar Khan", lat: 28.4208, lng: 70.3019 },
  { name: "PKM SDPO Office Liaqatpur, Rahim yar khan", address: "PKM SDPO Office Liaqatpur, Rahim yar khan", district: "Rahim Yar Khan", lat: 28.93, lng: 70.95 },
  { name: "PKM, Nearby Police Station Sadar, Rajanpur", address: "PKM, Nearby Police Station Sadar, Rajanpur", district: "Rajanpur", lat: 29.1, lng: 70.3167 },
  { name: "PKM Jampur, Rajanpur", address: "PKM Jampur, Rajanpur", district: "Rajanpur", lat: 29.6333, lng: 70.5833 },
  { name: "PKM & Tahafuz Center, Rawalpindi", address: "PKM & Tahafuz Center, Rawalpindi", district: "Rawalpindi", lat: 33.6, lng: 73.0667 },
  { name: "PKM Gujjar Khan, Rawalpindi", address: "PKM Gujjar Khan, Rawalpindi", district: "Rawalpindi", lat: 33.25, lng: 73.3 },
  { name: "PKM Murree, Rawalpindi", address: "PKM Murree, Rawalpindi", district: "Rawalpindi", lat: 33.9042, lng: 73.3903 },
  { name: "PKM Taxila, Rawalpindi", address: "PKM Taxila, Rawalpindi", district: "Rawalpindi", lat: 33.7458, lng: 72.825 },
  { name: "PKM, Rescue 15 office, Murree Road, Rawalpindi", address: "PKM, Rescue 15 office, Liaqat Bagh Metro Station, Murree Road, Rawalpindi", district: "Rawalpindi", lat: 33.6061, lng: 73.0617 },
  { name: "PKM Chichawatni, Sahiwal", address: "PKM Chichawatni, Sahiwal", district: "Sahiwal", lat: 30.53, lng: 72.7 },
  { name: "PKM Shahpur, Sargodha", address: "PKM Shahpur, Sargodha", district: "Sargodha", lat: 32.3, lng: 72.4667 },
  { name: "PKM Kotmomin, Sargodha", address: "PKM Kotmomin, Sargodha", district: "Sargodha", lat: 32.1833, lng: 73.0333 },
  { name: "PKM, Jail Road Sargodha", address: "Jail Road Sargodha", district: "Sargodha", lat: 32.0833, lng: 72.6711 },
  { name: "PKM Bhalwal, Sargodha", address: "PKM Bhalwal, Sargodha", district: "Sargodha", lat: 32.2667, lng: 72.9 },
  { name: "PKM Sheikhupura", address: "Sargodha road outside police station B/division sheikhupura", district: "Sheikhupura", lat: 31.7131, lng: 73.9844 },
  { name: "PKM Pasrur, Sialkot", address: "PKM Pasrur, Sialkot", district: "Sialkot", lat: 32.2667, lng: 74.6667 },
  { name: "PKM, Police Lines, Sialkot", address: "Police Lines, Sialkot", district: "Sialkot", lat: 32.5, lng: 74.5333 },
  { name: "PKM Daska, Sialkot", address: "PKM Daska, Sialkot", district: "Sialkot", lat: 32.3333, lng: 74.35 },
  { name: "PKM Sambrial, Sialkot", address: "PKM Sambrial, Sialkot", district: "Sialkot", lat: 32.48, lng: 74.35 },
  { name: "PKM, DPO Office, Toba Tek Singh", address: "PKM, DPO Office, District Office Complex, Toba Tek Singh", district: "Toba Tek Singh", lat: 31.15, lng: 72.4833 },
  { name: "PKM Burewala, Vehari", address: "PKM Burewala, Vehari", district: "Vehari", lat: 30.1569, lng: 72.6842 },
  { name: "PKM Mailsi, Vehari", address: "PKM Mailsi, Vehari", district: "Vehari", lat: 29.85, lng: 72.1833 },
  { name: "DPO Office Vehari City", address: "DPO Office Vehari City", district: "Vehari", lat: 30.0419, lng: 72.3528 },
];
