-- -- Enable RLS for admins (update existing policies or add new ones)

-- -- Policy for Admins to VIEW ALL chats
-- -- We assume the admin email is 'khashir657@gmail.com' based on middleware.ts or checked via app_metadata
-- -- For robust security, usage of custom claims consists of a better approach, 
-- -- but checking email in RLS is a quick fix for this specific user.

-- create policy "Admins can view all chats"
--   on public.support_chats for select
--   using (
--     auth.jwt() ->> 'email' = 'khashir657@gmail.com' 
--     OR 
--     exists (
--       select 1 from public.profiles
--       where id = auth.uid() and email = 'khashir657@gmail.com'
--     )
--   );

-- create policy "Admins can view all messages"
--   on public.support_messages for select
--   using (
--     exists (
--         select 1 from public.support_chats
--         where id = support_messages.chat_id
--     ) 
--     AND (
--         auth.jwt() ->> 'email' = 'khashir657@gmail.com'
--         OR
--         exists (
--           select 1 from public.profiles
--           where id = auth.uid() and email = 'khashir657@gmail.com'
--         )
--     )
--   );

-- create policy "Admins can reply to any chat"
--   on public.support_messages for insert
--   with check (
--     auth.jwt() ->> 'email' = 'khashir657@gmail.com'
--     OR
--     exists (
--       select 1 from public.profiles
--       where id = auth.uid() and email = 'khashir657@gmail.com'
--     )
--   );
