// Generated 397 fields for Form I-129F
import type { Field } from './types';

export const formId = 'i129f';
export const formTitle = 'Form I-129F';
export const formSubtitle = 'Petition for Alien Fiance(e)';

export const formFields: Field[] = [
  // === Part 6: Interpreter Information ===
  { key: 's_pt6_nameoflanguage', pdfKey: 's_pt6_nameoflanguage', label: 'S_Pt6_Nameoflanguage', type: 'text', section: 'Part 6: Interpreter Information' },
  // === Part 8: Additional Information ===
  { key: 'pt8_l1_aliennumber', pdfKey: 'pt8_l1_aliennumber', label: 'A-Number', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l2_acctidentifier', pdfKey: 'pt8_l2_acctidentifier', label: 'Acctidentifier', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l3_ssn', pdfKey: 'pt8_l3_ssn', label: 'Social Security Number', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l4a_checkboxes', pdfKey: 'pt8_l4a_checkboxes', label: 'Part 8, Item 4a', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l4a_checkboxes_1', pdfKey: 'pt8_l4a_checkboxes_1', label: 'Part 8, Item 4a', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5_checkboxes', pdfKey: 'pt8_l5_checkboxes', label: 'Part 8, Item 5', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5_checkboxes_1', pdfKey: 'pt8_l5_checkboxes_1', label: 'Part 8, Item 5', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6a_familyname', pdfKey: 'pt8_l6a_familyname', label: 'Family Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6b_givenname', pdfKey: 'pt8_l6b_givenname', label: 'Given Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6c_middlename', pdfKey: 'pt8_l6c_middlename', label: 'Middle Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l7a_familyname', pdfKey: 'pt8_l7a_familyname', label: 'Family Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l7b_givenname', pdfKey: 'pt8_l7b_givenname', label: 'Given Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l7c_middlename', pdfKey: 'pt8_l7c_middlename', label: 'Middle Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l8_aptsteflrnumber', pdfKey: 'pt8_l8_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l8_cityortown', pdfKey: 'pt8_l8_cityortown', label: 'City or Town', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l8_country', pdfKey: 'pt8_l8_country', label: 'Country', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l8_incareofname', pdfKey: 'pt8_l8_incareofname', label: 'Incareofname', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l8_postalcode', pdfKey: 'pt8_l8_postalcode', label: 'Postalcode', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l8_province', pdfKey: 'pt8_l8_province', label: 'Province', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l8_state', pdfKey: 'pt8_l8_state', label: 'State', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l8_streetnumbername', pdfKey: 'pt8_l8_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l8_unit', pdfKey: 'pt8_l8_unit', label: 'Unit', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l8_unit_1', pdfKey: 'pt8_l8_unit_1', label: 'Unit (1)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l8_unit_2', pdfKey: 'pt8_l8_unit_2', label: 'Unit (2)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l8_zipcode', pdfKey: 'pt8_l8_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l8j_checkboxes', pdfKey: 'pt8_l8j_checkboxes', label: 'Part 8, Item 8j', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l8j_checkboxes_1', pdfKey: 'pt8_l8j_checkboxes_1', label: 'Part 8, Item 8j', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l10a_datefrom', pdfKey: 'pt8_l10a_datefrom', label: 'Datefrom', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l10b_tofrom', pdfKey: 'pt8_l10b_tofrom', label: 'Tofrom', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l11_aptsteflrnumber', pdfKey: 'pt8_l11_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l11_cityortown', pdfKey: 'pt8_l11_cityortown', label: 'City or Town', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l11_country', pdfKey: 'pt8_l11_country', label: 'Country', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l11_postalcode', pdfKey: 'pt8_l11_postalcode', label: 'Postalcode', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l11_province', pdfKey: 'pt8_l11_province', label: 'Province', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l11_state', pdfKey: 'pt8_l11_state', label: 'State', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l11_streetnumbername', pdfKey: 'pt8_l11_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l11_unit', pdfKey: 'pt8_l11_unit', label: 'Unit', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l11_unit_1', pdfKey: 'pt8_l11_unit_1', label: 'Unit (1)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l11_unit_2', pdfKey: 'pt8_l11_unit_2', label: 'Unit (2)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l11_zipcode', pdfKey: 'pt8_l11_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l12a_datefrom', pdfKey: 'pt8_l12a_datefrom', label: 'Datefrom', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l12b_tofrom', pdfKey: 'pt8_l12b_tofrom', label: 'Tofrom', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l13_nameofemployer', pdfKey: 'pt8_l13_nameofemployer', label: 'Nameofemployer', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l14_aptsteflrnumber', pdfKey: 'pt8_l14_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l14_cityortown', pdfKey: 'pt8_l14_cityortown', label: 'City or Town', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l14_country', pdfKey: 'pt8_l14_country', label: 'Country', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l14_postalcode', pdfKey: 'pt8_l14_postalcode', label: 'Postalcode', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l14_province', pdfKey: 'pt8_l14_province', label: 'Province', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l14_state', pdfKey: 'pt8_l14_state', label: 'State', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l14_streetnumbername', pdfKey: 'pt8_l14_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l14_unit', pdfKey: 'pt8_l14_unit', label: 'Unit', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l14_unit_1', pdfKey: 'pt8_l14_unit_1', label: 'Unit (1)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l14_unit_2', pdfKey: 'pt8_l14_unit_2', label: 'Unit (2)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l14_zipcode', pdfKey: 'pt8_l14_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l15_occupation', pdfKey: 'pt8_l15_occupation', label: 'Occupation', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l16a_datefrom', pdfKey: 'pt8_l16a_datefrom', label: 'Datefrom', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l16b_tofrom', pdfKey: 'pt8_l16b_tofrom', label: 'Tofrom', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l17_nameofemployer', pdfKey: 'pt8_l17_nameofemployer', label: 'Nameofemployer', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l18_aptsteflrnumber', pdfKey: 'pt8_l18_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l18_cityortown', pdfKey: 'pt8_l18_cityortown', label: 'City or Town', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l18_country', pdfKey: 'pt8_l18_country', label: 'Country', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l18_postalcode', pdfKey: 'pt8_l18_postalcode', label: 'Postalcode', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l18_province', pdfKey: 'pt8_l18_province', label: 'Province', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l18_state', pdfKey: 'pt8_l18_state', label: 'State', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l18_streetnumbername', pdfKey: 'pt8_l18_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l18_unit', pdfKey: 'pt8_l18_unit', label: 'Unit', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l18_unit_1', pdfKey: 'pt8_l18_unit_1', label: 'Unit (1)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l18_unit_2', pdfKey: 'pt8_l18_unit_2', label: 'Unit (2)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l18_zipcode', pdfKey: 'pt8_l18_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l19_occupation', pdfKey: 'pt8_l19_occupation', label: 'Occupation', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l9_aptsteflrnumber', pdfKey: 'pt8_l9_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l9_cityortown', pdfKey: 'pt8_l9_cityortown', label: 'City or Town', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l9_country', pdfKey: 'pt8_l9_country', label: 'Country', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l9_postalcode', pdfKey: 'pt8_l9_postalcode', label: 'Postalcode', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l9_province', pdfKey: 'pt8_l9_province', label: 'Province', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l9_state', pdfKey: 'pt8_l9_state', label: 'State', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l9_streetnumbername', pdfKey: 'pt8_l9_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l9_unit', pdfKey: 'pt8_l9_unit', label: 'Unit', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l9_unit_1', pdfKey: 'pt8_l9_unit_1', label: 'Unit (1)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l9_unit_2', pdfKey: 'pt8_l9_unit_2', label: 'Unit (2)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l9_zipcode', pdfKey: 'pt8_l9_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l20_checkboxes', pdfKey: 'pt8_l20_checkboxes', label: 'Part 8, Item 20', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l20_checkboxes_1', pdfKey: 'pt8_l20_checkboxes_1', label: 'Part 8, Item 20', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l20a_datefrom', pdfKey: 'pt8_l20a_datefrom', label: 'Datefrom', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l20b_tofrom', pdfKey: 'pt8_l20b_tofrom', label: 'Tofrom', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l21_checkbox', pdfKey: 'pt8_l21_checkbox', label: 'Part 8, Item 21', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l21_checkbox_1', pdfKey: 'pt8_l21_checkbox_1', label: 'Part 8, Item 21', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l22_dateofbirth', pdfKey: 'pt8_l22_dateofbirth', label: 'Dateofbirth', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l23_checkbox', pdfKey: 'pt8_l23_checkbox', label: 'Part 8, Item 23', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l23_checkbox_1', pdfKey: 'pt8_l23_checkbox_1', label: 'Part 8, Item 23', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l23_checkbox_2', pdfKey: 'pt8_l23_checkbox_2', label: 'Part 8, Item 23', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l23_checkbox_3', pdfKey: 'pt8_l23_checkbox_3', label: 'Part 8, Item 23', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l24_citytownofbirth', pdfKey: 'pt8_l24_citytownofbirth', label: 'City/Town of Birth', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l25_provinceorstateofbirth', pdfKey: 'pt8_l25_provinceorstateofbirth', label: 'Provinceorstateofbirth', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l26_countryofcitzornationality', pdfKey: 'pt8_l26_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l27a_familyname', pdfKey: 'pt8_l27a_familyname', label: 'Family Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l27b_givenname', pdfKey: 'pt8_l27b_givenname', label: 'Given Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l27c_middlename', pdfKey: 'pt8_l27c_middlename', label: 'Middle Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l28_dateofbirth', pdfKey: 'pt8_l28_dateofbirth', label: 'Dateofbirth', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l29_checkbox', pdfKey: 'pt8_l29_checkbox', label: 'Part 8, Item 29', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l29_checkbox_1', pdfKey: 'pt8_l29_checkbox_1', label: 'Part 8, Item 29', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l30_countryofcitzornationality', pdfKey: 'pt8_l30_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l31_citytownofbirth', pdfKey: 'pt8_l31_citytownofbirth', label: 'City/Town of Birth', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l31_countryofcitzornationality', pdfKey: 'pt8_l31_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l32a_familyname', pdfKey: 'pt8_l32a_familyname', label: 'Family Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l32b_givenname', pdfKey: 'pt8_l32b_givenname', label: 'Given Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l32c_middlename', pdfKey: 'pt8_l32c_middlename', label: 'Middle Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l33_dateofbirth', pdfKey: 'pt8_l33_dateofbirth', label: 'Dateofbirth', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l34_checkbox', pdfKey: 'pt8_l34_checkbox', label: 'Part 8, Item 34', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l34_checkbox_1', pdfKey: 'pt8_l34_checkbox_1', label: 'Part 8, Item 34', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l35_countryofcitzornationality', pdfKey: 'pt8_l35_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l36a_citytownofbirth', pdfKey: 'pt8_l36a_citytownofbirth', label: 'City/Town of Birth', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l36b_countryofcitzornationality', pdfKey: 'pt8_l36b_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l37_checkboxes', pdfKey: 'pt8_l37_checkboxes', label: 'Part 8, Item 37', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l37_checkboxes_1', pdfKey: 'pt8_l37_checkboxes_1', label: 'Part 8, Item 37', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l38a_familyname', pdfKey: 'pt8_l38a_familyname', label: 'Family Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l38b_givenname', pdfKey: 'pt8_l38b_givenname', label: 'Given Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l38c_middlename', pdfKey: 'pt8_l38c_middlename', label: 'Middle Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l39_datemarriageended', pdfKey: 'pt8_l39_datemarriageended', label: 'Datemarriageended', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l40_checkbox', pdfKey: 'pt8_l40_checkbox', label: 'Part 8, Item 40', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l40_checkbox_1', pdfKey: 'pt8_l40_checkbox_1', label: 'Part 8, Item 40', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l40_checkbox_2', pdfKey: 'pt8_l40_checkbox_2', label: 'Part 8, Item 40', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l10a_familyname', pdfKey: 'pt8_l10a_familyname', label: 'Family Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l10b_givenname', pdfKey: 'pt8_l10b_givenname', label: 'Given Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l10c_middlename', pdfKey: 'pt8_l10c_middlename', label: 'Middle Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l1a_familyname', pdfKey: 'pt8_l1a_familyname', label: 'Family Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l1b_givenname', pdfKey: 'pt8_l1b_givenname', label: 'Given Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l1c_middlename', pdfKey: 'pt8_l1c_middlename', label: 'Middle Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l21a_certificatenumber', pdfKey: 'pt8_l21a_certificatenumber', label: 'Certificatenumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l21b_placeofissuance', pdfKey: 'pt8_l21b_placeofissuance', label: 'Placeofissuance', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l21c_dateofissuance', pdfKey: 'pt8_l21c_dateofissuance', label: 'Dateofissuance', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l2_aliennumber', pdfKey: 'pt8_l2_aliennumber', label: 'A-Number', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l43_checkboxes', pdfKey: 'pt8_l43_checkboxes', label: 'Part 8, Item 43', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l43_checkboxes_1', pdfKey: 'pt8_l43_checkboxes_1', label: 'Part 8, Item 43', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l44_aliennumber', pdfKey: 'pt8_l44_aliennumber', label: 'A-Number', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l45a_familyname', pdfKey: 'pt8_l45a_familyname', label: 'Family Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l45b_givenname', pdfKey: 'pt8_l45b_givenname', label: 'Given Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l45c_middlename', pdfKey: 'pt8_l45c_middlename', label: 'Middle Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l46_dateoffiling', pdfKey: 'pt8_l46_dateoffiling', label: 'Dateoffiling', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l47_result', pdfKey: 'pt8_l47_result', label: 'Result', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l48_checkboxes', pdfKey: 'pt8_l48_checkboxes', label: 'Part 8, Item 48', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l48_checkboxes_1', pdfKey: 'pt8_l48_checkboxes_1', label: 'Part 8, Item 48', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l49a_age', pdfKey: 'pt8_l49a_age', label: 'Age', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l49b_age', pdfKey: 'pt8_l49b_age', label: 'Age', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l4_dateofbirth', pdfKey: 'pt8_l4_dateofbirth', label: 'Dateofbirth', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l50a_state', pdfKey: 'pt8_l50a_state', label: 'State', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l50b_countryofcitzornationality', pdfKey: 'pt8_l50b_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l51a_state', pdfKey: 'pt8_l51a_state', label: 'State', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l51b_countryofcitzornationality', pdfKey: 'pt8_l51b_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6_checkboxes', pdfKey: 'pt8_l6_checkboxes', label: 'Part 8, Item 6', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6_checkboxes_1', pdfKey: 'pt8_l6_checkboxes_1', label: 'Part 8, Item 6', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6_checkboxes_2', pdfKey: 'pt8_l6_checkboxes_2', label: 'Part 8, Item 6', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6_checkboxes_3', pdfKey: 'pt8_l6_checkboxes_3', label: 'Part 8, Item 6', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l7_citytownofbirth', pdfKey: 'pt8_l7_citytownofbirth', label: 'City/Town of Birth', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l8_countryofbirth', pdfKey: 'pt8_l8_countryofbirth', label: 'Country of Birth', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l9_countryofcitzornationality', pdfKey: 'pt8_l9_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l11_incareofname', pdfKey: 'pt8_l11_incareofname', label: 'Incareofname', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l12_aptsteflrnumber', pdfKey: 'pt8_l12_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l12_cityortown', pdfKey: 'pt8_l12_cityortown', label: 'City or Town', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l12_country', pdfKey: 'pt8_l12_country', label: 'Country', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l12_postalcode', pdfKey: 'pt8_l12_postalcode', label: 'Postalcode', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l12_province', pdfKey: 'pt8_l12_province', label: 'Province', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l12_state', pdfKey: 'pt8_l12_state', label: 'State', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l12_streetnumbername', pdfKey: 'pt8_l12_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l12_unit', pdfKey: 'pt8_l12_unit', label: 'Unit', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l12_unit_1', pdfKey: 'pt8_l12_unit_1', label: 'Unit (1)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l12_unit_2', pdfKey: 'pt8_l12_unit_2', label: 'Unit (2)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l12_zipcode', pdfKey: 'pt8_l12_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l13a_datefrom', pdfKey: 'pt8_l13a_datefrom', label: 'Datefrom', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l13b_tofrom', pdfKey: 'pt8_l13b_tofrom', label: 'Tofrom', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l15a_datefrom', pdfKey: 'pt8_l15a_datefrom', label: 'Datefrom', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l15b_tofrom', pdfKey: 'pt8_l15b_tofrom', label: 'Tofrom', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l16_nameofemployer', pdfKey: 'pt8_l16_nameofemployer', label: 'Nameofemployer', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l17_aptsteflrnumber', pdfKey: 'pt8_l17_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l17_cityortown', pdfKey: 'pt8_l17_cityortown', label: 'City or Town', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l17_country', pdfKey: 'pt8_l17_country', label: 'Country', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l17_postalcode', pdfKey: 'pt8_l17_postalcode', label: 'Postalcode', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l17_province', pdfKey: 'pt8_l17_province', label: 'Province', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l17_state', pdfKey: 'pt8_l17_state', label: 'State', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l17_streetnumbername', pdfKey: 'pt8_l17_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l17_unit', pdfKey: 'pt8_l17_unit', label: 'Unit', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l17_unit_1', pdfKey: 'pt8_l17_unit_1', label: 'Unit (1)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l17_unit_2', pdfKey: 'pt8_l17_unit_2', label: 'Unit (2)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l17_zipcode', pdfKey: 'pt8_l17_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l18_occupation', pdfKey: 'pt8_l18_occupation', label: 'Occupation', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l19a_datefrom', pdfKey: 'pt8_l19a_datefrom', label: 'Datefrom', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l19b_tofrom', pdfKey: 'pt8_l19b_tofrom', label: 'Tofrom', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l11_dateofbirth', pdfKey: 'pt8_l11_dateofbirth', label: 'Dateofbirth', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l20_nameofemployer', pdfKey: 'pt8_l20_nameofemployer', label: 'Nameofemployer', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l21_aptsteflrnumber', pdfKey: 'pt8_l21_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l21_cityortown', pdfKey: 'pt8_l21_cityortown', label: 'City or Town', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l21_country', pdfKey: 'pt8_l21_country', label: 'Country', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l21_postalcode', pdfKey: 'pt8_l21_postalcode', label: 'Postalcode', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l21_province', pdfKey: 'pt8_l21_province', label: 'Province', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l21_state', pdfKey: 'pt8_l21_state', label: 'State', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l21_streetnumbername', pdfKey: 'pt8_l21_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l21_unit', pdfKey: 'pt8_l21_unit', label: 'Unit', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l21_unit_1', pdfKey: 'pt8_l21_unit_1', label: 'Unit (1)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l21_unit_2', pdfKey: 'pt8_l21_unit_2', label: 'Unit (2)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l21_zipcode', pdfKey: 'pt8_l21_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l22_occupation', pdfKey: 'pt8_l22_occupation', label: 'Occupation', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l23a_datefrom', pdfKey: 'pt8_l23a_datefrom', label: 'Datefrom', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l23b_tofrom', pdfKey: 'pt8_l23b_tofrom', label: 'Tofrom', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l24a_familyname', pdfKey: 'pt8_l24a_familyname', label: 'Family Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l24b_givenname', pdfKey: 'pt8_l24b_givenname', label: 'Given Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l24c_middlename', pdfKey: 'pt8_l24c_middlename', label: 'Middle Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l26_checkbox', pdfKey: 'pt8_l26_checkbox', label: 'Part 8, Item 26', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l26_checkbox_1', pdfKey: 'pt8_l26_checkbox_1', label: 'Part 8, Item 26', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l27_countryofcitzornationality', pdfKey: 'pt8_l27_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l28a_citytownofbirth', pdfKey: 'pt8_l28a_citytownofbirth', label: 'City/Town of Birth', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l28b_countryofcitzornationality', pdfKey: 'pt8_l28b_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l29a_familyname', pdfKey: 'pt8_l29a_familyname', label: 'Family Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l29b_givenname', pdfKey: 'pt8_l29b_givenname', label: 'Given Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l29c_middlename', pdfKey: 'pt8_l29c_middlename', label: 'Middle Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l30_dateofbirth', pdfKey: 'pt8_l30_dateofbirth', label: 'Dateofbirth', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l31_checkbox', pdfKey: 'pt8_l31_checkbox', label: 'Part 8, Item 31', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l31_checkbox_1', pdfKey: 'pt8_l31_checkbox_1', label: 'Part 8, Item 31', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l32_countryofcitzornationality', pdfKey: 'pt8_l32_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l33a_citytownofbirth', pdfKey: 'pt8_l33a_citytownofbirth', label: 'City/Town of Birth', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l33b_countryofcitzornationality', pdfKey: 'pt8_l33b_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l34_checkboxes', pdfKey: 'pt8_l34_checkboxes', label: 'Part 8, Item 34', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l34_checkboxes_1', pdfKey: 'pt8_l34_checkboxes_1', label: 'Part 8, Item 34', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l35a_familyname', pdfKey: 'pt8_l35a_familyname', label: 'Family Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l35b_givenname', pdfKey: 'pt8_l35b_givenname', label: 'Given Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l35c_middlename', pdfKey: 'pt8_l35c_middlename', label: 'Middle Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l36_datemarriageended', pdfKey: 'pt8_l36_datemarriageended', label: 'Datemarriageended', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l38a_lastarrivedas', pdfKey: 'pt8_l38a_lastarrivedas', label: 'Lastarrivedas', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l38b_arrivaldeparture', pdfKey: 'pt8_l38b_arrivaldeparture', label: 'Arrivaldeparture', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l38c_dateofarrival', pdfKey: 'pt8_l38c_dateofarrival', label: 'Dateofarrival', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l28c_cityortown', pdfKey: 'pt8_l28c_cityortown', label: 'City or Town', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l28d_province', pdfKey: 'pt8_l28d_province', label: 'Province', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l28e_postalcode', pdfKey: 'pt8_l28e_postalcode', label: 'Postalcode', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l28f_country', pdfKey: 'pt8_l28f_country', label: 'Country', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l38d_dateexpired', pdfKey: 'pt8_l38d_dateexpired', label: 'Dateexpired', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l38e_passport', pdfKey: 'pt8_l38e_passport', label: 'Passport', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l38f_traveldoc', pdfKey: 'pt8_l38f_traveldoc', label: 'Traveldoc', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l38g_countryofissuance', pdfKey: 'pt8_l38g_countryofissuance', label: 'Countryofissuance', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l38h_expdate', pdfKey: 'pt8_l38h_expdate', label: 'Expdate', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l39_checkboxes', pdfKey: 'pt8_l39_checkboxes', label: 'Part 8, Item 39', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l39_checkboxes_1', pdfKey: 'pt8_l39_checkboxes_1', label: 'Part 8, Item 39', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l40a_familyname', pdfKey: 'pt8_l40a_familyname', label: 'Family Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l40b_givenname', pdfKey: 'pt8_l40b_givenname', label: 'Given Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l40c_middlename', pdfKey: 'pt8_l40c_middlename', label: 'Middle Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l41_countryofbirth', pdfKey: 'pt8_l41_countryofbirth', label: 'Country of Birth', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l42_dateofbirth', pdfKey: 'pt8_l42_dateofbirth', label: 'Dateofbirth', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l44_aptsteflrnumber', pdfKey: 'pt8_l44_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l44_cityortown', pdfKey: 'pt8_l44_cityortown', label: 'City or Town', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l44_country', pdfKey: 'pt8_l44_country', label: 'Country', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l44_postalcode', pdfKey: 'pt8_l44_postalcode', label: 'Postalcode', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l44_province', pdfKey: 'pt8_l44_province', label: 'Province', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l44_state', pdfKey: 'pt8_l44_state', label: 'State', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l44_streetnumbername', pdfKey: 'pt8_l44_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l44_unit', pdfKey: 'pt8_l44_unit', label: 'Unit', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l44_unit_1', pdfKey: 'pt8_l44_unit_1', label: 'Unit (1)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l44_unit_2', pdfKey: 'pt8_l44_unit_2', label: 'Unit (2)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l44_zipcode', pdfKey: 'pt8_l44_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l45a_streetnumbername', pdfKey: 'pt8_l45a_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l45b_aptsteflrnumber', pdfKey: 'pt8_l45b_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l45b_unit', pdfKey: 'pt8_l45b_unit', label: 'Unit', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l45b_unit_1', pdfKey: 'pt8_l45b_unit_1', label: 'Unit (1)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l45b_unit_2', pdfKey: 'pt8_l45b_unit_2', label: 'Unit (2)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l45c_cityortown', pdfKey: 'pt8_l45c_cityortown', label: 'City or Town', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l45d_state', pdfKey: 'pt8_l45d_state', label: 'State', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l45e_zipcode', pdfKey: 'pt8_l45e_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l46_daytimetelephonenumber', pdfKey: 'pt8_l46_daytimetelephonenumber', label: 'Daytimetelephonenumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l47_aptsteflrnumber', pdfKey: 'pt8_l47_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l47_cityortown', pdfKey: 'pt8_l47_cityortown', label: 'City or Town', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l47_country', pdfKey: 'pt8_l47_country', label: 'Country', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l47_postalcode', pdfKey: 'pt8_l47_postalcode', label: 'Postalcode', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l47_province', pdfKey: 'pt8_l47_province', label: 'Province', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l47_streetnumbername', pdfKey: 'pt8_l47_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l47_unit', pdfKey: 'pt8_l47_unit', label: 'Unit', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l47_unit_1', pdfKey: 'pt8_l47_unit_1', label: 'Unit (1)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l47_unit_2', pdfKey: 'pt8_l47_unit_2', label: 'Unit (2)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l48_daytimetelephonenum', pdfKey: 'pt8_l48_daytimetelephonenum', label: 'Daytimetelephonenum', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l49a_familyname', pdfKey: 'pt8_l49a_familyname', label: 'Family Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l49b_givenname', pdfKey: 'pt8_l49b_givenname', label: 'Given Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l49c_middlename', pdfKey: 'pt8_l49c_middlename', label: 'Middle Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l50_aptsteflrnumber', pdfKey: 'pt8_l50_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l50_streetnumbername', pdfKey: 'pt8_l50_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l50_unit', pdfKey: 'pt8_l50_unit', label: 'Unit', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l50_unit_1', pdfKey: 'pt8_l50_unit_1', label: 'Unit (1)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l50_unit_2', pdfKey: 'pt8_l50_unit_2', label: 'Unit (2)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l1_checkboxes', pdfKey: 'pt8_l1_checkboxes', label: 'Part 8, Item 1', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l1_checkboxes_1', pdfKey: 'pt8_l1_checkboxes_1', label: 'Part 8, Item 1', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l2a_checkboxes', pdfKey: 'pt8_l2a_checkboxes', label: 'Part 8, Item 2a', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l2a_checkboxes_1', pdfKey: 'pt8_l2a_checkboxes_1', label: 'Part 8, Item 2a', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l51_checkboxes', pdfKey: 'pt8_l51_checkboxes', label: 'Part 8, Item 51', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l51_checkboxes_1', pdfKey: 'pt8_l51_checkboxes_1', label: 'Part 8, Item 51', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l51_checkboxes_2', pdfKey: 'pt8_l51_checkboxes_2', label: 'Part 8, Item 51', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l52_relationship', pdfKey: 'pt8_l52_relationship', label: 'Relationship', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l53_checkboxes', pdfKey: 'pt8_l53_checkboxes', label: 'Part 8, Item 53', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l53_checkboxes_1', pdfKey: 'pt8_l53_checkboxes_1', label: 'Part 8, Item 53', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l53_checkboxes_2', pdfKey: 'pt8_l53_checkboxes_2', label: 'Part 8, Item 53', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l54_describe', pdfKey: 'pt8_l54_describe', label: 'Describe', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l55_checkboxes', pdfKey: 'pt8_l55_checkboxes', label: 'Part 8, Item 55', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l55_checkboxes_1', pdfKey: 'pt8_l55_checkboxes_1', label: 'Part 8, Item 55', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l56_imbname', pdfKey: 'pt8_l56_imbname', label: 'Imbname', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l57a_imbfamilyname', pdfKey: 'pt8_l57a_imbfamilyname', label: 'Imbfamilyname', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l57b_imb_givenname', pdfKey: 'pt8_l57b_imb_givenname', label: 'Imb_Given Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l58_imborgname', pdfKey: 'pt8_l58_imborgname', label: 'Imborgname', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l59_imbwebsite', pdfKey: 'pt8_l59_imbwebsite', label: 'Imbwebsite', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l60_aptsteflrnumber', pdfKey: 'pt8_l60_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l60_cityortown', pdfKey: 'pt8_l60_cityortown', label: 'City or Town', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l60_country', pdfKey: 'pt8_l60_country', label: 'Country', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l60_postalcode', pdfKey: 'pt8_l60_postalcode', label: 'Postalcode', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l60_province', pdfKey: 'pt8_l60_province', label: 'Province', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l60_unit', pdfKey: 'pt8_l60_unit', label: 'Unit', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l60_unit_1', pdfKey: 'pt8_l60_unit_1', label: 'Unit (1)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l60_unit_2', pdfKey: 'pt8_l60_unit_2', label: 'Unit (2)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l60a_streetnumbername', pdfKey: 'pt8_l60a_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l61_daytimetelephonenum', pdfKey: 'pt8_l61_daytimetelephonenum', label: 'Daytimetelephonenum', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l62a_citytown', pdfKey: 'pt8_l62a_citytown', label: 'Citytown', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l62b_country', pdfKey: 'pt8_l62b_country', label: 'Country', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l1_checkbox', pdfKey: 'pt8_l1_checkbox', label: 'Part 8, Item 1', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l1_checkbox_1', pdfKey: 'pt8_l1_checkbox_1', label: 'Part 8, Item 1', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l2_checkbox', pdfKey: 'pt8_l2_checkbox', label: 'Part 8, Item 2', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l2_checkbox_1', pdfKey: 'pt8_l2_checkbox_1', label: 'Part 8, Item 2', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l2_checkbox_2', pdfKey: 'pt8_l2_checkbox_2', label: 'Part 8, Item 2', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l2_checkbox_3', pdfKey: 'pt8_l2_checkbox_3', label: 'Part 8, Item 2', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l2_checkbox_4', pdfKey: 'pt8_l2_checkbox_4', label: 'Part 8, Item 2', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l2b_checkboxes', pdfKey: 'pt8_l2b_checkboxes', label: 'Part 8, Item 2b', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l2b_checkboxes_1', pdfKey: 'pt8_l2b_checkboxes_1', label: 'Part 8, Item 2b', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l2c_checkboxes', pdfKey: 'pt8_l2c_checkboxes', label: 'Part 8, Item 2c', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l2c_checkboxes_1', pdfKey: 'pt8_l2c_checkboxes_1', label: 'Part 8, Item 2c', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l3_checkboxes', pdfKey: 'pt8_l3_checkboxes', label: 'Part 8, Item 3', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l3_checkboxes_1', pdfKey: 'pt8_l3_checkboxes_1', label: 'Part 8, Item 3', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l3_checkboxes_2', pdfKey: 'pt8_l3_checkboxes_2', label: 'Part 8, Item 3', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l3_heightfeet', pdfKey: 'pt8_l3_heightfeet', label: 'Heightfeet', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l3_heightinches', pdfKey: 'pt8_l3_heightinches', label: 'Heightinches', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l4B_describe', pdfKey: 'pt8_l4B_describe', label: 'Describe', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l4_heightinches1', pdfKey: 'pt8_l4_heightinches1', label: 'Heightinches1', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l4_heightinches2', pdfKey: 'pt8_l4_heightinches2', label: 'Heightinches2', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l4_heightinches3', pdfKey: 'pt8_l4_heightinches3', label: 'Heightinches3', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5_checkbox', pdfKey: 'pt8_l5_checkbox', label: 'Part 8, Item 5', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5_checkbox_1', pdfKey: 'pt8_l5_checkbox_1', label: 'Part 8, Item 5', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5_checkbox_2', pdfKey: 'pt8_l5_checkbox_2', label: 'Part 8, Item 5', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5_checkbox_3', pdfKey: 'pt8_l5_checkbox_3', label: 'Part 8, Item 5', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5_checkbox_4', pdfKey: 'pt8_l5_checkbox_4', label: 'Part 8, Item 5', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5_checkbox_5', pdfKey: 'pt8_l5_checkbox_5', label: 'Part 8, Item 5', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5_checkbox_6', pdfKey: 'pt8_l5_checkbox_6', label: 'Part 8, Item 5', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5_checkbox_7', pdfKey: 'pt8_l5_checkbox_7', label: 'Part 8, Item 5', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5_checkbox_8', pdfKey: 'pt8_l5_checkbox_8', label: 'Part 8, Item 5', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5_checkboxes_2', pdfKey: 'pt8_l5_checkboxes_2', label: 'Part 8, Item 5', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5_checkboxes_3', pdfKey: 'pt8_l5_checkboxes_3', label: 'Part 8, Item 5', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6_haircolor', pdfKey: 'pt8_l6_haircolor', label: 'Haircolor', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6_haircolor_1', pdfKey: 'pt8_l6_haircolor_1', label: 'Haircolor (1)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6_haircolor_2', pdfKey: 'pt8_l6_haircolor_2', label: 'Haircolor (2)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6_haircolor_3', pdfKey: 'pt8_l6_haircolor_3', label: 'Haircolor (3)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6_haircolor_4', pdfKey: 'pt8_l6_haircolor_4', label: 'Haircolor (4)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6_haircolor_5', pdfKey: 'pt8_l6_haircolor_5', label: 'Haircolor (5)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6_haircolor_6', pdfKey: 'pt8_l6_haircolor_6', label: 'Haircolor (6)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6_haircolor_7', pdfKey: 'pt8_l6_haircolor_7', label: 'Haircolor (7)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6_haircolor_8', pdfKey: 'pt8_l6_haircolor_8', label: 'Haircolor (8)', type: 'checkbox', section: 'Part 8: Additional Information' },
  { key: 'pt8_l1_daytimephonenumber1', pdfKey: 'pt8_l1_daytimephonenumber1', label: 'Daytimephonenumber1', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l1_interpreterfamilyname', pdfKey: 'pt8_l1_interpreterfamilyname', label: 'Interpreterfamilyname', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l1_interpretergivenname', pdfKey: 'pt8_l1_interpretergivenname', label: 'Interpretergivenname', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l1_preparerfamilyname', pdfKey: 'pt8_l1_preparerfamilyname', label: 'Preparerfamilyname', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l1b_preparergivenname', pdfKey: 'pt8_l1b_preparergivenname', label: 'Preparergivenname', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l2_mobilenumber1', pdfKey: 'pt8_l2_mobilenumber1', label: 'Mobilenumber1', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l2_nameofbusinessororgname', pdfKey: 'pt8_l2_nameofbusinessororgname', label: 'Nameofbusinessororgname', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l3_daytimephonenumber1', pdfKey: 'pt8_l3_daytimephonenumber1', label: 'Daytimephonenumber1', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l3_email', pdfKey: 'pt8_l3_email', label: 'Email', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l4_dateofsignature', pdfKey: 'pt8_l4_dateofsignature', label: 'Dateofsignature', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l4_interpreterdaytimetelephone', pdfKey: 'pt8_l4_interpreterdaytimetelephone', label: 'Interpreterdaytimetelephone', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l4_interpreterdaytimetelephone_1', pdfKey: 'pt8_l4_interpreterdaytimetelephone_1', label: 'Interpreterdaytimetelephone (1)', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l4_preparermobilenumber', pdfKey: 'pt8_l4_preparermobilenumber', label: 'Preparermobilenumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l4_signature', pdfKey: 'pt8_l4_signature', label: 'Signature', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5_email', pdfKey: 'pt8_l5_email', label: 'Email', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6_dateofsignature', pdfKey: 'pt8_l6_dateofsignature', label: 'Dateofsignature', type: 'date', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6_signature', pdfKey: 'pt8_l6_signature', label: 'Signature', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6_signatureofpreparer', pdfKey: 'pt8_l6_signatureofpreparer', label: 'Signatureofpreparer', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l1_aliennumber_1', pdfKey: 'pt8_l1_aliennumber_1', label: 'A-Number (1)', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l3a_pagenumber', pdfKey: 'pt8_l3a_pagenumber', label: 'Pagenumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l3b_partnumber', pdfKey: 'pt8_l3b_partnumber', label: 'Partnumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l3c_itemnumber', pdfKey: 'pt8_l3c_itemnumber', label: 'Itemnumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l3d_additionalinfo', pdfKey: 'pt8_l3d_additionalinfo', label: 'Additionalinfo', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l4a_pagenumber', pdfKey: 'pt8_l4a_pagenumber', label: 'Pagenumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l4b_partnumber', pdfKey: 'pt8_l4b_partnumber', label: 'Partnumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l4c_itemnumber', pdfKey: 'pt8_l4c_itemnumber', label: 'Itemnumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l4d_additionalinfo', pdfKey: 'pt8_l4d_additionalinfo', label: 'Additionalinfo', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5a_pagenumber', pdfKey: 'pt8_l5a_pagenumber', label: 'Pagenumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5b_partnumber', pdfKey: 'pt8_l5b_partnumber', label: 'Partnumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5c_itemnumber', pdfKey: 'pt8_l5c_itemnumber', label: 'Itemnumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l5d_additionalinfo', pdfKey: 'pt8_l5d_additionalinfo', label: 'Additionalinfo', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6a_familyname_1', pdfKey: 'pt8_l6a_familyname_1', label: 'Family Name (1)', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6a_pagenumber', pdfKey: 'pt8_l6a_pagenumber', label: 'Pagenumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6b_givenname_1', pdfKey: 'pt8_l6b_givenname_1', label: 'Given Name (1)', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6b_partnumber', pdfKey: 'pt8_l6b_partnumber', label: 'Partnumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6c_itemnumber', pdfKey: 'pt8_l6c_itemnumber', label: 'Itemnumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6c_middlename_1', pdfKey: 'pt8_l6c_middlename_1', label: 'Middle Name (1)', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l6d_additionalinfo', pdfKey: 'pt8_l6d_additionalinfo', label: 'Additionalinfo', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l7a_pagenumber', pdfKey: 'pt8_l7a_pagenumber', label: 'Pagenumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l7b_partnumber', pdfKey: 'pt8_l7b_partnumber', label: 'Partnumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l7c_itemnumber', pdfKey: 'pt8_l7c_itemnumber', label: 'Itemnumber', type: 'text', section: 'Part 8: Additional Information' },
  { key: 'pt8_l7d_additionalinfo', pdfKey: 'pt8_l7d_additionalinfo', label: 'Additionalinfo', type: 'text', section: 'Part 8: Additional Information' },
];

export const getInitialFormData = () => {
  const data: Record<string, string> = {};
  formFields.forEach((f) => { if (f.key != null) data[f.key] = ''; });
  return data;
};

export const i129fConfig = { formId, formTitle, formSubtitle, formFields, getInitialFormData };
export default i129fConfig;