// Generated fields for Form I-129F
import type { Field } from './types';

export const formId = 'i129f';
export const formTitle = 'Form I-129F';
export const formSubtitle = 'Petition for Alien Fiance(e)';

export const formFields: Field[] = [
  // === Part 1: Petitioner Info ===
  { key: 'pt1_l1_AlienNumber', pdfKey: 'pt1_l1_aliennumber', label: 'Petitioner\'s Alien Registration Number (A-Number)', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l2_AcctIdentifier', pdfKey: 'pt1_l2_acctidentifier', label: 'Acct Identifier', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l3_SSN', pdfKey: 'pt1_l3_ssn', label: 'Petitioner\'s U.S. Social Security Number', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l4a_Checkboxes', pdfKey: 'pt1_l4a_checkboxes', label: 'Part 1, Item 4a', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l4a_Checkboxes_1', pdfKey: 'pt1_l4a_checkboxes_1', label: 'Part 1, Item 4a', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l5_Checkboxes', pdfKey: 'pt1_l5_checkboxes', label: 'Part 1, Item 5', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l5_Checkboxes_1', pdfKey: 'pt1_l5_checkboxes_1', label: 'Part 1, Item 5', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l6a_FamilyName', pdfKey: 'pt1_l6a_familyname', label: 'Petitioner\'s Family Name (Last Name)', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l6b_GivenName', pdfKey: 'pt1_l6b_givenname', label: 'Petitioner\'s Given Name (First Name)', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l6c_MiddleName', pdfKey: 'pt1_l6c_middlename', label: 'Petitioner\'s Middle Name', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l7a_FamilyName', pdfKey: 'pt1_l7a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l7b_GivenName', pdfKey: 'pt1_l7b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l7c_MiddleName', pdfKey: 'pt1_l7c_middlename', label: 'Middle Name', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l8_AptSteFlrNumber', pdfKey: 'pt1_l8_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l8_CityOrTown', pdfKey: 'pt1_l8_cityortown', label: 'City or Town', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l8_Country', pdfKey: 'pt1_l8_country', label: 'Country', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l8_InCareofName', pdfKey: 'pt1_l8_incareofname', label: 'In Careof Name', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l8_PostalCode', pdfKey: 'pt1_l8_postalcode', label: 'Postal Code', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l8_Province', pdfKey: 'pt1_l8_province', label: 'Province', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l8_State', pdfKey: 'pt1_l8_state', label: 'State', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l8_StreetNumberName', pdfKey: 'pt1_l8_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l8_Unit', pdfKey: 'pt1_l8_unit', label: 'Unit', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l8_Unit_1', pdfKey: 'pt1_l8_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l8_Unit_2', pdfKey: 'pt1_l8_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l8_ZipCode', pdfKey: 'pt1_l8_zipcode', label: 'Zip Code', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l8j_Checkboxes', pdfKey: 'pt1_l8j_checkboxes', label: 'Part 1, Item 8j', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l8j_Checkboxes_1', pdfKey: 'pt1_l8j_checkboxes_1', label: 'Part 1, Item 8j', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l10a_DateFrom', pdfKey: 'pt1_l10a_datefrom', label: 'Date From', type: 'date', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l10b_ToFrom', pdfKey: 'pt1_l10b_tofrom', label: 'To From', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l11_AptSteFlrNumber', pdfKey: 'pt1_l11_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l11_CityOrTown', pdfKey: 'pt1_l11_cityortown', label: 'City or Town', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l11_Country', pdfKey: 'pt1_l11_country', label: 'Country', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l11_PostalCode', pdfKey: 'pt1_l11_postalcode', label: 'Postal Code', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l11_Province', pdfKey: 'pt1_l11_province', label: 'Province', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l11_State', pdfKey: 'pt1_l11_state', label: 'State', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l11_StreetNumberName', pdfKey: 'pt1_l11_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l11_Unit', pdfKey: 'pt1_l11_unit', label: 'Unit', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l11_Unit_1', pdfKey: 'pt1_l11_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l11_Unit_2', pdfKey: 'pt1_l11_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l11_ZipCode', pdfKey: 'pt1_l11_zipcode', label: 'Zip Code', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l12a_DateFrom', pdfKey: 'pt1_l12a_datefrom', label: 'Date From', type: 'date', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l12b_ToFrom', pdfKey: 'pt1_l12b_tofrom', label: 'To From', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l13_NameofEmployer', pdfKey: 'pt1_l13_nameofemployer', label: 'Nameof Employer', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l14_AptSteFlrNumber', pdfKey: 'pt1_l14_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l14_CityOrTown', pdfKey: 'pt1_l14_cityortown', label: 'City or Town', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l14_Country', pdfKey: 'pt1_l14_country', label: 'Country', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l14_PostalCode', pdfKey: 'pt1_l14_postalcode', label: 'Postal Code', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l14_Province', pdfKey: 'pt1_l14_province', label: 'Province', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l14_State', pdfKey: 'pt1_l14_state', label: 'State', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l14_StreetNumberName', pdfKey: 'pt1_l14_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l14_Unit', pdfKey: 'pt1_l14_unit', label: 'Unit', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l14_Unit_1', pdfKey: 'pt1_l14_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l14_Unit_2', pdfKey: 'pt1_l14_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l14_ZipCode', pdfKey: 'pt1_l14_zipcode', label: 'Zip Code', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l15_Occupation', pdfKey: 'pt1_l15_occupation', label: 'Occupation', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l16a_DateFrom', pdfKey: 'pt1_l16a_datefrom', label: 'Date From', type: 'date', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l16b_ToFrom', pdfKey: 'pt1_l16b_tofrom', label: 'To From', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l17_NameofEmployer', pdfKey: 'pt1_l17_nameofemployer', label: 'Nameof Employer', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l18_AptSteFlrNumber', pdfKey: 'pt1_l18_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l18_CityOrTown', pdfKey: 'pt1_l18_cityortown', label: 'City or Town', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l18_Country', pdfKey: 'pt1_l18_country', label: 'Country', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l18_PostalCode', pdfKey: 'pt1_l18_postalcode', label: 'Postal Code', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l18_Province', pdfKey: 'pt1_l18_province', label: 'Province', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l18_State', pdfKey: 'pt1_l18_state', label: 'State', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l18_StreetNumberName', pdfKey: 'pt1_l18_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l18_Unit', pdfKey: 'pt1_l18_unit', label: 'Unit', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l18_Unit_1', pdfKey: 'pt1_l18_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l18_Unit_2', pdfKey: 'pt1_l18_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l18_ZipCode', pdfKey: 'pt1_l18_zipcode', label: 'Zip Code', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l19_Occupation', pdfKey: 'pt1_l19_occupation', label: 'Occupation', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l9_AptSteFlrNumber', pdfKey: 'pt1_l9_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l9_CityOrTown', pdfKey: 'pt1_l9_cityortown', label: 'City or Town', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l9_Country', pdfKey: 'pt1_l9_country', label: 'Country', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l9_PostalCode', pdfKey: 'pt1_l9_postalcode', label: 'Postal Code', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l9_Province', pdfKey: 'pt1_l9_province', label: 'Province', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l9_State', pdfKey: 'pt1_l9_state', label: 'State', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l9_StreetNumberName', pdfKey: 'pt1_l9_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l9_Unit', pdfKey: 'pt1_l9_unit', label: 'Unit', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l9_Unit_1', pdfKey: 'pt1_l9_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l9_Unit_2', pdfKey: 'pt1_l9_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l9_ZipCode', pdfKey: 'pt1_l9_zipcode', label: 'Zip Code', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l20_Checkboxes', pdfKey: 'pt1_l20_checkboxes', label: 'Part 1, Item 20', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l20_Checkboxes_1', pdfKey: 'pt1_l20_checkboxes_1', label: 'Part 1, Item 20', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l20a_DateFrom', pdfKey: 'pt1_l20a_datefrom', label: 'Date From', type: 'date', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l20b_ToFrom', pdfKey: 'pt1_l20b_tofrom', label: 'To From', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l21_Checkbox', pdfKey: 'pt1_l21_checkbox', label: 'Part 1, Item 21', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l21_Checkbox_1', pdfKey: 'pt1_l21_checkbox_1', label: 'Part 1, Item 21', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l22_DateofBirth', pdfKey: 'pt1_l22_dateofbirth', label: 'Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l23_Checkbox', pdfKey: 'pt1_l23_checkbox', label: 'Part 1, Item 23', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l23_Checkbox_1', pdfKey: 'pt1_l23_checkbox_1', label: 'Part 1, Item 23', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l23_Checkbox_2', pdfKey: 'pt1_l23_checkbox_2', label: 'Part 1, Item 23', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l23_Checkbox_3', pdfKey: 'pt1_l23_checkbox_3', label: 'Part 1, Item 23', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l24_CityTownOfBirth', pdfKey: 'pt1_l24_citytownofbirth', label: 'City Town of Birth', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l25_ProvinceOrStateOfBirth', pdfKey: 'pt1_l25_provinceorstateofbirth', label: 'Province or State of Birth', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l26_CountryOfCitzOrNationality', pdfKey: 'pt1_l26_countryofcitzornationality', label: 'Country of Citz or Nationality', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l27a_FamilyName', pdfKey: 'pt1_l27a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l27b_GivenName', pdfKey: 'pt1_l27b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l27c_MiddleName', pdfKey: 'pt1_l27c_middlename', label: 'Middle Name', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l28_DateofBirth', pdfKey: 'pt1_l28_dateofbirth', label: 'Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l29_Checkbox', pdfKey: 'pt1_l29_checkbox', label: 'Part 1, Item 29', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l29_Checkbox_1', pdfKey: 'pt1_l29_checkbox_1', label: 'Part 1, Item 29', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l30_CountryOfCitzOrNationality', pdfKey: 'pt1_l30_countryofcitzornationality', label: 'Country of Citz or Nationality', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l31_CityTownOfBirth', pdfKey: 'pt1_l31_citytownofbirth', label: 'City Town of Birth', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l31_CountryOfCitzOrNationality', pdfKey: 'pt1_l31_countryofcitzornationality', label: 'Country of Citz or Nationality', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l32a_FamilyName', pdfKey: 'pt1_l32a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l32b_GivenName', pdfKey: 'pt1_l32b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l32c_MiddleName', pdfKey: 'pt1_l32c_middlename', label: 'Middle Name', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l33_DateofBirth', pdfKey: 'pt1_l33_dateofbirth', label: 'Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l34_Checkbox', pdfKey: 'pt1_l34_checkbox', label: 'Part 1, Item 34', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l34_Checkbox_1', pdfKey: 'pt1_l34_checkbox_1', label: 'Part 1, Item 34', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l35_CountryOfCitzOrNationality', pdfKey: 'pt1_l35_countryofcitzornationality', label: 'Country of Citz or Nationality', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l36a_CityTownOfBirth', pdfKey: 'pt1_l36a_citytownofbirth', label: 'City Town of Birth', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l36b_CountryOfCitzOrNationality', pdfKey: 'pt1_l36b_countryofcitzornationality', label: 'Country of Citz or Nationality', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l37_Checkboxes', pdfKey: 'pt1_l37_checkboxes', label: 'Part 1, Item 37', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l37_Checkboxes_1', pdfKey: 'pt1_l37_checkboxes_1', label: 'Part 1, Item 37', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l38a_FamilyName', pdfKey: 'pt1_l38a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l38b_GivenName', pdfKey: 'pt1_l38b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l38c_MiddleName', pdfKey: 'pt1_l38c_middlename', label: 'Middle Name', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l39_DateMarriageEnded', pdfKey: 'pt1_l39_datemarriageended', label: 'Date Marriage Ended', type: 'date', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l40_Checkbox', pdfKey: 'pt1_l40_checkbox', label: 'Part 1, Item 40', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l40_Checkbox_1', pdfKey: 'pt1_l40_checkbox_1', label: 'Part 1, Item 40', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l40_Checkbox_2', pdfKey: 'pt1_l40_checkbox_2', label: 'Part 1, Item 40', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l21a_CertificateNumber', pdfKey: 'pt1_l21a_certificatenumber', label: 'Certificate Number', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l21b_PlaceofIssuance', pdfKey: 'pt1_l21b_placeofissuance', label: 'Placeof Issuance', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l21c_DateOfIssuance', pdfKey: 'pt1_l21c_dateofissuance', label: 'Date of Issuance', type: 'date', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l43_Checkboxes', pdfKey: 'pt1_l43_checkboxes', label: 'Part 1, Item 43', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l43_Checkboxes_1', pdfKey: 'pt1_l43_checkboxes_1', label: 'Part 1, Item 43', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l44_AlienNumber', pdfKey: 'pt1_l44_aliennumber', label: 'A-Number', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l45a_FamilyName', pdfKey: 'pt1_l45a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l45b_GivenName', pdfKey: 'pt1_l45b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l45c_MiddleName', pdfKey: 'pt1_l45c_middlename', label: 'Middle Name', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l46_DateOfFiling', pdfKey: 'pt1_l46_dateoffiling', label: 'Date of Filing', type: 'date', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l47_Result', pdfKey: 'pt1_l47_result', label: 'Result', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l48_Checkboxes', pdfKey: 'pt1_l48_checkboxes', label: 'Part 1, Item 48', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l48_Checkboxes_1', pdfKey: 'pt1_l48_checkboxes_1', label: 'Part 1, Item 48', type: 'checkbox', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l49a_Age', pdfKey: 'pt1_l49a_age', label: 'Age', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l49b_Age', pdfKey: 'pt1_l49b_age', label: 'Age', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l50a_State', pdfKey: 'pt1_l50a_state', label: 'State', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l50b_CountryOfCitzOrNationality', pdfKey: 'pt1_l50b_countryofcitzornationality', label: 'Country of Citz or Nationality', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l51a_State', pdfKey: 'pt1_l51a_state', label: 'State', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l51b_CountryOfCitzOrNationality', pdfKey: 'pt1_l51b_countryofcitzornationality', label: 'Country of Citz or Nationality', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l11_DateofBirth', pdfKey: 'pt1_l11_dateofbirth', label: 'Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l1_AlienNumber_1', pdfKey: 'pt1_l1_aliennumber_1', label: 'A-Number (Item 2)', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l6a_FamilyName_1', pdfKey: 'pt1_l6a_familyname_1', label: 'Family Name (Last Name) (Item 2)', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l6b_GivenName_1', pdfKey: 'pt1_l6b_givenname_1', label: 'Given Name (First Name) (Item 2)', type: 'text', section: 'Part 1: Petitioner Info' },
  { key: 'pt1_l6c_MiddleName_1', pdfKey: 'pt1_l6c_middlename_1', label: 'Middle Name (Item 2)', type: 'text', section: 'Part 1: Petitioner Info' },
  // === Part 2: Beneficiary Info ===
  { key: 'pt2_l10a_FamilyName', pdfKey: 'pt2_l10a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l10b_GivenName', pdfKey: 'pt2_l10b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l10c_MiddleName', pdfKey: 'pt2_l10c_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l1a_FamilyName', pdfKey: 'pt2_l1a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l1b_GivenName', pdfKey: 'pt2_l1b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l1c_MiddleName', pdfKey: 'pt2_l1c_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l2_AlienNumber', pdfKey: 'pt2_l2_aliennumber', label: 'A-Number', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l3_SSN', pdfKey: 'pt2_l3_ssn', label: 'Social Security Number', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l4_DateOfBirth', pdfKey: 'pt2_l4_dateofbirth', label: 'Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l5_Checkboxes', pdfKey: 'pt2_l5_checkboxes', label: 'Part 2, Item 5', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l5_Checkboxes_1', pdfKey: 'pt2_l5_checkboxes_1', label: 'Part 2, Item 5', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l6_Checkboxes', pdfKey: 'pt2_l6_checkboxes', label: 'Part 2, Item 6', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l6_Checkboxes_1', pdfKey: 'pt2_l6_checkboxes_1', label: 'Part 2, Item 6', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l6_Checkboxes_2', pdfKey: 'pt2_l6_checkboxes_2', label: 'Part 2, Item 6', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l6_Checkboxes_3', pdfKey: 'pt2_l6_checkboxes_3', label: 'Part 2, Item 6', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l7_CityTownOfBirth', pdfKey: 'pt2_l7_citytownofbirth', label: 'City Town of Birth', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l8_CountryOfBirth', pdfKey: 'pt2_l8_countryofbirth', label: 'Country of Birth', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l9_CountryofCitzOrNationality', pdfKey: 'pt2_l9_countryofcitzornationality', label: 'Countryof Citz or Nationality', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l11_AptSteFlrNumber', pdfKey: 'pt2_l11_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l11_CityOrTown', pdfKey: 'pt2_l11_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l11_Country', pdfKey: 'pt2_l11_country', label: 'Country', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l11_InCareOfName', pdfKey: 'pt2_l11_incareofname', label: 'In Care of Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l11_PostalCode', pdfKey: 'pt2_l11_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l11_Province', pdfKey: 'pt2_l11_province', label: 'Province', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l11_State', pdfKey: 'pt2_l11_state', label: 'State', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l11_StreetNumberName', pdfKey: 'pt2_l11_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l11_Unit', pdfKey: 'pt2_l11_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l11_Unit_1', pdfKey: 'pt2_l11_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l11_Unit_2', pdfKey: 'pt2_l11_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l11_ZipCode', pdfKey: 'pt2_l11_zipcode', label: 'Zip Code', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l12_AptSteFlrNumber', pdfKey: 'pt2_l12_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l12_CityOrTown', pdfKey: 'pt2_l12_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l12_Country', pdfKey: 'pt2_l12_country', label: 'Country', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l12_PostalCode', pdfKey: 'pt2_l12_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l12_Province', pdfKey: 'pt2_l12_province', label: 'Province', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l12_State', pdfKey: 'pt2_l12_state', label: 'State', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l12_StreetNumberName', pdfKey: 'pt2_l12_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l12_Unit', pdfKey: 'pt2_l12_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l12_Unit_1', pdfKey: 'pt2_l12_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l12_Unit_2', pdfKey: 'pt2_l12_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l12_ZipCode', pdfKey: 'pt2_l12_zipcode', label: 'Zip Code', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l13a_DateFrom', pdfKey: 'pt2_l13a_datefrom', label: 'Date From', type: 'date', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l13b_ToFrom', pdfKey: 'pt2_l13b_tofrom', label: 'To From', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l14_AptSteFlrNumber', pdfKey: 'pt2_l14_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l14_CityOrTown', pdfKey: 'pt2_l14_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l14_Country', pdfKey: 'pt2_l14_country', label: 'Country', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l14_PostalCode', pdfKey: 'pt2_l14_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l14_Province', pdfKey: 'pt2_l14_province', label: 'Province', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l14_State', pdfKey: 'pt2_l14_state', label: 'State', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l14_StreetNumberName', pdfKey: 'pt2_l14_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l14_Unit', pdfKey: 'pt2_l14_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l14_Unit_1', pdfKey: 'pt2_l14_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l14_Unit_2', pdfKey: 'pt2_l14_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l14_ZipCode', pdfKey: 'pt2_l14_zipcode', label: 'Zip Code', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l15a_DateFrom', pdfKey: 'pt2_l15a_datefrom', label: 'Date From', type: 'date', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l15b_ToFrom', pdfKey: 'pt2_l15b_tofrom', label: 'To From', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l16_NameofEmployer', pdfKey: 'pt2_l16_nameofemployer', label: 'Nameof Employer', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l17_AptSteFlrNumber', pdfKey: 'pt2_l17_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l17_CityOrTown', pdfKey: 'pt2_l17_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l17_Country', pdfKey: 'pt2_l17_country', label: 'Country', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l17_PostalCode', pdfKey: 'pt2_l17_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l17_Province', pdfKey: 'pt2_l17_province', label: 'Province', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l17_State', pdfKey: 'pt2_l17_state', label: 'State', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l17_StreetNumberName', pdfKey: 'pt2_l17_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l17_Unit', pdfKey: 'pt2_l17_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l17_Unit_1', pdfKey: 'pt2_l17_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l17_Unit_2', pdfKey: 'pt2_l17_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l17_ZipCode', pdfKey: 'pt2_l17_zipcode', label: 'Zip Code', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l18_Occupation', pdfKey: 'pt2_l18_occupation', label: 'Occupation', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l19a_DateFrom', pdfKey: 'pt2_l19a_datefrom', label: 'Date From', type: 'date', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l19b_ToFrom', pdfKey: 'pt2_l19b_tofrom', label: 'To From', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l20_NameofEmployer', pdfKey: 'pt2_l20_nameofemployer', label: 'Nameof Employer', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l21_AptSteFlrNumber', pdfKey: 'pt2_l21_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l21_CityOrTown', pdfKey: 'pt2_l21_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l21_Country', pdfKey: 'pt2_l21_country', label: 'Country', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l21_PostalCode', pdfKey: 'pt2_l21_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l21_Province', pdfKey: 'pt2_l21_province', label: 'Province', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l21_State', pdfKey: 'pt2_l21_state', label: 'State', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l21_StreetNumberName', pdfKey: 'pt2_l21_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l21_Unit', pdfKey: 'pt2_l21_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l21_Unit_1', pdfKey: 'pt2_l21_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l21_Unit_2', pdfKey: 'pt2_l21_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l21_ZipCode', pdfKey: 'pt2_l21_zipcode', label: 'Zip Code', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l22_Occupation', pdfKey: 'pt2_l22_occupation', label: 'Occupation', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l23a_DateFrom', pdfKey: 'pt2_l23a_datefrom', label: 'Date From', type: 'date', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l23b_ToFrom', pdfKey: 'pt2_l23b_tofrom', label: 'To From', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l24a_FamilyName', pdfKey: 'pt2_l24a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l24b_GivenName', pdfKey: 'pt2_l24b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l24c_MiddleName', pdfKey: 'pt2_l24c_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l26_Checkbox', pdfKey: 'pt2_l26_checkbox', label: 'Part 2, Item 26', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l26_Checkbox_1', pdfKey: 'pt2_l26_checkbox_1', label: 'Part 2, Item 26', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l27_CountryOfCitzOrNationality', pdfKey: 'pt2_l27_countryofcitzornationality', label: 'Country of Citz or Nationality', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l28a_CityTownOfBirth', pdfKey: 'pt2_l28a_citytownofbirth', label: 'City Town of Birth', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l28b_CountryOfCitzOrNationality', pdfKey: 'pt2_l28b_countryofcitzornationality', label: 'Country of Citz or Nationality', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l29a_FamilyName', pdfKey: 'pt2_l29a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l29b_GivenName', pdfKey: 'pt2_l29b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l29c_MiddleName', pdfKey: 'pt2_l29c_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l30_DateofBirth', pdfKey: 'pt2_l30_dateofbirth', label: 'Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l31_Checkbox', pdfKey: 'pt2_l31_checkbox', label: 'Part 2, Item 31', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l31_Checkbox_1', pdfKey: 'pt2_l31_checkbox_1', label: 'Part 2, Item 31', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l32_CountryOfCitzOrNationality', pdfKey: 'pt2_l32_countryofcitzornationality', label: 'Country of Citz or Nationality', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l33a_CityTownOfBirth', pdfKey: 'pt2_l33a_citytownofbirth', label: 'City Town of Birth', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l33b_CountryOfCitzOrNationality', pdfKey: 'pt2_l33b_countryofcitzornationality', label: 'Country of Citz or Nationality', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l34_Checkboxes', pdfKey: 'pt2_l34_checkboxes', label: 'Part 2, Item 34', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l34_Checkboxes_1', pdfKey: 'pt2_l34_checkboxes_1', label: 'Part 2, Item 34', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l35a_FamilyName', pdfKey: 'pt2_l35a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l35b_GivenName', pdfKey: 'pt2_l35b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l35c_MiddleName', pdfKey: 'pt2_l35c_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l36_DateMarriageEnded', pdfKey: 'pt2_l36_datemarriageended', label: 'Date Marriage Ended', type: 'date', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l37_Checkboxes', pdfKey: 'pt2_l37_checkboxes', label: 'Part 2, Item 37', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l37_Checkboxes_1', pdfKey: 'pt2_l37_checkboxes_1', label: 'Part 2, Item 37', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l38a_LastArrivedAs', pdfKey: 'pt2_l38a_lastarrivedas', label: 'Last Arrived As', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l38b_ArrivalDeparture', pdfKey: 'pt2_l38b_arrivaldeparture', label: 'Arrival Departure', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l38c_DateofArrival', pdfKey: 'pt2_l38c_dateofarrival', label: 'Dateof Arrival', type: 'date', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l28c_CityOrTown', pdfKey: 'pt2_l28c_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l28d_Province', pdfKey: 'pt2_l28d_province', label: 'Province', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l28e_PostalCode', pdfKey: 'pt2_l28e_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l28f_Country', pdfKey: 'pt2_l28f_country', label: 'Country', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l38d_DateExpired', pdfKey: 'pt2_l38d_dateexpired', label: 'Date Expired', type: 'date', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l38e_Passport', pdfKey: 'pt2_l38e_passport', label: 'Passport', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l38f_TravelDoc', pdfKey: 'pt2_l38f_traveldoc', label: 'Travel Doc', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l38g_CountryOfIssuance', pdfKey: 'pt2_l38g_countryofissuance', label: 'Country of Issuance', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l38h_ExpDate', pdfKey: 'pt2_l38h_expdate', label: 'Exp Date', type: 'date', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l39_Checkboxes', pdfKey: 'pt2_l39_checkboxes', label: 'Part 2, Item 39', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l39_Checkboxes_1', pdfKey: 'pt2_l39_checkboxes_1', label: 'Part 2, Item 39', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l40a_FamilyName', pdfKey: 'pt2_l40a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l40b_GivenName', pdfKey: 'pt2_l40b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l40c_MiddleName', pdfKey: 'pt2_l40c_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l41_CountryOfBirth', pdfKey: 'pt2_l41_countryofbirth', label: 'Country of Birth', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l42_DateofBirth', pdfKey: 'pt2_l42_dateofbirth', label: 'Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l43_Checkboxes', pdfKey: 'pt2_l43_checkboxes', label: 'Part 2, Item 43', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l43_Checkboxes_1', pdfKey: 'pt2_l43_checkboxes_1', label: 'Part 2, Item 43', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l44_AptSteFlrNumber', pdfKey: 'pt2_l44_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l44_CityOrTown', pdfKey: 'pt2_l44_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l44_Country', pdfKey: 'pt2_l44_country', label: 'Country', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l44_PostalCode', pdfKey: 'pt2_l44_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l44_Province', pdfKey: 'pt2_l44_province', label: 'Province', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l44_State', pdfKey: 'pt2_l44_state', label: 'State', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l44_StreetNumberName', pdfKey: 'pt2_l44_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l44_Unit', pdfKey: 'pt2_l44_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l44_Unit_1', pdfKey: 'pt2_l44_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l44_Unit_2', pdfKey: 'pt2_l44_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l44_ZipCode', pdfKey: 'pt2_l44_zipcode', label: 'Zip Code', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l45a_StreetNumberName', pdfKey: 'pt2_l45a_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l45b_AptSteFlrNumber', pdfKey: 'pt2_l45b_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l45b_Unit', pdfKey: 'pt2_l45b_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l45b_Unit_1', pdfKey: 'pt2_l45b_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l45b_Unit_2', pdfKey: 'pt2_l45b_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l45c_CityOrTown', pdfKey: 'pt2_l45c_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l45d_State', pdfKey: 'pt2_l45d_state', label: 'State', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l45e_ZipCode', pdfKey: 'pt2_l45e_zipcode', label: 'Zip Code', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l46_DayTimeTelephoneNumber', pdfKey: 'pt2_l46_daytimetelephonenumber', label: 'Daytime Telephone Number', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l47_AptSteFlrNumber', pdfKey: 'pt2_l47_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l47_CityOrTown', pdfKey: 'pt2_l47_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l47_Country', pdfKey: 'pt2_l47_country', label: 'Country', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l47_PostalCode', pdfKey: 'pt2_l47_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l47_Province', pdfKey: 'pt2_l47_province', label: 'Province', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l47_StreetNumberName', pdfKey: 'pt2_l47_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l47_Unit', pdfKey: 'pt2_l47_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l47_Unit_1', pdfKey: 'pt2_l47_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l47_Unit_2', pdfKey: 'pt2_l47_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l48_DaytimeTelephoneNum', pdfKey: 'pt2_l48_daytimetelephonenum', label: 'Daytime Telephone Num', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l49a_FamilyName', pdfKey: 'pt2_l49a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l49b_GivenName', pdfKey: 'pt2_l49b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l49c_MiddleName', pdfKey: 'pt2_l49c_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l50_AptSteFlrNumber', pdfKey: 'pt2_l50_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l50_StreetNumberName', pdfKey: 'pt2_l50_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l50_Unit', pdfKey: 'pt2_l50_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l50_Unit_1', pdfKey: 'pt2_l50_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l50_Unit_2', pdfKey: 'pt2_l50_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l51_Checkboxes', pdfKey: 'pt2_l51_checkboxes', label: 'Part 2, Item 51', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l51_Checkboxes_1', pdfKey: 'pt2_l51_checkboxes_1', label: 'Part 2, Item 51', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l51_Checkboxes_2', pdfKey: 'pt2_l51_checkboxes_2', label: 'Part 2, Item 51', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l52_Relationship', pdfKey: 'pt2_l52_relationship', label: 'Relationship', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l53_Checkboxes', pdfKey: 'pt2_l53_checkboxes', label: 'Part 2, Item 53', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l53_Checkboxes_1', pdfKey: 'pt2_l53_checkboxes_1', label: 'Part 2, Item 53', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l53_Checkboxes_2', pdfKey: 'pt2_l53_checkboxes_2', label: 'Part 2, Item 53', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l54_Describe', pdfKey: 'pt2_l54_describe', label: 'Describe', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l55_Checkboxes', pdfKey: 'pt2_l55_checkboxes', label: 'Part 2, Item 55', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l55_Checkboxes_1', pdfKey: 'pt2_l55_checkboxes_1', label: 'Part 2, Item 55', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l56_IMBName', pdfKey: 'pt2_l56_imbname', label: 'Imbname', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l57a_IMBFamilyName', pdfKey: 'pt2_l57a_imbfamilyname', label: 'Imbfamily Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l57b_IMB_GivenName', pdfKey: 'pt2_l57b_imb_givenname', label: 'Imb_Given Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l58_IMBOrgName', pdfKey: 'pt2_l58_imborgname', label: 'Imborg Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l59_IMBWebsite', pdfKey: 'pt2_l59_imbwebsite', label: 'Imbwebsite', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l60_AptSteFlrNumber', pdfKey: 'pt2_l60_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l60_CityOrTown', pdfKey: 'pt2_l60_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l60_Country', pdfKey: 'pt2_l60_country', label: 'Country', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l60_PostalCode', pdfKey: 'pt2_l60_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l60_Province', pdfKey: 'pt2_l60_province', label: 'Province', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l60_Unit', pdfKey: 'pt2_l60_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l60_Unit_1', pdfKey: 'pt2_l60_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l60_Unit_2', pdfKey: 'pt2_l60_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l60a_StreetNumberName', pdfKey: 'pt2_l60a_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l61_DaytimeTelephoneNum', pdfKey: 'pt2_l61_daytimetelephonenum', label: 'Daytime Telephone Num', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l62a_CityTown', pdfKey: 'pt2_l62a_citytown', label: 'City Town', type: 'text', section: 'Part 2: Beneficiary Info' },
  { key: 'pt2_l62b_Country', pdfKey: 'pt2_l62b_country', label: 'Country', type: 'text', section: 'Part 2: Beneficiary Info' },
  // === Part 3: Other Info ===
  { key: 'pt3_l1_Checkboxes', pdfKey: 'pt3_l1_checkboxes', label: 'Part 3, Item 1', type: 'checkbox', section: 'Part 3: Other Info' },
  { key: 'pt3_l1_Checkboxes_1', pdfKey: 'pt3_l1_checkboxes_1', label: 'Part 3, Item 1', type: 'checkbox', section: 'Part 3: Other Info' },
  { key: 'pt3_l2a_Checkboxes', pdfKey: 'pt3_l2a_checkboxes', label: 'Part 3, Item 2a', type: 'checkbox', section: 'Part 3: Other Info' },
  { key: 'pt3_l2a_Checkboxes_1', pdfKey: 'pt3_l2a_checkboxes_1', label: 'Part 3, Item 2a', type: 'checkbox', section: 'Part 3: Other Info' },
  { key: 'pt3_l2b_Checkboxes', pdfKey: 'pt3_l2b_checkboxes', label: 'Part 3, Item 2b', type: 'checkbox', section: 'Part 3: Other Info' },
  { key: 'pt3_l2b_Checkboxes_1', pdfKey: 'pt3_l2b_checkboxes_1', label: 'Part 3, Item 2b', type: 'checkbox', section: 'Part 3: Other Info' },
  { key: 'pt3_l2c_Checkboxes', pdfKey: 'pt3_l2c_checkboxes', label: 'Part 3, Item 2c', type: 'checkbox', section: 'Part 3: Other Info' },
  { key: 'pt3_l2c_Checkboxes_1', pdfKey: 'pt3_l2c_checkboxes_1', label: 'Part 3, Item 2c', type: 'checkbox', section: 'Part 3: Other Info' },
  { key: 'pt3_l3_Checkboxes', pdfKey: 'pt3_l3_checkboxes', label: 'Part 3, Item 3', type: 'checkbox', section: 'Part 3: Other Info' },
  { key: 'pt3_l3_Checkboxes_1', pdfKey: 'pt3_l3_checkboxes_1', label: 'Part 3, Item 3', type: 'checkbox', section: 'Part 3: Other Info' },
  { key: 'pt3_l3_Checkboxes_2', pdfKey: 'pt3_l3_checkboxes_2', label: 'Part 3, Item 3', type: 'checkbox', section: 'Part 3: Other Info' },
  { key: 'pt3_l4a_Checkboxes', pdfKey: 'pt3_l4a_checkboxes', label: 'Part 3, Item 4a', type: 'checkbox', section: 'Part 3: Other Info' },
  { key: 'pt3_l4a_Checkboxes_1', pdfKey: 'pt3_l4a_checkboxes_1', label: 'Part 3, Item 4a', type: 'checkbox', section: 'Part 3: Other Info' },
  { key: 'pt3_l4B_Describe', pdfKey: 'pt3_l4b_describe', label: 'Describe', type: 'text', section: 'Part 3: Other Info' },
  { key: 'pt3_l5_Checkboxes', pdfKey: 'pt3_l5_checkboxes', label: 'Part 3, Item 5', type: 'checkbox', section: 'Part 3: Other Info' },
  { key: 'pt3_l5_Checkboxes_1', pdfKey: 'pt3_l5_checkboxes_1', label: 'Part 3, Item 5', type: 'checkbox', section: 'Part 3: Other Info' },
  { key: 'pt3_l5_Checkboxes_2', pdfKey: 'pt3_l5_checkboxes_2', label: 'Part 3, Item 5', type: 'checkbox', section: 'Part 3: Other Info' },
  { key: 'pt3_l5_Checkboxes_3', pdfKey: 'pt3_l5_checkboxes_3', label: 'Part 3, Item 5', type: 'checkbox', section: 'Part 3: Other Info' },
  { key: 'pt3_l0_AdditionalInfo', pdfKey: 'pt3_l0_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 3: Other Info' },
  { key: 'pt3_l0_ItemNumber', pdfKey: 'pt3_l0_itemnumber', label: 'Item Number', type: 'text', section: 'Part 3: Other Info' },
  { key: 'pt3_l0_PageNumber', pdfKey: 'pt3_l0_pagenumber', label: 'Page Number', type: 'text', section: 'Part 3: Other Info' },
  { key: 'pt3_l0_PartNumber', pdfKey: 'pt3_l0_partnumber', label: 'Part Number', type: 'text', section: 'Part 3: Other Info' },
  // === Part 4: Relationship ===
  { key: 'pt4_l1_Checkbox', pdfKey: 'pt4_l1_checkbox', label: 'Part 4, Item 1', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l1_Checkbox_1', pdfKey: 'pt4_l1_checkbox_1', label: 'Part 4, Item 1', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l2_Checkbox', pdfKey: 'pt4_l2_checkbox', label: 'Part 4, Item 2', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l2_Checkbox_1', pdfKey: 'pt4_l2_checkbox_1', label: 'Part 4, Item 2', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l2_Checkbox_2', pdfKey: 'pt4_l2_checkbox_2', label: 'Part 4, Item 2', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l2_Checkbox_3', pdfKey: 'pt4_l2_checkbox_3', label: 'Part 4, Item 2', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l2_Checkbox_4', pdfKey: 'pt4_l2_checkbox_4', label: 'Part 4, Item 2', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l3_HeightFeet', pdfKey: 'pt4_l3_heightfeet', label: 'Height Feet', type: 'text', section: 'Part 4: Relationship' },
  { key: 'pt4_l3_HeightInches', pdfKey: 'pt4_l3_heightinches', label: 'Height Inches', type: 'text', section: 'Part 4: Relationship' },
  { key: 'pt4_l4_HeightInches1', pdfKey: 'pt4_l4_heightinches1', label: 'Height Inches1', type: 'text', section: 'Part 4: Relationship' },
  { key: 'pt4_l4_HeightInches2', pdfKey: 'pt4_l4_heightinches2', label: 'Height Inches2', type: 'text', section: 'Part 4: Relationship' },
  { key: 'pt4_l4_HeightInches3', pdfKey: 'pt4_l4_heightinches3', label: 'Height Inches3', type: 'text', section: 'Part 4: Relationship' },
  { key: 'pt4_l5_Checkbox', pdfKey: 'pt4_l5_checkbox', label: 'Part 4, Item 5', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l5_Checkbox_1', pdfKey: 'pt4_l5_checkbox_1', label: 'Part 4, Item 5', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l5_Checkbox_2', pdfKey: 'pt4_l5_checkbox_2', label: 'Part 4, Item 5', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l5_Checkbox_3', pdfKey: 'pt4_l5_checkbox_3', label: 'Part 4, Item 5', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l5_Checkbox_4', pdfKey: 'pt4_l5_checkbox_4', label: 'Part 4, Item 5', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l5_Checkbox_5', pdfKey: 'pt4_l5_checkbox_5', label: 'Part 4, Item 5', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l5_Checkbox_6', pdfKey: 'pt4_l5_checkbox_6', label: 'Part 4, Item 5', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l5_Checkbox_7', pdfKey: 'pt4_l5_checkbox_7', label: 'Part 4, Item 5', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l5_Checkbox_8', pdfKey: 'pt4_l5_checkbox_8', label: 'Part 4, Item 5', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l6_HairColor', pdfKey: 'pt4_l6_haircolor', label: 'Hair Color', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l6_HairColor_1', pdfKey: 'pt4_l6_haircolor_1', label: 'Hair Color (Item 2)', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l6_HairColor_2', pdfKey: 'pt4_l6_haircolor_2', label: 'Hair Color (Item 3)', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l6_HairColor_3', pdfKey: 'pt4_l6_haircolor_3', label: 'Hair Color (Item 4)', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l6_HairColor_4', pdfKey: 'pt4_l6_haircolor_4', label: 'Hair Color (Item 5)', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l6_HairColor_5', pdfKey: 'pt4_l6_haircolor_5', label: 'Hair Color (Item 6)', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l6_HairColor_6', pdfKey: 'pt4_l6_haircolor_6', label: 'Hair Color (Item 7)', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l6_HairColor_7', pdfKey: 'pt4_l6_haircolor_7', label: 'Hair Color (Item 8)', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l6_HairColor_8', pdfKey: 'pt4_l6_haircolor_8', label: 'Hair Color (Item 9)', type: 'checkbox', section: 'Part 4: Relationship' },
  { key: 'pt4_l0_AdditionalInfo', pdfKey: 'pt4_l0_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 4: Relationship' },
  { key: 'pt4_l0_ItemNumber', pdfKey: 'pt4_l0_itemnumber', label: 'Item Number', type: 'text', section: 'Part 4: Relationship' },
  { key: 'pt4_l0_PageNumber', pdfKey: 'pt4_l0_pagenumber', label: 'Page Number', type: 'text', section: 'Part 4: Relationship' },
  { key: 'pt4_l0_PartNumber', pdfKey: 'pt4_l0_partnumber', label: 'Part Number', type: 'text', section: 'Part 4: Relationship' },
  // === Part 5: Petitioner Statement ===
  { key: 'pt5_l1_DaytimePhoneNumber1', pdfKey: 'pt5_l1_daytimephonenumber1', label: 'Daytime Phone Number1', type: 'text', section: 'Part 5: Petitioner Statement' },
  { key: 'pt5_l2_MobileNumber1', pdfKey: 'pt5_l2_mobilenumber1', label: 'Mobile Number1', type: 'text', section: 'Part 5: Petitioner Statement' },
  { key: 'pt5_l3_Email', pdfKey: 'pt5_l3_email', label: 'Email', type: 'text', section: 'Part 5: Petitioner Statement' },
  { key: 'pt5_l4_DateOfSignature', pdfKey: 'pt5_l4_dateofsignature', label: 'Date of Signature', type: 'date', section: 'Part 5: Petitioner Statement' },
  { key: 'pt5_l0_AdditionalInfo', pdfKey: 'pt5_l0_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 5: Petitioner Statement' },
  { key: 'pt5_l0_ItemNumber', pdfKey: 'pt5_l0_itemnumber', label: 'Item Number', type: 'text', section: 'Part 5: Petitioner Statement' },
  { key: 'pt5_l0_PageNumber', pdfKey: 'pt5_l0_pagenumber', label: 'Page Number', type: 'text', section: 'Part 5: Petitioner Statement' },
  { key: 'pt5_l0_PartNumber', pdfKey: 'pt5_l0_partnumber', label: 'Part Number', type: 'text', section: 'Part 5: Petitioner Statement' },
  // === Part 6: Interpreter ===
  { key: 'pt6_l0_NameOfLanguage', pdfKey: 'pt6_l0_nameoflanguage', label: 'Name of Language', type: 'text', section: 'Part 6: Interpreter' },
  { key: 'pt6_l1_InterpreterFamilyName', pdfKey: 'pt6_l1_interpreterfamilyname', label: 'Interpreter Family Name', type: 'text', section: 'Part 6: Interpreter' },
  { key: 'pt6_l1_InterpreterGivenName', pdfKey: 'pt6_l1_interpretergivenname', label: 'Interpreter Given Name', type: 'text', section: 'Part 6: Interpreter' },
  { key: 'pt6_l2_NameofBusinessorOrgName', pdfKey: 'pt6_l2_nameofbusinessororgname', label: 'Nameof Businessor org Name', type: 'text', section: 'Part 6: Interpreter' },
  { key: 'pt6_l4_InterpreterDaytimeTelephone', pdfKey: 'pt6_l4_interpreterdaytimetelephone', label: 'Interpreter Daytime Telephone', type: 'text', section: 'Part 6: Interpreter' },
  { key: 'pt6_l4_InterpreterDaytimeTelephone_1', pdfKey: 'pt6_l4_interpreterdaytimetelephone_1', label: 'Interpreter Daytime Telephone (Item 2)', type: 'text', section: 'Part 6: Interpreter' },
  { key: 'pt6_l4_Signature', pdfKey: 'pt6_l4_signature', label: 'Signature', type: 'text', section: 'Part 6: Interpreter' },
  { key: 'pt6_l5_Email', pdfKey: 'pt6_l5_email', label: 'Email', type: 'text', section: 'Part 6: Interpreter' },
  { key: 'pt6_l6_DateofSignature', pdfKey: 'pt6_l6_dateofsignature', label: 'Dateof Signature', type: 'date', section: 'Part 6: Interpreter' },
  { key: 'pt6_l6_Signature', pdfKey: 'pt6_l6_signature', label: 'Signature', type: 'text', section: 'Part 6: Interpreter' },
  { key: 'pt6_l0_AdditionalInfo', pdfKey: 'pt6_l0_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 6: Interpreter' },
  { key: 'pt6_l0_ItemNumber', pdfKey: 'pt6_l0_itemnumber', label: 'Item Number', type: 'text', section: 'Part 6: Interpreter' },
  { key: 'pt6_l0_PageNumber', pdfKey: 'pt6_l0_pagenumber', label: 'Page Number', type: 'text', section: 'Part 6: Interpreter' },
  { key: 'pt6_l0_PartNumber', pdfKey: 'pt6_l0_partnumber', label: 'Part Number', type: 'text', section: 'Part 6: Interpreter' },
  // === Part 7: Preparer ===
  { key: 'pt7_l1_PreparerFamilyName', pdfKey: 'pt7_l1_preparerfamilyname', label: 'Preparer Family Name', type: 'text', section: 'Part 7: Preparer' },
  { key: 'pt7_l1b_PreparerGivenName', pdfKey: 'pt7_l1b_preparergivenname', label: 'Preparer Given Name', type: 'text', section: 'Part 7: Preparer' },
  { key: 'pt7_l2_NameofBusinessorOrgName', pdfKey: 'pt7_l2_nameofbusinessororgname', label: 'Nameof Businessor org Name', type: 'text', section: 'Part 7: Preparer' },
  { key: 'pt7_l3_DaytimePhoneNumber1', pdfKey: 'pt7_l3_daytimephonenumber1', label: 'Daytime Phone Number1', type: 'text', section: 'Part 7: Preparer' },
  { key: 'pt7_l4_PreparerMobileNumber', pdfKey: 'pt7_l4_preparermobilenumber', label: 'Preparer Mobile Number', type: 'text', section: 'Part 7: Preparer' },
  { key: 'pt7_l5_Email', pdfKey: 'pt7_l5_email', label: 'Email', type: 'text', section: 'Part 7: Preparer' },
  { key: 'pt7_l6_DateofSignature', pdfKey: 'pt7_l6_dateofsignature', label: 'Dateof Signature', type: 'date', section: 'Part 7: Preparer' },
  { key: 'pt7_l6_SignatureofPreparer', pdfKey: 'pt7_l6_signatureofpreparer', label: 'Signatureof Preparer', type: 'text', section: 'Part 7: Preparer' },
  { key: 'pt7_l0_AdditionalInfo', pdfKey: 'pt7_l0_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 7: Preparer' },
  { key: 'pt7_l0_ItemNumber', pdfKey: 'pt7_l0_itemnumber', label: 'Item Number', type: 'text', section: 'Part 7: Preparer' },
  { key: 'pt7_l0_PageNumber', pdfKey: 'pt7_l0_pagenumber', label: 'Page Number', type: 'text', section: 'Part 7: Preparer' },
  { key: 'pt7_l0_PartNumber', pdfKey: 'pt7_l0_partnumber', label: 'Part Number', type: 'text', section: 'Part 7: Preparer' },
];

export const getInitialFormData = () => {
  const data: Record<string, string> = {};
  formFields.forEach((f) => { if (f.key) data[f.key] = ''; });
  return data;
};

export const i129fConfig = { formId, formTitle, formSubtitle, formFields, getInitialFormData };
export default i129fConfig;