// Generated 433 fields for I-129F

import type { Field } from './types';

export const formId = 'i129f';
export const formTitle = 'Form I-129F';
export const formSubtitle = 'Petition for Alien Fiance(e)';

export const formFields: Field[] = [
  // === Part 1: Information About You (Petitioner) ===
  { key: 'pt1_l6a_familyname', pdfKey: 'pt1_l6a_familyname', label: 'Your Family Name (Last Name)', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l6b_givenname', pdfKey: 'pt1_l6b_givenname', label: 'Your Given Name (First Name)', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l6c_middlename', pdfKey: 'pt1_l6c_middlename', label: 'Your Middle Name', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l4a_checkboxes', pdfKey: 'pt1_l4a_checkboxes', label: 'U.S. Citizen', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l4a_checkboxes_1', pdfKey: 'pt1_l4a_checkboxes_1', label: 'Lawful Permanent Resident', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l5_checkboxes', pdfKey: 'pt1_l5_checkboxes', label: 'Male', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l5_checkboxes_1', pdfKey: 'pt1_l5_checkboxes_1', label: 'Female', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l1_aliennumber', pdfKey: 'pt1_l1_aliennumber', label: 'Your Alien Registration Number (A-Number), if any', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l2_acctidentifier', pdfKey: 'pt1_l2_acctidentifier', label: 'Your USCIS Online Account Number, if any', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l3_ssn', pdfKey: 'pt1_l3_ssn', label: 'Your U.S. Social Security Number (if any)', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l7b_givenname', pdfKey: 'pt1_l7b_givenname', label: 'Other Given Names You Have Used (if any)', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l7c_middlename', pdfKey: 'pt1_l7c_middlename', label: 'Other Middle Names You Have Used (if any)', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l7a_familyname', pdfKey: 'pt1_l7a_familyname', label: 'Other Family Names You Have Used (if any)', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  // === Part 1: Your Address Information ===
  { key: 'pt1_l8j_checkboxes', pdfKey: 'pt1_l8j_checkboxes', label: 'es', type: 'checkbox', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l8j_checkboxes_1', pdfKey: 'pt1_l8j_checkboxes_1', label: 'es', type: 'checkbox', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l8_streetnumbername', pdfKey: 'pt1_l8_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l8_unit', pdfKey: 'pt1_l8_unit', label: 'Apt.', type: 'checkbox', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l8_unit_1', pdfKey: 'pt1_l8_unit_1', label: 'Ste.', type: 'checkbox', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l8_aptsteflrnumber', pdfKey: 'pt1_l8_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l8_unit_2', pdfKey: 'pt1_l8_unit_2', label: 'Flr.', type: 'checkbox', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l8_cityortown', pdfKey: 'pt1_l8_cityortown', label: 'City or Town', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l8_province', pdfKey: 'pt1_l8_province', label: 'Province', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l8_postalcode', pdfKey: 'pt1_l8_postalcode', label: 'Postal Code', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l8_zipcode', pdfKey: 'pt1_l8_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l8_state', pdfKey: 'pt1_l8_state', label: 'State', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l8_country', pdfKey: 'pt1_l8_country', label: 'Country', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l8_incareofname', pdfKey: 'pt1_l8_incareofname', label: 'In Care Of Name (if any)', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l10b_tofrom', pdfKey: 'pt1_l10b_tofrom', label: 'Date To (or "Present")', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l9_streetnumbername', pdfKey: 'pt1_l9_streetnumbername', label: 'Physical Address - Street Number and Name', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l9_cityortown', pdfKey: 'pt1_l9_cityortown', label: 'Physical Address - City or Town', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l9_province', pdfKey: 'pt1_l9_province', label: 'Physical Address - Province', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l9_postalcode', pdfKey: 'pt1_l9_postalcode', label: 'Physical Address - Postal Code', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l9_zipcode', pdfKey: 'pt1_l9_zipcode', label: 'Physical Address - ZIP Code', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l9_state', pdfKey: 'pt1_l9_state', label: 'Physical Address - State', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l9_country', pdfKey: 'pt1_l9_country', label: 'Physical Address - Country', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l10a_datefrom', pdfKey: 'pt1_l10a_datefrom', label: 'Date From (Physical Address)', type: 'date', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l12b_tofrom', pdfKey: 'pt1_l12b_tofrom', label: 'Date To (Previous Address)', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l11_streetnumbername', pdfKey: 'pt1_l11_streetnumbername', label: 'Previous Address - Street Number and Name', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l11_unit', pdfKey: 'pt1_l11_unit', label: 'Apt.', type: 'checkbox', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l11_unit_1', pdfKey: 'pt1_l11_unit_1', label: 'Ste.', type: 'checkbox', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l11_aptsteflrnumber', pdfKey: 'pt1_l11_aptsteflrnumber', label: 'Previous Address - Apt./Ste./Flr. Number', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l11_unit_2', pdfKey: 'pt1_l11_unit_2', label: 'Flr.', type: 'checkbox', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l11_cityortown', pdfKey: 'pt1_l11_cityortown', label: 'Previous Address - City or Town', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l11_province', pdfKey: 'pt1_l11_province', label: 'Province', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l11_postalcode', pdfKey: 'pt1_l11_postalcode', label: 'Postal Code', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l11_zipcode', pdfKey: 'pt1_l11_zipcode', label: 'Previous Address - ZIP Code', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l11_state', pdfKey: 'pt1_l11_state', label: 'Previous Address - State', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l11_country', pdfKey: 'pt1_l11_country', label: 'Country', type: 'text', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l12a_datefrom', pdfKey: 'pt1_l12a_datefrom', label: 'Date From (Previous Address)', type: 'date', section: 'Part 1: Your Address Information' },
  // === Part 1: Your Employment Information ===
  { key: 'pt1_l13_nameofemployer', pdfKey: 'pt1_l13_nameofemployer', label: 'Name of Your Current Employer (if any)', type: 'text', section: 'Part 1: Your Employment Information' },
  { key: 'pt1_l16b_tofrom', pdfKey: 'pt1_l16b_tofrom', label: 'Date Employment Ended (or "Present")', type: 'text', section: 'Part 1: Your Employment Information' },
  { key: 'pt1_l14_streetnumbername', pdfKey: 'pt1_l14_streetnumbername', label: 'Employer Street Number and Name', type: 'text', section: 'Part 1: Your Employment Information' },
  { key: 'pt1_l14_unit', pdfKey: 'pt1_l14_unit', label: 'Unit', type: 'checkbox', section: 'Part 1: Your Employment Information' },
  { key: 'pt1_l14_unit_1', pdfKey: 'pt1_l14_unit_1', label: 'Unit', type: 'checkbox', section: 'Part 1: Your Employment Information' },
  { key: 'pt1_l14_aptsteflrnumber', pdfKey: 'pt1_l14_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 1: Your Employment Information' },
  { key: 'pt1_l14_unit_2', pdfKey: 'pt1_l14_unit_2', label: 'Unit', type: 'checkbox', section: 'Part 1: Your Employment Information' },
  { key: 'pt1_l14_cityortown', pdfKey: 'pt1_l14_cityortown', label: 'Employer City or Town', type: 'text', section: 'Part 1: Your Employment Information' },
  { key: 'pt1_l14_province', pdfKey: 'pt1_l14_province', label: 'Province', type: 'text', section: 'Part 1: Your Employment Information' },
  { key: 'pt1_l14_postalcode', pdfKey: 'pt1_l14_postalcode', label: 'Postal Code', type: 'text', section: 'Part 1: Your Employment Information' },
  { key: 'pt1_l14_zipcode', pdfKey: 'pt1_l14_zipcode', label: 'Employer ZIP Code', type: 'text', section: 'Part 1: Your Employment Information' },
  { key: 'pt1_l14_state', pdfKey: 'pt1_l14_state', label: 'Employer State', type: 'text', section: 'Part 1: Your Employment Information' },
  { key: 'pt1_l14_country', pdfKey: 'pt1_l14_country', label: 'Country', type: 'text', section: 'Part 1: Your Employment Information' },
  { key: 'pt1_l16a_datefrom', pdfKey: 'pt1_l16a_datefrom', label: 'Date Employment Began', type: 'date', section: 'Part 1: Your Employment Information' },
  { key: 'pt1_l15_occupation', pdfKey: 'pt1_l15_occupation', label: 'Your Occupation', type: 'text', section: 'Part 1: Your Employment Information' },
  // === Part 1: Information About You (Petitioner) ===
  { key: 'pt1_l17_nameofemployer', pdfKey: 'pt1_l17_nameofemployer', label: 'Name of Employer', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l18_streetnumbername', pdfKey: 'pt1_l18_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l18_unit', pdfKey: 'pt1_l18_unit', label: 'Unit', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l18_unit_1', pdfKey: 'pt1_l18_unit_1', label: 'Unit', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l18_aptsteflrnumber', pdfKey: 'pt1_l18_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l18_unit_2', pdfKey: 'pt1_l18_unit_2', label: 'Unit', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l18_cityortown', pdfKey: 'pt1_l18_cityortown', label: 'City or Town', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l18_province', pdfKey: 'pt1_l18_province', label: 'Province', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l18_postalcode', pdfKey: 'pt1_l18_postalcode', label: 'Postal Code', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l18_zipcode', pdfKey: 'pt1_l18_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l18_state', pdfKey: 'pt1_l18_state', label: 'State', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l18_country', pdfKey: 'pt1_l18_country', label: 'Country', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l19_occupation', pdfKey: 'pt1_l19_occupation', label: 'Occupation', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  // === Part 1: Your Address Information ===
  { key: 'pt1_l9_unit', pdfKey: 'pt1_l9_unit', label: 'Unit', type: 'checkbox', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l9_unit_1', pdfKey: 'pt1_l9_unit_1', label: 'Unit', type: 'checkbox', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l9_unit_2', pdfKey: 'pt1_l9_unit_2', label: 'Unit', type: 'checkbox', section: 'Part 1: Your Address Information' },
  { key: 'pt1_l9_aptsteflrnumber', pdfKey: 'pt1_l9_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 1: Your Address Information' },
  // === Part 1: Information About You (Petitioner) ===
  { key: 'pt1_l20b_tofrom', pdfKey: 'pt1_l20b_tofrom', label: 'Date To', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l20a_datefrom', pdfKey: 'pt1_l20a_datefrom', label: 'Date From', type: 'date', section: 'Part 1: Information About You (Petitioner)' },
  // === Part 1: Your Birth Information ===
  { key: 'pt1_l24_citytownofbirth', pdfKey: 'pt1_l24_citytownofbirth', label: 'City/Town of Birth', type: 'text', section: 'Part 1: Your Birth Information' },
  // === Part 1: Your Citizenship Information ===
  { key: 'pt1_l26_countryofcitzornationality', pdfKey: 'pt1_l26_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 1: Your Citizenship Information' },
  // === Part 1: Your Birth Information ===
  { key: 'pt1_l25_provinceorstateofbirth', pdfKey: 'pt1_l25_provinceorstateofbirth', label: 'Provinceorstateofbirth', type: 'text', section: 'Part 1: Your Birth Information' },
  { key: 'pt1_l23_checkbox', pdfKey: 'pt1_l23_checkbox', label: 'Item 23', type: 'checkbox', section: 'Part 1: Your Birth Information' },
  { key: 'pt1_l23_checkbox_1', pdfKey: 'pt1_l23_checkbox_1', label: 'Item 23', type: 'checkbox', section: 'Part 1: Your Birth Information' },
  { key: 'pt1_l23_checkbox_2', pdfKey: 'pt1_l23_checkbox_2', label: 'Item 23', type: 'checkbox', section: 'Part 1: Your Birth Information' },
  { key: 'pt1_l23_checkbox_3', pdfKey: 'pt1_l23_checkbox_3', label: 'Item 23', type: 'checkbox', section: 'Part 1: Your Birth Information' },
  { key: 'pt1_l22_dateofbirth', pdfKey: 'pt1_l22_dateofbirth', label: 'Your Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 1: Your Birth Information' },
  // === Part 1: Information About You (Petitioner) ===
  { key: 'pt1_l21_checkbox', pdfKey: 'pt1_l21_checkbox', label: 'Item 21', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l21_checkbox_1', pdfKey: 'pt1_l21_checkbox_1', label: 'Item 21', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  // === Part 1: Your Citizenship Information ===
  { key: 'pt1_l27a_familyname', pdfKey: 'pt1_l27a_familyname', label: 'Family Name', type: 'text', section: 'Part 1: Your Citizenship Information' },
  { key: 'pt1_l27b_givenname', pdfKey: 'pt1_l27b_givenname', label: 'Given Name', type: 'text', section: 'Part 1: Your Citizenship Information' },
  { key: 'pt1_l27c_middlename', pdfKey: 'pt1_l27c_middlename', label: 'Middle Name', type: 'text', section: 'Part 1: Your Citizenship Information' },
  { key: 'pt1_l28_dateofbirth', pdfKey: 'pt1_l28_dateofbirth', label: 'Date of Birth', type: 'date', section: 'Part 1: Your Citizenship Information' },
  // === Part 1: Information About You (Petitioner) ===
  { key: 'pt1_l29_checkbox', pdfKey: 'pt1_l29_checkbox', label: 'Item 29', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l29_checkbox_1', pdfKey: 'pt1_l29_checkbox_1', label: 'Item 29', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l30_countryofcitzornationality', pdfKey: 'pt1_l30_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l31_countryofcitzornationality', pdfKey: 'pt1_l31_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l31_citytownofbirth', pdfKey: 'pt1_l31_citytownofbirth', label: 'City/Town of Birth', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l32a_familyname', pdfKey: 'pt1_l32a_familyname', label: 'Family Name', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l32b_givenname', pdfKey: 'pt1_l32b_givenname', label: 'Given Name', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l32c_middlename', pdfKey: 'pt1_l32c_middlename', label: 'Middle Name', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l33_dateofbirth', pdfKey: 'pt1_l33_dateofbirth', label: 'Date of Birth', type: 'date', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l34_checkbox', pdfKey: 'pt1_l34_checkbox', label: 'Item 34', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l34_checkbox_1', pdfKey: 'pt1_l34_checkbox_1', label: 'Item 34', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l35_countryofcitzornationality', pdfKey: 'pt1_l35_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l36b_countryofcitzornationality', pdfKey: 'pt1_l36b_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l36a_citytownofbirth', pdfKey: 'pt1_l36a_citytownofbirth', label: 'City/Town of Birth', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l37_checkboxes', pdfKey: 'pt1_l37_checkboxes', label: 'es', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l37_checkboxes_1', pdfKey: 'pt1_l37_checkboxes_1', label: 'es', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l38a_familyname', pdfKey: 'pt1_l38a_familyname', label: 'Family Name', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l38b_givenname', pdfKey: 'pt1_l38b_givenname', label: 'Given Name', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l38c_middlename', pdfKey: 'pt1_l38c_middlename', label: 'Middle Name', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l39_datemarriageended', pdfKey: 'pt1_l39_datemarriageended', label: 'Datemarriageended', type: 'date', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l40_checkbox', pdfKey: 'pt1_l40_checkbox', label: 'Item 40', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l40_checkbox_1', pdfKey: 'pt1_l40_checkbox_1', label: 'Item 40', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l40_checkbox_2', pdfKey: 'pt1_l40_checkbox_2', label: 'Item 40', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l20_checkboxes', pdfKey: 'pt1_l20_checkboxes', label: 'es', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l20_checkboxes_1', pdfKey: 'pt1_l20_checkboxes_1', label: 'es', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l21a_certificatenumber', pdfKey: 'pt1_l21a_certificatenumber', label: 'Certificatenumber', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l21b_placeofissuance', pdfKey: 'pt1_l21b_placeofissuance', label: 'Placeofissuance', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l21c_dateofissuance', pdfKey: 'pt1_l21c_dateofissuance', label: 'Dateofissuance', type: 'date', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l45a_familyname', pdfKey: 'pt1_l45a_familyname', label: 'Family Name', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l45b_givenname', pdfKey: 'pt1_l45b_givenname', label: 'Given Name', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l45c_middlename', pdfKey: 'pt1_l45c_middlename', label: 'Middle Name', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l46_dateoffiling', pdfKey: 'pt1_l46_dateoffiling', label: 'Dateoffiling', type: 'date', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l47_result', pdfKey: 'pt1_l47_result', label: 'Result', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l43_checkboxes', pdfKey: 'pt1_l43_checkboxes', label: 'es', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l43_checkboxes_1', pdfKey: 'pt1_l43_checkboxes_1', label: 'es', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l44_aliennumber', pdfKey: 'pt1_l44_aliennumber', label: 'A-Number', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l48_checkboxes', pdfKey: 'pt1_l48_checkboxes', label: 'es', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l48_checkboxes_1', pdfKey: 'pt1_l48_checkboxes_1', label: 'es', type: 'checkbox', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l49a_age', pdfKey: 'pt1_l49a_age', label: 'Age', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l49b_age', pdfKey: 'pt1_l49b_age', label: 'Age', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l50b_countryofcitzornationality', pdfKey: 'pt1_l50b_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l50a_state', pdfKey: 'pt1_l50a_state', label: 'State', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l51b_countryofcitzornationality', pdfKey: 'pt1_l51b_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l51a_state', pdfKey: 'pt1_l51a_state', label: 'State', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  // === Part 2: Information About Your Fiance(e) ===
  { key: 'pt2_l1a_familyname', pdfKey: 'pt2_l1a_familyname', label: 'Beneficiary\'s Family Name (Last Name)', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l1b_givenname', pdfKey: 'pt2_l1b_givenname', label: 'Beneficiary\'s Given Name (First Name)', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l1c_middlename', pdfKey: 'pt2_l1c_middlename', label: 'Beneficiary\'s Middle Name', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l2_aliennumber', pdfKey: 'pt2_l2_aliennumber', label: 'Beneficiary\'s Alien Registration Number (A-Number), if any', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  // === Part 2: Beneficiary Personal Information ===
  { key: 'pt2_l8_countryofbirth', pdfKey: 'pt2_l8_countryofbirth', label: 'Beneficiary\'s Country of Birth', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l9_countryofcitzornationality', pdfKey: 'pt2_l9_countryofcitzornationality', label: 'Beneficiary\'s Country of Citizenship or Nationality', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l7_citytownofbirth', pdfKey: 'pt2_l7_citytownofbirth', label: 'Beneficiary\'s City/Town of Birth', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l6_checkboxes', pdfKey: 'pt2_l6_checkboxes', label: 'Single', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l6_checkboxes_1', pdfKey: 'pt2_l6_checkboxes_1', label: 'Married', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l6_checkboxes_2', pdfKey: 'pt2_l6_checkboxes_2', label: 'Widowed', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l6_checkboxes_3', pdfKey: 'pt2_l6_checkboxes_3', label: 'Divorced', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  // === Part 2: Information About Your Fiance(e) ===
  { key: 'pt2_l3_ssn', pdfKey: 'pt2_l3_ssn', label: 'Beneficiary\'s U.S. Social Security Number (if any)', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  // === Part 2: Beneficiary Personal Information ===
  { key: 'pt2_l4_dateofbirth', pdfKey: 'pt2_l4_dateofbirth', label: 'Beneficiary\'s Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l5_checkboxes', pdfKey: 'pt2_l5_checkboxes', label: 'Male', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l5_checkboxes_1', pdfKey: 'pt2_l5_checkboxes_1', label: 'Female', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  // === Part 2: Information About Your Fiance(e) ===
  { key: 'pt2_l10a_familyname', pdfKey: 'pt2_l10a_familyname', label: 'Family Name', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l10b_givenname', pdfKey: 'pt2_l10b_givenname', label: 'Given Name', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l10c_middlename', pdfKey: 'pt2_l10c_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  // === Part 2: Beneficiary Address Information ===
  { key: 'pt2_l11_cityortown', pdfKey: 'pt2_l11_cityortown', label: 'Beneficiary\'s City or Town', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l11_incareofname', pdfKey: 'pt2_l11_incareofname', label: 'In Care Of Name (if any)', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l11_streetnumbername', pdfKey: 'pt2_l11_streetnumbername', label: 'Beneficiary\'s Street Number and Name', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l11_unit', pdfKey: 'pt2_l11_unit', label: 'Apt.', type: 'checkbox', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l11_unit_1', pdfKey: 'pt2_l11_unit_1', label: 'Ste.', type: 'checkbox', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l11_aptsteflrnumber', pdfKey: 'pt2_l11_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l11_unit_2', pdfKey: 'pt2_l11_unit_2', label: 'Flr.', type: 'checkbox', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l11_country', pdfKey: 'pt2_l11_country', label: 'Beneficiary\'s Country', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l11_province', pdfKey: 'pt2_l11_province', label: 'Beneficiary\'s Province', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l11_zipcode', pdfKey: 'pt2_l11_zipcode', label: 'Beneficiary\'s ZIP Code', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l11_state', pdfKey: 'pt2_l11_state', label: 'Beneficiary\'s State', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l11_postalcode', pdfKey: 'pt2_l11_postalcode', label: 'Beneficiary\'s Postal Code', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l13b_tofrom', pdfKey: 'pt2_l13b_tofrom', label: 'Date To', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l12_streetnumbername', pdfKey: 'pt2_l12_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l12_unit', pdfKey: 'pt2_l12_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l12_unit_1', pdfKey: 'pt2_l12_unit_1', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l12_aptsteflrnumber', pdfKey: 'pt2_l12_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l12_unit_2', pdfKey: 'pt2_l12_unit_2', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l12_cityortown', pdfKey: 'pt2_l12_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l12_province', pdfKey: 'pt2_l12_province', label: 'Province', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l12_postalcode', pdfKey: 'pt2_l12_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l12_zipcode', pdfKey: 'pt2_l12_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l12_state', pdfKey: 'pt2_l12_state', label: 'State', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l12_country', pdfKey: 'pt2_l12_country', label: 'Country', type: 'text', section: 'Part 2: Beneficiary Address Information' },
  { key: 'pt2_l13a_datefrom', pdfKey: 'pt2_l13a_datefrom', label: 'Date From', type: 'date', section: 'Part 2: Beneficiary Address Information' },
  // === Part 2: Information About Your Fiance(e) ===
  { key: 'pt2_l15b_tofrom', pdfKey: 'pt2_l15b_tofrom', label: 'Date To', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l14_streetnumbername', pdfKey: 'pt2_l14_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l14_unit', pdfKey: 'pt2_l14_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l14_unit_1', pdfKey: 'pt2_l14_unit_1', label: 'Unit', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l14_aptsteflrnumber', pdfKey: 'pt2_l14_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l14_unit_2', pdfKey: 'pt2_l14_unit_2', label: 'Unit', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l14_cityortown', pdfKey: 'pt2_l14_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l14_province', pdfKey: 'pt2_l14_province', label: 'Province', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l14_postalcode', pdfKey: 'pt2_l14_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l14_zipcode', pdfKey: 'pt2_l14_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l14_state', pdfKey: 'pt2_l14_state', label: 'State', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l14_country', pdfKey: 'pt2_l14_country', label: 'Country', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l15a_datefrom', pdfKey: 'pt2_l15a_datefrom', label: 'Date From', type: 'date', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l16_nameofemployer', pdfKey: 'pt2_l16_nameofemployer', label: 'Name of Employer', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l19b_tofrom', pdfKey: 'pt2_l19b_tofrom', label: 'Date To', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l17_streetnumbername', pdfKey: 'pt2_l17_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l17_unit', pdfKey: 'pt2_l17_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l17_unit_1', pdfKey: 'pt2_l17_unit_1', label: 'Unit', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l17_aptsteflrnumber', pdfKey: 'pt2_l17_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l17_unit_2', pdfKey: 'pt2_l17_unit_2', label: 'Unit', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l17_cityortown', pdfKey: 'pt2_l17_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l17_province', pdfKey: 'pt2_l17_province', label: 'Province', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l17_postalcode', pdfKey: 'pt2_l17_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l17_zipcode', pdfKey: 'pt2_l17_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l17_state', pdfKey: 'pt2_l17_state', label: 'State', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l17_country', pdfKey: 'pt2_l17_country', label: 'Country', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l19a_datefrom', pdfKey: 'pt2_l19a_datefrom', label: 'Date From', type: 'date', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l18_occupation', pdfKey: 'pt2_l18_occupation', label: 'Occupation', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l20_nameofemployer', pdfKey: 'pt2_l20_nameofemployer', label: 'Name of Employer', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l23b_tofrom', pdfKey: 'pt2_l23b_tofrom', label: 'Date To', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l21_streetnumbername', pdfKey: 'pt2_l21_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l21_unit', pdfKey: 'pt2_l21_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l21_unit_1', pdfKey: 'pt2_l21_unit_1', label: 'Unit', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l21_aptsteflrnumber', pdfKey: 'pt2_l21_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l21_unit_2', pdfKey: 'pt2_l21_unit_2', label: 'Unit', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l21_cityortown', pdfKey: 'pt2_l21_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l21_province', pdfKey: 'pt2_l21_province', label: 'Province', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l21_postalcode', pdfKey: 'pt2_l21_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l21_zipcode', pdfKey: 'pt2_l21_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l21_state', pdfKey: 'pt2_l21_state', label: 'State', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l21_country', pdfKey: 'pt2_l21_country', label: 'Country', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l23a_datefrom', pdfKey: 'pt2_l23a_datefrom', label: 'Date From', type: 'date', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l22_occupation', pdfKey: 'pt2_l22_occupation', label: 'Occupation', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l24a_familyname', pdfKey: 'pt2_l24a_familyname', label: 'Family Name', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l24b_givenname', pdfKey: 'pt2_l24b_givenname', label: 'Given Name', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l24c_middlename', pdfKey: 'pt2_l24c_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  // === Part 1: Your Address Information ===
  { key: 'pt1_l11_dateofbirth', pdfKey: 'pt1_l11_dateofbirth', label: 'Date of Birth', type: 'date', section: 'Part 1: Your Address Information' },
  // === Part 2: Information About Your Fiance(e) ===
  { key: 'pt2_l26_checkbox', pdfKey: 'pt2_l26_checkbox', label: 'Item 26', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l26_checkbox_1', pdfKey: 'pt2_l26_checkbox_1', label: 'Item 26', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l27_countryofcitzornationality', pdfKey: 'pt2_l27_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l28b_countryofcitzornationality', pdfKey: 'pt2_l28b_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l28a_citytownofbirth', pdfKey: 'pt2_l28a_citytownofbirth', label: 'City/Town of Birth', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l29a_familyname', pdfKey: 'pt2_l29a_familyname', label: 'Family Name', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l29b_givenname', pdfKey: 'pt2_l29b_givenname', label: 'Given Name', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l29c_middlename', pdfKey: 'pt2_l29c_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l30_dateofbirth', pdfKey: 'pt2_l30_dateofbirth', label: 'Date of Birth', type: 'date', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l31_checkbox', pdfKey: 'pt2_l31_checkbox', label: 'Item 31', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l31_checkbox_1', pdfKey: 'pt2_l31_checkbox_1', label: 'Item 31', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l32_countryofcitzornationality', pdfKey: 'pt2_l32_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l33b_countryofcitzornationality', pdfKey: 'pt2_l33b_countryofcitzornationality', label: 'Country of Citizenship or Nationality', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l33a_citytownofbirth', pdfKey: 'pt2_l33a_citytownofbirth', label: 'City/Town of Birth', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l34_checkboxes', pdfKey: 'pt2_l34_checkboxes', label: 'es', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l34_checkboxes_1', pdfKey: 'pt2_l34_checkboxes_1', label: 'es', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l35a_familyname', pdfKey: 'pt2_l35a_familyname', label: 'Family Name', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l35b_givenname', pdfKey: 'pt2_l35b_givenname', label: 'Given Name', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l35c_middlename', pdfKey: 'pt2_l35c_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l36_datemarriageended', pdfKey: 'pt2_l36_datemarriageended', label: 'Datemarriageended', type: 'date', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l37_checkboxes', pdfKey: 'pt2_l37_checkboxes', label: 'es', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l37_checkboxes_1', pdfKey: 'pt2_l37_checkboxes_1', label: 'es', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l38a_lastarrivedas', pdfKey: 'pt2_l38a_lastarrivedas', label: 'Lastarrivedas', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l38b_arrivaldeparture', pdfKey: 'pt2_l38b_arrivaldeparture', label: 'Arrivaldeparture', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l38c_dateofarrival', pdfKey: 'pt2_l38c_dateofarrival', label: 'Dateofarrival', type: 'date', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l38g_countryofissuance', pdfKey: 'pt2_l38g_countryofissuance', label: 'Countryofissuance', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l38h_expdate', pdfKey: 'pt2_l38h_expdate', label: 'Expdate', type: 'date', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l38e_passport', pdfKey: 'pt2_l38e_passport', label: 'Passport', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l38f_traveldoc', pdfKey: 'pt2_l38f_traveldoc', label: 'Traveldoc', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l38d_dateexpired', pdfKey: 'pt2_l38d_dateexpired', label: 'Dateexpired', type: 'date', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l39_checkboxes', pdfKey: 'pt2_l39_checkboxes', label: 'es', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l39_checkboxes_1', pdfKey: 'pt2_l39_checkboxes_1', label: 'es', type: 'checkbox', section: 'Part 2: Information About Your Fiance(e)' },
  // === Part 2: Beneficiary Personal Information ===
  { key: 'pt2_l40a_familyname', pdfKey: 'pt2_l40a_familyname', label: 'Family Name', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l40b_givenname', pdfKey: 'pt2_l40b_givenname', label: 'Given Name', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l40c_middlename', pdfKey: 'pt2_l40c_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l41_countryofbirth', pdfKey: 'pt2_l41_countryofbirth', label: 'Country of Birth', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l42_dateofbirth', pdfKey: 'pt2_l42_dateofbirth', label: 'Date of Birth', type: 'date', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l43_checkboxes', pdfKey: 'pt2_l43_checkboxes', label: 'es', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l43_checkboxes_1', pdfKey: 'pt2_l43_checkboxes_1', label: 'es', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l45e_zipcode', pdfKey: 'pt2_l45e_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l45c_cityortown', pdfKey: 'pt2_l45c_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l45a_streetnumbername', pdfKey: 'pt2_l45a_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l45b_unit', pdfKey: 'pt2_l45b_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l45b_unit_1', pdfKey: 'pt2_l45b_unit_1', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l45b_aptsteflrnumber', pdfKey: 'pt2_l45b_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l45b_unit_2', pdfKey: 'pt2_l45b_unit_2', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l45d_state', pdfKey: 'pt2_l45d_state', label: 'State', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l46_daytimetelephonenumber', pdfKey: 'pt2_l46_daytimetelephonenumber', label: 'Daytimetelephonenumber', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l47_country', pdfKey: 'pt2_l47_country', label: 'Country', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l47_province', pdfKey: 'pt2_l47_province', label: 'Province', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l47_unit', pdfKey: 'pt2_l47_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l47_aptsteflrnumber', pdfKey: 'pt2_l47_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l47_unit_1', pdfKey: 'pt2_l47_unit_1', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l47_unit_2', pdfKey: 'pt2_l47_unit_2', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l47_streetnumbername', pdfKey: 'pt2_l47_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l47_cityortown', pdfKey: 'pt2_l47_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l48_daytimetelephonenum', pdfKey: 'pt2_l48_daytimetelephonenum', label: 'Daytimetelephonenum', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l47_postalcode', pdfKey: 'pt2_l47_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l44_streetnumbername', pdfKey: 'pt2_l44_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l44_unit', pdfKey: 'pt2_l44_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l44_unit_1', pdfKey: 'pt2_l44_unit_1', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l44_aptsteflrnumber', pdfKey: 'pt2_l44_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l44_unit_2', pdfKey: 'pt2_l44_unit_2', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l44_cityortown', pdfKey: 'pt2_l44_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l44_state', pdfKey: 'pt2_l44_state', label: 'State', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l44_province', pdfKey: 'pt2_l44_province', label: 'Province', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l44_zipcode', pdfKey: 'pt2_l44_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l44_country', pdfKey: 'pt2_l44_country', label: 'Country', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l44_postalcode', pdfKey: 'pt2_l44_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l49a_familyname', pdfKey: 'pt2_l49a_familyname', label: 'Family Name', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l49b_givenname', pdfKey: 'pt2_l49b_givenname', label: 'Given Name', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l49c_middlename', pdfKey: 'pt2_l49c_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l50_aptsteflrnumber', pdfKey: 'pt2_l50_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l50_streetnumbername', pdfKey: 'pt2_l50_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  // === Part 2: Information About Your Fiance(e) ===
  { key: 'pt2_l28c_cityortown', pdfKey: 'pt2_l28c_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l28e_postalcode', pdfKey: 'pt2_l28e_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l28f_country', pdfKey: 'pt2_l28f_country', label: 'Country', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  { key: 'pt2_l28d_province', pdfKey: 'pt2_l28d_province', label: 'Province', type: 'text', section: 'Part 2: Information About Your Fiance(e)' },
  // === Part 2: Beneficiary Personal Information ===
  { key: 'pt2_l50_unit', pdfKey: 'pt2_l50_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l50_unit_1', pdfKey: 'pt2_l50_unit_1', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l50_unit_2', pdfKey: 'pt2_l50_unit_2', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l51_checkboxes', pdfKey: 'pt2_l51_checkboxes', label: 'es', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l51_checkboxes_1', pdfKey: 'pt2_l51_checkboxes_1', label: 'es', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l52_relationship', pdfKey: 'pt2_l52_relationship', label: 'Relationship', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l51_checkboxes_2', pdfKey: 'pt2_l51_checkboxes_2', label: 'es', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l53_checkboxes', pdfKey: 'pt2_l53_checkboxes', label: 'es', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l53_checkboxes_1', pdfKey: 'pt2_l53_checkboxes_1', label: 'es', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l53_checkboxes_2', pdfKey: 'pt2_l53_checkboxes_2', label: 'es', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l54_describe', pdfKey: 'pt2_l54_describe', label: 'Describe', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l60a_streetnumbername', pdfKey: 'pt2_l60a_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l60_unit', pdfKey: 'pt2_l60_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l60_unit_1', pdfKey: 'pt2_l60_unit_1', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l60_aptsteflrnumber', pdfKey: 'pt2_l60_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l60_unit_2', pdfKey: 'pt2_l60_unit_2', label: 'Unit', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l60_cityortown', pdfKey: 'pt2_l60_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l60_province', pdfKey: 'pt2_l60_province', label: 'Province', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l60_country', pdfKey: 'pt2_l60_country', label: 'Country', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l60_postalcode', pdfKey: 'pt2_l60_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l58_imborgname', pdfKey: 'pt2_l58_imborgname', label: 'Imborgname', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l59_imbwebsite', pdfKey: 'pt2_l59_imbwebsite', label: 'Imbwebsite', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l61_daytimetelephonenum', pdfKey: 'pt2_l61_daytimetelephonenum', label: 'Daytimetelephonenum', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l62a_citytown', pdfKey: 'pt2_l62a_citytown', label: 'Citytown', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l62b_country', pdfKey: 'pt2_l62b_country', label: 'Country', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l55_checkboxes', pdfKey: 'pt2_l55_checkboxes', label: 'es', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l55_checkboxes_1', pdfKey: 'pt2_l55_checkboxes_1', label: 'es', type: 'checkbox', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l57a_imbfamilyname', pdfKey: 'pt2_l57a_imbfamilyname', label: 'Imbfamilyname', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l57b_IMB_givenname', pdfKey: 'pt2_l57b_IMB_givenname', label: 'Imb Given Name', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  { key: 'pt2_l56_imbname', pdfKey: 'pt2_l56_imbname', label: 'Imbname', type: 'text', section: 'Part 2: Beneficiary Personal Information' },
  // === Part 3: Other Information ===
  { key: 'pt3_l1_checkboxes', pdfKey: 'pt3_l1_checkboxes', label: 'Have you ever filed for this beneficiary or any other beneficiary before?', type: 'checkbox', section: 'Part 3: Other Information' },
  { key: 'pt3_l1_checkboxes_1', pdfKey: 'pt3_l1_checkboxes_1', label: 'es', type: 'checkbox', section: 'Part 3: Other Information' },
  // === Additional Information ===
  { key: 'subform_7_p3line2a_checkboxes', pdfKey: 'subform_7_p3line2a_checkboxes', label: 'Subform 7 P3Line2A Checkboxes', type: 'checkbox', section: 'Additional Information' },
  { key: 'subform_7_p3line2a_checkboxes_1', pdfKey: 'subform_7_p3line2a_checkboxes_1', label: 'Subform 7 P3Line2A Checkboxes 1', type: 'checkbox', section: 'Additional Information' },
  { key: 'subform_8_p3line2b_checkboxes', pdfKey: 'subform_8_p3line2b_checkboxes', label: 'Subform 8 P3Line2B Checkboxes', type: 'checkbox', section: 'Additional Information' },
  { key: 'subform_8_p3line2b_checkboxes_1', pdfKey: 'subform_8_p3line2b_checkboxes_1', label: 'Subform 8 P3Line2B Checkboxes 1', type: 'checkbox', section: 'Additional Information' },
  { key: 'subform_8_p3line2c_checkboxes', pdfKey: 'subform_8_p3line2c_checkboxes', label: 'Subform 8 P3Line2C Checkboxes', type: 'checkbox', section: 'Additional Information' },
  { key: 'subform_8_p3line2c_checkboxes_1', pdfKey: 'subform_8_p3line2c_checkboxes_1', label: 'Subform 8 P3Line2C Checkboxes 1', type: 'checkbox', section: 'Additional Information' },
  // === Part 3: Other Information ===
  { key: 'pt3_l3_checkboxes', pdfKey: 'pt3_l3_checkboxes', label: 'Have you met the beneficiary in person within the 2 years before filing this petition?', type: 'checkbox', section: 'Part 3: Other Information' },
  { key: 'pt3_l3_checkboxes_1', pdfKey: 'pt3_l3_checkboxes_1', label: 'es', type: 'checkbox', section: 'Part 3: Other Information' },
  { key: 'pt3_l3_checkboxes_2', pdfKey: 'pt3_l3_checkboxes_2', label: 'es', type: 'checkbox', section: 'Part 3: Other Information' },
  { key: 'pt3_l5_checkboxes', pdfKey: 'pt3_l5_checkboxes', label: 'es', type: 'checkbox', section: 'Part 3: Other Information' },
  { key: 'pt3_l5_checkboxes_1', pdfKey: 'pt3_l5_checkboxes_1', label: 'es', type: 'checkbox', section: 'Part 3: Other Information' },
  { key: 'pt3_l5_checkboxes_2', pdfKey: 'pt3_l5_checkboxes_2', label: 'es', type: 'checkbox', section: 'Part 3: Other Information' },
  { key: 'pt3_l5_checkboxes_3', pdfKey: 'pt3_l5_checkboxes_3', label: 'es', type: 'checkbox', section: 'Part 3: Other Information' },
  // === Part 4: Information About Your Relationship ===
  { key: 'pt4_l1_checkbox', pdfKey: 'pt4_l1_checkbox', label: 'Item 1', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l1_checkbox_1', pdfKey: 'pt4_l1_checkbox_1', label: 'Item 1', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l2_checkbox', pdfKey: 'pt4_l2_checkbox', label: 'Item 2', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l2_checkbox_1', pdfKey: 'pt4_l2_checkbox_1', label: 'Item 2', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l2_checkbox_2', pdfKey: 'pt4_l2_checkbox_2', label: 'Item 2', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l2_checkbox_3', pdfKey: 'pt4_l2_checkbox_3', label: 'Item 2', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l2_checkbox_4', pdfKey: 'pt4_l2_checkbox_4', label: 'Item 2', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l3_heightfeet', pdfKey: 'pt4_l3_heightfeet', label: 'Heightfeet', type: 'text', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l3_heightinches', pdfKey: 'pt4_l3_heightinches', label: 'Heightinches', type: 'text', section: 'Part 4: Information About Your Relationship' },
  // === Additional Information ===
  { key: 'subform_8_part3line4a_checkboxes', pdfKey: 'subform_8_part3line4a_checkboxes', label: 'Subform 8 Part3Line4A Checkboxes', type: 'checkbox', section: 'Additional Information' },
  { key: 'subform_8_part3line4a_checkboxes_1', pdfKey: 'subform_8_part3line4a_checkboxes_1', label: 'Subform 8 Part3Line4A Checkboxes 1', type: 'checkbox', section: 'Additional Information' },
  // === Part 3: Other Information ===
  { key: 'pt3_l4B_describe', pdfKey: 'pt3_l4B_describe', label: 'Describe', type: 'text', section: 'Part 3: Other Information' },
  // === Part 4: Information About Your Relationship ===
  { key: 'pt4_l4_heightinches1', pdfKey: 'pt4_l4_heightinches1', label: 'Heightinches', type: 'text', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l4_heightinches2', pdfKey: 'pt4_l4_heightinches2', label: 'Heightinches', type: 'text', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l4_heightinches3', pdfKey: 'pt4_l4_heightinches3', label: 'Heightinches', type: 'text', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l5_checkbox', pdfKey: 'pt4_l5_checkbox', label: 'Item 5', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l5_checkbox_1', pdfKey: 'pt4_l5_checkbox_1', label: 'Item 5', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l5_checkbox_2', pdfKey: 'pt4_l5_checkbox_2', label: 'Item 5', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l5_checkbox_3', pdfKey: 'pt4_l5_checkbox_3', label: 'Item 5', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l5_checkbox_4', pdfKey: 'pt4_l5_checkbox_4', label: 'Item 5', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l5_checkbox_5', pdfKey: 'pt4_l5_checkbox_5', label: 'Item 5', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l5_checkbox_6', pdfKey: 'pt4_l5_checkbox_6', label: 'Item 5', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l5_checkbox_7', pdfKey: 'pt4_l5_checkbox_7', label: 'Item 5', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l5_checkbox_8', pdfKey: 'pt4_l5_checkbox_8', label: 'Item 5', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l6_haircolor', pdfKey: 'pt4_l6_haircolor', label: 'Haircolor', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l6_haircolor_1', pdfKey: 'pt4_l6_haircolor_1', label: 'Haircolor', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l6_haircolor_2', pdfKey: 'pt4_l6_haircolor_2', label: 'Haircolor', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l6_haircolor_3', pdfKey: 'pt4_l6_haircolor_3', label: 'Haircolor', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l6_haircolor_4', pdfKey: 'pt4_l6_haircolor_4', label: 'Haircolor', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l6_haircolor_5', pdfKey: 'pt4_l6_haircolor_5', label: 'Haircolor', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l6_haircolor_6', pdfKey: 'pt4_l6_haircolor_6', label: 'Haircolor', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l6_haircolor_7', pdfKey: 'pt4_l6_haircolor_7', label: 'Haircolor', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  { key: 'pt4_l6_haircolor_8', pdfKey: 'pt4_l6_haircolor_8', label: 'Haircolor', type: 'checkbox', section: 'Part 4: Information About Your Relationship' },
  // === Part 5: Your Contact Information ===
  { key: 'pt5_l3_email', pdfKey: 'pt5_l3_email', label: 'Your Email Address (if any)', type: 'text', section: 'Part 5: Your Contact Information' },
  { key: 'pt5_l2_mobilenumber1', pdfKey: 'pt5_l2_mobilenumber1', label: 'Your Mobile Telephone Number (if any)', type: 'text', section: 'Part 5: Your Contact Information' },
  { key: 'pt5_l1_daytimephonenumber1', pdfKey: 'pt5_l1_daytimephonenumber1', label: 'Your Daytime Telephone Number', type: 'text', section: 'Part 5: Your Contact Information' },
  { key: 'pt5_l4_dateofsignature', pdfKey: 'pt5_l4_dateofsignature', label: 'Dateofsignature', type: 'date', section: 'Part 5: Your Contact Information' },
  // === Part 6: Information About Children ===
  { key: 'pt6_l1_interpretergivenname', pdfKey: 'pt6_l1_interpretergivenname', label: 'Interpretergivenname', type: 'text', section: 'Part 6: Information About Children' },
  { key: 'pt6_l1_interpreterfamilyname', pdfKey: 'pt6_l1_interpreterfamilyname', label: 'Interpreterfamilyname', type: 'text', section: 'Part 6: Information About Children' },
  { key: 'pt6_l2_nameofbusinessororgname', pdfKey: 'pt6_l2_nameofbusinessororgname', label: 'Nameofbusinessororgname', type: 'text', section: 'Part 6: Information About Children' },
  { key: 'pt6_l4_signature', pdfKey: 'pt6_l4_signature', label: 'Signature', type: 'text', section: 'Part 6: Information About Children' },
  { key: 'pt6_l4_interpreterdaytimetelephone', pdfKey: 'pt6_l4_interpreterdaytimetelephone', label: 'Interpreterdaytimetelephone', type: 'text', section: 'Part 6: Information About Children' },
  { key: 'pt6_l5_email', pdfKey: 'pt6_l5_email', label: 'Email', type: 'text', section: 'Part 6: Information About Children' },
  { key: 'subform_9_pt6_nameoflanguage', pdfKey: 'subform_9_pt6_nameoflanguage', label: 'Subform 9 Pt6 Nameoflanguage', type: 'text', section: 'Part 6: Information About Children' },
  { key: 'pt6_l4_interpreterdaytimetelephone_1', pdfKey: 'pt6_l4_interpreterdaytimetelephone_1', label: 'Interpreterdaytimetelephone', type: 'text', section: 'Part 6: Information About Children' },
  { key: 'pt6_l6_dateofsignature', pdfKey: 'pt6_l6_dateofsignature', label: 'Dateofsignature', type: 'date', section: 'Part 6: Information About Children' },
  { key: 'pt6_l6_signature', pdfKey: 'pt6_l6_signature', label: 'Signature', type: 'text', section: 'Part 6: Information About Children' },
  // === Part 7: Signature and Certification ===
  { key: 'pt7_l1_preparerfamilyname', pdfKey: 'pt7_l1_preparerfamilyname', label: 'Preparerfamilyname', type: 'text', section: 'Part 7: Signature and Certification' },
  { key: 'pt7_l1b_preparergivenname', pdfKey: 'pt7_l1b_preparergivenname', label: 'Preparergivenname', type: 'text', section: 'Part 7: Signature and Certification' },
  { key: 'pt7_l2_nameofbusinessororgname', pdfKey: 'pt7_l2_nameofbusinessororgname', label: 'Nameofbusinessororgname', type: 'text', section: 'Part 7: Signature and Certification' },
  { key: 'pt7_l3_daytimephonenumber1', pdfKey: 'pt7_l3_daytimephonenumber1', label: 'Daytime Telephone Number', type: 'text', section: 'Part 7: Signature and Certification' },
  { key: 'pt7_l4_preparermobilenumber', pdfKey: 'pt7_l4_preparermobilenumber', label: 'Preparermobilenumber', type: 'text', section: 'Part 7: Signature and Certification' },
  { key: 'pt7_l5_email', pdfKey: 'pt7_l5_email', label: 'Email', type: 'text', section: 'Part 7: Signature and Certification' },
  { key: 'pt7_l6_signatureofpreparer', pdfKey: 'pt7_l6_signatureofpreparer', label: 'Signatureofpreparer', type: 'text', section: 'Part 7: Signature and Certification' },
  { key: 'pt7_l6_dateofsignature', pdfKey: 'pt7_l6_dateofsignature', label: 'Dateofsignature', type: 'date', section: 'Part 7: Signature and Certification' },
  // === Additional Information ===
  { key: 's11_line3d_additionalinfo', pdfKey: 's11_line3d_additionalinfo', label: 'S11 Line3D Additionalinfo', type: 'text', section: 'Additional Information' },
  // === Part 1: Information About You (Petitioner) ===
  { key: 'pt1_l6a_familyname_1', pdfKey: 'pt1_l6a_familyname_1', label: 'Family Name', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l6b_givenname_1', pdfKey: 'pt1_l6b_givenname_1', label: 'Given Name', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  { key: 'pt1_l6c_middlename_1', pdfKey: 'pt1_l6c_middlename_1', label: 'Middle Name', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  // === Additional Information ===
  { key: 's11_line3a_pagenumber', pdfKey: 's11_line3a_pagenumber', label: 'S11 Line3A Pagenumber', type: 'text', section: 'Additional Information' },
  { key: 'subform_11_line3b_partnumber', pdfKey: 'subform_11_line3b_partnumber', label: 'Subform 11 Line3B Partnumber', type: 'text', section: 'Additional Information' },
  { key: 'subform_11_line3c_itemnumber', pdfKey: 'subform_11_line3c_itemnumber', label: 'Subform 11 Line3C Itemnumber', type: 'text', section: 'Additional Information' },
  { key: 's11_line4d_additionalinfo', pdfKey: 's11_line4d_additionalinfo', label: 'S11 Line4D Additionalinfo', type: 'text', section: 'Additional Information' },
  { key: 's11_line4a_pagenumber', pdfKey: 's11_line4a_pagenumber', label: 'S11 Line4A Pagenumber', type: 'text', section: 'Additional Information' },
  { key: 'subform_11_line4b_partnumber', pdfKey: 'subform_11_line4b_partnumber', label: 'Subform 11 Line4B Partnumber', type: 'text', section: 'Additional Information' },
  { key: 'subform_11_line4c_itemnumber', pdfKey: 'subform_11_line4c_itemnumber', label: 'Subform 11 Line4C Itemnumber', type: 'text', section: 'Additional Information' },
  { key: 's11_line5d_additionalinfo', pdfKey: 's11_line5d_additionalinfo', label: 'S11 Line5D Additionalinfo', type: 'text', section: 'Additional Information' },
  { key: 's11_line5a_pagenumber', pdfKey: 's11_line5a_pagenumber', label: 'S11 Line5A Pagenumber', type: 'text', section: 'Additional Information' },
  { key: 'subform_11_line5b_partnumber', pdfKey: 'subform_11_line5b_partnumber', label: 'Subform 11 Line5B Partnumber', type: 'text', section: 'Additional Information' },
  { key: 'subform_11_line5c_itemnumber', pdfKey: 'subform_11_line5c_itemnumber', label: 'Subform 11 Line5C Itemnumber', type: 'text', section: 'Additional Information' },
  { key: 's11_line6d_additionalinfo', pdfKey: 's11_line6d_additionalinfo', label: 'S11 Line6D Additionalinfo', type: 'text', section: 'Additional Information' },
  { key: 's11_line6a_pagenumber', pdfKey: 's11_line6a_pagenumber', label: 'S11 Line6A Pagenumber', type: 'text', section: 'Additional Information' },
  { key: 'subform_11_line6b_partnumber', pdfKey: 'subform_11_line6b_partnumber', label: 'Subform 11 Line6B Partnumber', type: 'text', section: 'Additional Information' },
  { key: 'subform_11_line6c_itemnumber', pdfKey: 'subform_11_line6c_itemnumber', label: 'Subform 11 Line6C Itemnumber', type: 'text', section: 'Additional Information' },
  // === Part 1: Information About You (Petitioner) ===
  { key: 'pt1_l1_aliennumber_1', pdfKey: 'pt1_l1_aliennumber_1', label: 'A-Number', type: 'text', section: 'Part 1: Information About You (Petitioner)' },
  // === Additional Information ===
  { key: 's11_line7d_additionalinfo', pdfKey: 's11_line7d_additionalinfo', label: 'S11 Line7D Additionalinfo', type: 'text', section: 'Additional Information' },
  { key: 's11_line7a_pagenumber', pdfKey: 's11_line7a_pagenumber', label: 'S11 Line7A Pagenumber', type: 'text', section: 'Additional Information' },
  { key: 'subform_11_line7b_partnumber', pdfKey: 'subform_11_line7b_partnumber', label: 'Subform 11 Line7B Partnumber', type: 'text', section: 'Additional Information' },
  { key: 'subform_11_line7c_itemnumber', pdfKey: 'subform_11_line7c_itemnumber', label: 'Subform 11 Line7C Itemnumber', type: 'text', section: 'Additional Information' },
];

export const getInitialFormData = () => {
  const data: Record<string, string> = {};
  formFields.forEach((f) => { if (f.key) data[f.key] = ''; });
  return data;
};

export const i129fConfig = { formId, formTitle, formSubtitle, formFields, getInitialFormData };
export default i129fConfig;
