// Generated fields for Form I-693
import type { Field } from './types';

export const formId = 'i693';
export const formTitle = 'Form I-693';
export const formSubtitle = 'Report of Medical Examination and Vaccination Record';

export const formFields: Field[] = [
  // === Part 1: Applicant Info ===
  { key: 'pt1_l1a_FamilyName', pdfKey: 'pt1_l1a_familyname', label: 'Applicant\'s Family Name (Last Name)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1b_GivenName', pdfKey: 'pt1_l1b_givenname', label: 'Applicant\'s Given Name (First Name)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1c_MiddleName', pdfKey: 'pt1_l1c_middlename', label: 'Applicant\'s Middle Name', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l2_AptSteFlrNumber', pdfKey: 'pt1_l2_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l2_CityOrTown', pdfKey: 'pt1_l2_cityortown', label: 'City or Town', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l2_Country', pdfKey: 'pt1_l2_country', label: 'Country', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l2_PostalCode', pdfKey: 'pt1_l2_postalcode', label: 'Postal Code', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l2_Province', pdfKey: 'pt1_l2_province', label: 'Province', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l2_State', pdfKey: 'pt1_l2_state', label: 'State', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l2_StreetNumberName', pdfKey: 'pt1_l2_streetnumbername', label: 'Address - Street Number and Name', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l2_StreetNumberName_1', pdfKey: 'pt1_l2_streetnumbername_1', label: 'Street Number and Name (Item 2)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l2_Unit', pdfKey: 'pt1_l2_unit', label: 'Unit', type: 'checkbox', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l2_Unit_1', pdfKey: 'pt1_l2_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l2_Unit_2', pdfKey: 'pt1_l2_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l2_ZipCode', pdfKey: 'pt1_l2_zipcode', label: 'Zip Code', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3_CityTownVillageofBirth', pdfKey: 'pt1_l3_citytownvillageofbirth', label: 'City/Town/Village of Birth', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3_CountryofBirth', pdfKey: 'pt1_l3_countryofbirth', label: 'Country of Birth', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3_DateOfBirth', pdfKey: 'pt1_l3_dateofbirth', label: 'Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3_Gender', pdfKey: 'pt1_l3_gender', label: 'Gender: Male', type: 'checkbox', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3_Gender_1', pdfKey: 'pt1_l3_gender_1', label: 'Gender: Female', type: 'checkbox', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3e_AlienNumber', pdfKey: 'pt1_l3e_aliennumber', label: 'Alien Registration Number (A-Number)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3f_USCISOnlineAcctNumber', pdfKey: 'pt1_l3f_uscisonlineacctnumber', label: 'USCIS Online Account Number (if any)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l4_ImmMedExamReq', pdfKey: 'pt1_l4_immmedexamreq', label: 'I am an applicant for status as a permanent resident...', type: 'checkbox', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1a_FamilyName_1', pdfKey: 'pt1_l1a_familyname_1', label: 'Family Name (Last Name) (Item 2)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1b_GivenName_1', pdfKey: 'pt1_l1b_givenname_1', label: 'Given Name (First Name) (Item 2)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1c_MiddleName_1', pdfKey: 'pt1_l1c_middlename_1', label: 'Middle Name (Item 2)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3e_AlienNumber_1', pdfKey: 'pt1_l3e_aliennumber_1', label: 'A-Number (Item 2)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1a_FamilyName_2', pdfKey: 'pt1_l1a_familyname_2', label: 'Family Name (Last Name) (Item 3)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1b_GivenName_2', pdfKey: 'pt1_l1b_givenname_2', label: 'Given Name (First Name) (Item 3)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1c_MiddleName_2', pdfKey: 'pt1_l1c_middlename_2', label: 'Middle Name (Item 3)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3e_AlienNumber_2', pdfKey: 'pt1_l3e_aliennumber_2', label: 'A-Number (Item 3)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1a_FamilyName_3', pdfKey: 'pt1_l1a_familyname_3', label: 'Family Name (Last Name) (Item 4)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1b_GivenName_3', pdfKey: 'pt1_l1b_givenname_3', label: 'Given Name (First Name) (Item 4)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1c_MiddleName_3', pdfKey: 'pt1_l1c_middlename_3', label: 'Middle Name (Item 4)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3e_AlienNumber_3', pdfKey: 'pt1_l3e_aliennumber_3', label: 'A-Number (Item 4)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1a_FamilyName_4', pdfKey: 'pt1_l1a_familyname_4', label: 'Family Name (Last Name) (Item 5)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1b_GivenName_4', pdfKey: 'pt1_l1b_givenname_4', label: 'Given Name (First Name) (Item 5)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1c_MiddleName_4', pdfKey: 'pt1_l1c_middlename_4', label: 'Middle Name (Item 5)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3e_AlienNumber_4', pdfKey: 'pt1_l3e_aliennumber_4', label: 'A-Number (Item 5)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1a_FamilyName_5', pdfKey: 'pt1_l1a_familyname_5', label: 'Family Name (Last Name) (Item 6)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1b_GivenName_5', pdfKey: 'pt1_l1b_givenname_5', label: 'Given Name (First Name) (Item 6)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1c_MiddleName_5', pdfKey: 'pt1_l1c_middlename_5', label: 'Middle Name (Item 6)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3e_AlienNumber_5', pdfKey: 'pt1_l3e_aliennumber_5', label: 'A-Number (Item 6)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1a_FamilyName_6', pdfKey: 'pt1_l1a_familyname_6', label: 'Family Name (Last Name) (Item 7)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1b_GivenName_6', pdfKey: 'pt1_l1b_givenname_6', label: 'Given Name (First Name) (Item 7)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1c_MiddleName_6', pdfKey: 'pt1_l1c_middlename_6', label: 'Middle Name (Item 7)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3e_AlienNumber_6', pdfKey: 'pt1_l3e_aliennumber_6', label: 'A-Number (Item 7)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1a_FamilyName_7', pdfKey: 'pt1_l1a_familyname_7', label: 'Family Name (Last Name) (Item 8)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1b_GivenName_7', pdfKey: 'pt1_l1b_givenname_7', label: 'Given Name (First Name) (Item 8)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1c_MiddleName_7', pdfKey: 'pt1_l1c_middlename_7', label: 'Middle Name (Item 8)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3e_AlienNumber_7', pdfKey: 'pt1_l3e_aliennumber_7', label: 'A-Number (Item 8)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1a_FamilyName_8', pdfKey: 'pt1_l1a_familyname_8', label: 'Family Name (Last Name) (Item 9)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1b_GivenName_8', pdfKey: 'pt1_l1b_givenname_8', label: 'Given Name (First Name) (Item 9)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1c_MiddleName_8', pdfKey: 'pt1_l1c_middlename_8', label: 'Middle Name (Item 9)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3e_AlienNumber_8', pdfKey: 'pt1_l3e_aliennumber_8', label: 'A-Number (Item 9)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1a_FamilyName_9', pdfKey: 'pt1_l1a_familyname_9', label: 'Family Name (Last Name) (Item 10)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1b_GivenName_9', pdfKey: 'pt1_l1b_givenname_9', label: 'Given Name (First Name) (Item 10)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1c_MiddleName_9', pdfKey: 'pt1_l1c_middlename_9', label: 'Middle Name (Item 10)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3e_AlienNumber_9', pdfKey: 'pt1_l3e_aliennumber_9', label: 'A-Number (Item 10)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1a_FamilyName_10', pdfKey: 'pt1_l1a_familyname_10', label: 'Family Name (Last Name) (Item 11)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1b_GivenName_10', pdfKey: 'pt1_l1b_givenname_10', label: 'Given Name (First Name) (Item 11)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1c_MiddleName_10', pdfKey: 'pt1_l1c_middlename_10', label: 'Middle Name (Item 11)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3e_AlienNumber_10', pdfKey: 'pt1_l3e_aliennumber_10', label: 'A-Number (Item 11)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1a_FamilyName_11', pdfKey: 'pt1_l1a_familyname_11', label: 'Family Name (Last Name) (Item 12)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1b_GivenName_11', pdfKey: 'pt1_l1b_givenname_11', label: 'Given Name (First Name) (Item 12)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1c_MiddleName_11', pdfKey: 'pt1_l1c_middlename_11', label: 'Middle Name (Item 12)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3e_AlienNumber_11', pdfKey: 'pt1_l3e_aliennumber_11', label: 'A-Number (Item 12)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1a_FamilyName_12', pdfKey: 'pt1_l1a_familyname_12', label: 'Family Name (Last Name) (Item 13)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1b_GivenName_12', pdfKey: 'pt1_l1b_givenname_12', label: 'Given Name (First Name) (Item 13)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l1c_MiddleName_12', pdfKey: 'pt1_l1c_middlename_12', label: 'Middle Name (Item 13)', type: 'text', section: 'Part 1: Applicant Info' },
  { key: 'pt1_l3e_AlienNumber_12', pdfKey: 'pt1_l3e_aliennumber_12', label: 'A-Number (Item 13)', type: 'text', section: 'Part 1: Applicant Info' },
  // === Part 2: Applicant Statement ===
  { key: 'pt2_l3_DaytimePhone', pdfKey: 'pt2_l3_daytimephone', label: 'Daytime Phone', type: 'text', section: 'Part 2: Applicant Statement' },
  { key: 'pt2_l4_Mobilephone', pdfKey: 'pt2_l4_mobilephone', label: 'Mobilephone', type: 'text', section: 'Part 2: Applicant Statement' },
  { key: 'pt2_l5_EmailAddress', pdfKey: 'pt2_l5_emailaddress', label: 'Email Address', type: 'text', section: 'Part 2: Applicant Statement' },
  { key: 'pt2_l6_ApplicantSignature', pdfKey: 'pt2_l6_applicantsignature', label: 'Applicant Signature', type: 'text', section: 'Part 2: Applicant Statement' },
  { key: 'pt2_l6_DateofSignature', pdfKey: 'pt2_l6_dateofsignature', label: 'Dateof Signature', type: 'date', section: 'Part 2: Applicant Statement' },
  // === Part 3: Interpreter ===
  { key: 'pt3_l1_InterpreterFamilyName', pdfKey: 'pt3_l1_interpreterfamilyname', label: 'Interpreter Family Name', type: 'text', section: 'Part 3: Interpreter' },
  { key: 'pt3_l1_InterpreterGivenName', pdfKey: 'pt3_l1_interpretergivenname', label: 'Interpreter Given Name', type: 'text', section: 'Part 3: Interpreter' },
  { key: 'pt3_l2_NameofBusinessorOrgName', pdfKey: 'pt3_l2_nameofbusinessororgname', label: 'Nameof Businessor org Name', type: 'text', section: 'Part 3: Interpreter' },
  { key: 'pt3_l4_DaytimePhone', pdfKey: 'pt3_l4_daytimephone', label: 'Daytime Phone', type: 'text', section: 'Part 3: Interpreter' },
  { key: 'pt3_l5_MobilePhone', pdfKey: 'pt3_l5_mobilephone', label: 'Mobile Phone', type: 'text', section: 'Part 3: Interpreter' },
  { key: 'pt3_l6_EmailAddress', pdfKey: 'pt3_l6_emailaddress', label: 'Email Address', type: 'text', section: 'Part 3: Interpreter' },
  { key: 'pt3_l0_NameOfLanguage', pdfKey: 'pt3_l0_nameoflanguage', label: 'Name of Language', type: 'text', section: 'Part 3: Interpreter' },
  { key: 'pt3_l7_DateofSignature', pdfKey: 'pt3_l7_dateofsignature', label: 'Dateof Signature', type: 'date', section: 'Part 3: Interpreter' },
  { key: 'pt3_l7_Signature', pdfKey: 'pt3_l7_signature', label: 'Signature', type: 'text', section: 'Part 3: Interpreter' },
  // === Part 4: Preparer ===
  { key: 'pt4_l1_PreparerFamilyName', pdfKey: 'pt4_l1_preparerfamilyname', label: 'Preparer Family Name', type: 'text', section: 'Part 4: Preparer' },
  { key: 'pt4_l1_PreparerGivenName', pdfKey: 'pt4_l1_preparergivenname', label: 'Preparer Given Name', type: 'text', section: 'Part 4: Preparer' },
  { key: 'pt4_l2_PreparerNameofBusinessorOrgName', pdfKey: 'pt4_l2_preparernameofbusinessororgname', label: 'Preparer Nameof Businessor org Name', type: 'text', section: 'Part 4: Preparer' },
  { key: 'pt4_l3_DaytimePhone', pdfKey: 'pt4_l3_daytimephone', label: 'Daytime Phone', type: 'text', section: 'Part 4: Preparer' },
  { key: 'pt4_l4_MobilePhone', pdfKey: 'pt4_l4_mobilephone', label: 'Mobile Phone', type: 'text', section: 'Part 4: Preparer' },
  { key: 'pt4_l5_EmailAddress', pdfKey: 'pt4_l5_emailaddress', label: 'Email Address', type: 'text', section: 'Part 4: Preparer' },
  { key: 'pt4_l8_DateofSignature', pdfKey: 'pt4_l8_dateofsignature', label: 'Dateof Signature', type: 'date', section: 'Part 4: Preparer' },
  { key: 'pt4_l8_Signature', pdfKey: 'pt4_l8_signature', label: 'Signature', type: 'text', section: 'Part 4: Preparer' },
  // === Part 5: Identification ===
  { key: 'pt5_l1_ApplicantFormOfID', pdfKey: 'pt5_l1_applicantformofid', label: 'Applicant Form of Id', type: 'text', section: 'Part 5: Identification' },
  { key: 'pt5_l2_IDNumber', pdfKey: 'pt5_l2_idnumber', label: 'Idnumber', type: 'text', section: 'Part 5: Identification' },
  // === Part 6: Medical Summary ===
  { key: 'pt6_l1_OverallFinding', pdfKey: 'pt6_l1_overallfinding', label: 'A. No Class A or Class B Condition', type: 'checkbox', section: 'Part 6: Medical Summary' },
  { key: 'pt6_l1_OverallFinding_1', pdfKey: 'pt6_l1_overallfinding_1', label: 'B. Class B Conditions (See Part 8)', type: 'checkbox', section: 'Part 6: Medical Summary' },
  { key: 'pt6_l1_OverallFinding_2', pdfKey: 'pt6_l1_overallfinding_2', label: 'C. Class A Conditions (See Part 8)', type: 'checkbox', section: 'Part 6: Medical Summary' },
  { key: 'pt6_l2_DateoExam', pdfKey: 'pt6_l2_dateoexam', label: 'Date of First Examination (mm/dd/yyyy)', type: 'date', section: 'Part 6: Medical Summary' },
  { key: 'pt6_l3_DateofExam1', pdfKey: 'pt6_l3_dateofexam1', label: 'Follow-up Exam Date 1 (mm/dd/yyyy)', type: 'date', section: 'Part 6: Medical Summary' },
  { key: 'pt6_l3_DateofExam2', pdfKey: 'pt6_l3_dateofexam2', label: 'Follow-up Exam Date 2 (mm/dd/yyyy)', type: 'date', section: 'Part 6: Medical Summary' },
  { key: 'pt6_l3_DateofExam3', pdfKey: 'pt6_l3_dateofexam3', label: 'Follow-up Exam Date 3 (mm/dd/yyyy)', type: 'date', section: 'Part 6: Medical Summary' },
  // === Part 7: Civil Surgeon Info ===
  { key: 'pt7_l1_CivilSurgeonID', pdfKey: 'pt7_l1_civilsurgeonid', label: 'Civil Surgeon Identification Number (CSID)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1_FamilyName', pdfKey: 'pt7_l1_familyname', label: 'Civil Surgeon\'s Family Name (Last Name)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1_GivenName', pdfKey: 'pt7_l1_givenname', label: 'Civil Surgeon\'s Given Name (First Name)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1_MiddleName', pdfKey: 'pt7_l1_middlename', label: 'Civil Surgeon\'s Middle Name (if applicable)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l2_MedPracticeName', pdfKey: 'pt7_l2_medpracticename', label: 'Name of Medical Practice, Facility, or Health Department', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l3_AptSteFlrNumber', pdfKey: 'pt7_l3_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l3_CityOrTown', pdfKey: 'pt7_l3_cityortown', label: 'City or Town', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l3_State', pdfKey: 'pt7_l3_state', label: 'State', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l3_StreetNumberName', pdfKey: 'pt7_l3_streetnumbername', label: 'Physical Address - Street Number and Name', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l3_Unit', pdfKey: 'pt7_l3_unit', label: 'Unit', type: 'checkbox', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l3_Unit_1', pdfKey: 'pt7_l3_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l3_Unit_2', pdfKey: 'pt7_l3_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l3_ZipCode', pdfKey: 'pt7_l3_zipcode', label: 'Zip Code', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l4_AptSteFlrNumber', pdfKey: 'pt7_l4_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l4_CityOrTown', pdfKey: 'pt7_l4_cityortown', label: 'City or Town', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l4_State', pdfKey: 'pt7_l4_state', label: 'State', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l4_StreetNumberName', pdfKey: 'pt7_l4_streetnumbername', label: 'Mailing Address - Street Number and Name (PO Box)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l4_Unit', pdfKey: 'pt7_l4_unit', label: 'Unit', type: 'checkbox', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l4_Unit_1', pdfKey: 'pt7_l4_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l4_Unit_2', pdfKey: 'pt7_l4_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l4_ZipCode', pdfKey: 'pt7_l4_zipcode', label: 'Zip Code', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l5_DaytimePhone', pdfKey: 'pt7_l5_daytimephone', label: 'Daytime Telephone Number', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l6_MobilePhone', pdfKey: 'pt7_l6_mobilephone', label: 'Mobile Telephone Number (if any)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l7_EmailAddress', pdfKey: 'pt7_l7_emailaddress', label: 'Email Address (if any)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l7_CivilSurgeonSignature', pdfKey: 'pt7_l7_civilsurgeonsignature', label: 'Civil Surgeon\'s Signature', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l8_DateofSignature', pdfKey: 'pt7_l8_dateofsignature', label: 'Date of Signature (mm/dd/yyyy)', type: 'date', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1b_DateScreeningRun', pdfKey: 'pt7_l1b1b_datescreeningrun', label: 'Date Screening Run', type: 'date', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1b_DateScreeningRun_1', pdfKey: 'pt7_l1b1b_datescreeningrun_1', label: 'Date Screening Run (Item 2)', type: 'date', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1b_DateScreeningRun_10', pdfKey: 'pt7_l1b1b_datescreeningrun_10', label: 'Date Screening Run (Item 11)', type: 'date', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1b_DateScreeningRun_11', pdfKey: 'pt7_l1b1b_datescreeningrun_11', label: 'Date Screening Run (Item 12)', type: 'date', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1b_DateScreeningRun_2', pdfKey: 'pt7_l1b1b_datescreeningrun_2', label: 'Date Screening Run (Item 3)', type: 'date', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1b_DateScreeningRun_3', pdfKey: 'pt7_l1b1b_datescreeningrun_3', label: 'Date Screening Run (Item 4)', type: 'date', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1b_DateScreeningRun_4', pdfKey: 'pt7_l1b1b_datescreeningrun_4', label: 'Date Screening Run (Item 5)', type: 'date', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1b_DateScreeningRun_5', pdfKey: 'pt7_l1b1b_datescreeningrun_5', label: 'Date Screening Run (Item 6)', type: 'date', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1b_DateScreeningRun_6', pdfKey: 'pt7_l1b1b_datescreeningrun_6', label: 'Date Screening Run (Item 7)', type: 'date', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1b_DateScreeningRun_7', pdfKey: 'pt7_l1b1b_datescreeningrun_7', label: 'Date Screening Run (Item 8)', type: 'date', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1b_DateScreeningRun_8', pdfKey: 'pt7_l1b1b_datescreeningrun_8', label: 'Date Screening Run (Item 9)', type: 'date', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1b_DateScreeningRun_9', pdfKey: 'pt7_l1b1b_datescreeningrun_9', label: 'Date Screening Run (Item 10)', type: 'date', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1c_TiterOne', pdfKey: 'pt7_l1b1c_titerone', label: 'Titer One', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name', pdfKey: 'pt7_l1b1d_name', label: 'Name', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name_1', pdfKey: 'pt7_l1b1d_name_1', label: 'Name (Item 2)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name_10', pdfKey: 'pt7_l1b1d_name_10', label: 'Name (Item 11)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name_11', pdfKey: 'pt7_l1b1d_name_11', label: 'Name (Item 12)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name_12', pdfKey: 'pt7_l1b1d_name_12', label: 'Name (Item 13)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name_13', pdfKey: 'pt7_l1b1d_name_13', label: 'Name (Item 14)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name_14', pdfKey: 'pt7_l1b1d_name_14', label: 'Name (Item 15)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name_15', pdfKey: 'pt7_l1b1d_name_15', label: 'Name (Item 16)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name_16', pdfKey: 'pt7_l1b1d_name_16', label: 'Name (Item 17)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name_17', pdfKey: 'pt7_l1b1d_name_17', label: 'Name (Item 18)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name_2', pdfKey: 'pt7_l1b1d_name_2', label: 'Name (Item 3)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name_3', pdfKey: 'pt7_l1b1d_name_3', label: 'Name (Item 4)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name_4', pdfKey: 'pt7_l1b1d_name_4', label: 'Name (Item 5)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name_5', pdfKey: 'pt7_l1b1d_name_5', label: 'Name (Item 6)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name_6', pdfKey: 'pt7_l1b1d_name_6', label: 'Name (Item 7)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name_7', pdfKey: 'pt7_l1b1d_name_7', label: 'Name (Item 8)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name_8', pdfKey: 'pt7_l1b1d_name_8', label: 'Name (Item 9)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1d_name_9', pdfKey: 'pt7_l1b1d_name_9', label: 'Name (Item 10)', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1B1h_DateOfrepeatTest', pdfKey: 'pt7_l1b1h_dateofrepeattest', label: 'Date ofrepeat Test', type: 'date', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1C1b_DateScreeningNucleicAcid', pdfKey: 'pt7_l1c1b_datescreeningnucleicacid', label: 'Date Screening Nucleic Acid', type: 'date', section: 'Part 7: Civil Surgeon Info' },
  { key: 'pt7_l1_CompleteSeries', pdfKey: 'pt7_l1_completeseries', label: 'Complete Series', type: 'text', section: 'Part 7: Civil Surgeon Info' },
  // === Part 8: Diseases ===
  { key: 'pt8_l1A1_QFDate', pdfKey: 'pt8_l1a1_qfdate', label: 'Date Blood Sample Drawn (QuantiFERON)', type: 'date', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A1_Result', pdfKey: 'pt8_l1a1_result', label: 'Result: Negative', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A1_Result_1', pdfKey: 'pt8_l1a1_result_1', label: 'Result: Positive', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A1_Result_2', pdfKey: 'pt8_l1a1_result_2', label: 'Result: Indeterminate', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A1_TSDate', pdfKey: 'pt8_l1a1_tsdate', label: 'Date Blood Sample Drawn (T-Spot)', type: 'date', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A2_InitialScreening', pdfKey: 'pt8_l1a2_initialscreening', label: '1.A. (2) Chest X-ray not required', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A2_InitialScreening_1', pdfKey: 'pt8_l1a2_initialscreening_1', label: '1.A. (2) Chest X-ray required due to initial screening result', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A2_InitialScreening_2', pdfKey: 'pt8_l1a2_initialscreening_2', label: '1.A. (2) Chest X-ray required due to TB signs or symptoms', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A2_InitialScreening_3', pdfKey: 'pt8_l1a2_initialscreening_3', label: '1.A. (2) Chest X-ray required due to IGRA exception', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A3_Cavitylesion', pdfKey: 'pt8_l1a3_cavitylesion', label: 'Abnormal: Cavitary lesion', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A3_DiscretelinearOpac', pdfKey: 'pt8_l1a3_discretelinearopac', label: 'Abnormal: Discrete linear opacity', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A3_DiscreteNodule', pdfKey: 'pt8_l1a3_discretenodule', label: 'Abnormal: Discrete nodule(s) without calcification', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A3_Hilar', pdfKey: 'pt8_l1a3_hilar', label: 'Abnormal: Hilar/mediastinal adenopathy', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A3_Infiltrate', pdfKey: 'pt8_l1a3_infiltrate', label: 'Abnormal: Infiltrate or consolidation', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A3_Irregularthickpleural', pdfKey: 'pt8_l1a3_irregularthickpleural', label: 'Abnormal: Irregular thick pleural reaction', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A3_Miliary', pdfKey: 'pt8_l1a3_miliary', label: 'Abnormal: Miliary findings', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A3_NodulesorMass', pdfKey: 'pt8_l1a3_nodulesormass', label: 'Abnormal: Nodule(s) or mass with poorly defined margins', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A3_Other', pdfKey: 'pt8_l1a3_other', label: 'Abnormal: Other', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A3_Pleuraleffusion', pdfKey: 'pt8_l1a3_pleuraleffusion', label: 'Abnormal: Pleural effusion', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A3_Results', pdfKey: 'pt8_l1a3_results', label: 'Result: Normal', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A3_Results_1', pdfKey: 'pt8_l1a3_results_1', label: 'Result: Abnormal findings suggestive of TB', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A3_Reticular', pdfKey: 'pt8_l1a3_reticular', label: 'Abnormal: Reticular markings suggestive of fibrosis', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A3_Volumeloss', pdfKey: 'pt8_l1a3_volumeloss', label: 'Abnormal: Volume loss or retraction', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A3_XrayReadDate', pdfKey: 'pt8_l1a3_xrayreaddate', label: 'Date Chest X-Ray Read (mm/dd/yyyy)', type: 'date', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A3_XrayTakenDate', pdfKey: 'pt8_l1a3_xraytakendate', label: 'Date Chest X-Ray Taken (mm/dd/yyyy)', type: 'date', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A_GammarRelease', pdfKey: 'pt8_l1a_gammarrelease', label: '1.A. (1) Not Administered (IGRA exception)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A_GammarRelease_1', pdfKey: 'pt8_l1a_gammarrelease_1', label: '1.A. (1) QuantiFERON', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A_GammarRelease_2', pdfKey: 'pt8_l1a_gammarrelease_2', label: '1.A. (1) T-Spot', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A4_SputumSmearsCultures', pdfKey: 'pt8_l1a4_sputumsmearscultures', label: 'Sputum Smears Cultures', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A4_SputumSmearsCultures_1', pdfKey: 'pt8_l1a4_sputumsmearscultures_1', label: 'Sputum Smears Cultures (Item 2)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A4_SputumSmearsCultures_2', pdfKey: 'pt8_l1a4_sputumsmearscultures_2', label: 'Sputum Smears Cultures (Item 3)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A4_SputumSmearsCultures_3', pdfKey: 'pt8_l1a4_sputumsmearscultures_3', label: 'Sputum Smears Cultures (Item 4)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A4_SputumSmearsCultures_4', pdfKey: 'pt8_l1a4_sputumsmearscultures_4', label: 'Sputum Smears Cultures (Item 5)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A6_TBClassification', pdfKey: 'pt8_l1a6_tbclassification', label: 'No Class A or Class B TB', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A6_TBClassification_1', pdfKey: 'pt8_l1a6_tbclassification_1', label: 'Class A Pulmonary TB Disease', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A6_TBClassification_2', pdfKey: 'pt8_l1a6_tbclassification_2', label: 'Class B0 Pulmonary TB', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A6_TBClassification_3', pdfKey: 'pt8_l1a6_tbclassification_3', label: 'Class B1 Pulmonary TB', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A6_TBClassification_4', pdfKey: 'pt8_l1a6_tbclassification_4', label: 'Class B1 Extrapulmonary TB', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A6_TBClassification_5', pdfKey: 'pt8_l1a6_tbclassification_5', label: 'Class B2 TB, Latent TB Infection', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A6_TBClassification_6', pdfKey: 'pt8_l1a6_tbclassification_6', label: 'Class B, Other Chest Condition (non-TB)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1A7_Remarks', pdfKey: 'pt8_l1a7_remarks', label: 'Remarks regarding TB findings', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B1a_name', pdfKey: 'pt8_l1b1a_name', label: 'Name', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B1b_DateNontrepoemaltest', pdfKey: 'pt8_l1b1b_datenontrepoemaltest', label: 'Date Nontrepoemaltest', type: 'date', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B1c_DateNontreponemalTest', pdfKey: 'pt8_l1b1c_datenontreponemaltest', label: 'Date Nontreponemal Test', type: 'date', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B1c_SyphilisScreen', pdfKey: 'pt8_l1b1c_syphilisscreen', label: 'B. (1) (c) Nontreponemal Test Nonreactive', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B1c_SyphilisScreen_1', pdfKey: 'pt8_l1b1c_syphilisscreen_1', label: 'B. (1) (c) Screening Reactive', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B1d_name', pdfKey: 'pt8_l1b1d_name', label: 'Name', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B1d_TreponemalReactiveNon', pdfKey: 'pt8_l1b1d_treponemalreactivenon', label: 'Treponemal Reactive Non', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B1d_TreponemalReactiveNon_1', pdfKey: 'pt8_l1b1d_treponemalreactivenon_1', label: 'Treponemal Reactive Non (Item 2)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B1e_DateScreeningRun', pdfKey: 'pt8_l1b1e_datescreeningrun', label: 'Date Screening Run', type: 'date', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B1f_TiterOne', pdfKey: 'pt8_l1b1f_titerone', label: 'Titer One', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B1g_nameOfrepeat', pdfKey: 'pt8_l1b1g_nameofrepeat', label: 'Name ofrepeat', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B1i_RepeatReativeNon', pdfKey: 'pt8_l1b1i_repeatreativenon', label: 'Repeat Reative Non', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B1i_RepeatReativeNon_1', pdfKey: 'pt8_l1b1i_repeatreativenon_1', label: 'Repeat Reative Non (Item 2)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B2_Findings', pdfKey: 'pt8_l1b2_findings', label: 'Findings', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B2_Findings_1', pdfKey: 'pt8_l1b2_findings_1', label: 'Findings (Item 2)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B2_Findings_2', pdfKey: 'pt8_l1b2_findings_2', label: 'Findings (Item 3)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B3_Dosage', pdfKey: 'pt8_l1b3_dosage', label: 'Dosage', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B3_Drug', pdfKey: 'pt8_l1b3_drug', label: 'Drug', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B3_endDate', pdfKey: 'pt8_l1b3_enddate', label: 'End Date', type: 'date', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B3_Remarks', pdfKey: 'pt8_l1b3_remarks', label: 'Remarks', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l1B3_startDate', pdfKey: 'pt8_l1b3_startdate', label: 'Start Date', type: 'date', section: 'Part 8: Diseases' },
  { key: 'pt8_l1C1a_name', pdfKey: 'pt8_l1c1a_name', label: 'Name', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l1c2_Findings', pdfKey: 'pt8_l1c2_findings', label: 'Findings', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1c2_Findings_1', pdfKey: 'pt8_l1c2_findings_1', label: 'Findings (Item 2)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1c2_Findings_2', pdfKey: 'pt8_l1c2_findings_2', label: 'Findings (Item 3)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1C3_Dosage', pdfKey: 'pt8_l1c3_dosage', label: 'Dosage', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l1C3_Drug', pdfKey: 'pt8_l1c3_drug', label: 'Drug', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l1C3_endDate', pdfKey: 'pt8_l1c3_enddate', label: 'End Date', type: 'date', section: 'Part 8: Diseases' },
  { key: 'pt8_l1c3_Remarks', pdfKey: 'pt8_l1c3_remarks', label: 'Remarks', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l1C3_startDate', pdfKey: 'pt8_l1c3_startdate', label: 'Start Date', type: 'date', section: 'Part 8: Diseases' },
  { key: 'Pt8Line1C1c_0', pdfKey: 'pt8line1c1c_0', label: 'Line1C1C_0', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'Pt8Line1C1c_1', pdfKey: 'pt8line1c1c_1', label: 'Line1C1C_1', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1C1c_Checkboxg', pdfKey: 'pt8_l1c1c_checkboxg', label: 'Checkboxg', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1C1c_Checkboxg_1', pdfKey: 'pt8_l1c1c_checkboxg_1', label: 'Checkboxg (Item 2)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1C2_Remarks', pdfKey: 'pt8_l1c2_remarks', label: 'Remarks', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l1D1_Findings', pdfKey: 'pt8_l1d1_findings', label: 'Findings', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1D1_Findings_1', pdfKey: 'pt8_l1d1_findings_1', label: 'Findings (Item 2)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1D1_Findings_2', pdfKey: 'pt8_l1d1_findings_2', label: 'Findings (Item 3)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1D1b_Checkboxf', pdfKey: 'pt8_l1d1b_checkboxf', label: 'Checkboxf', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l1D1b_Checkboxf_1', pdfKey: 'pt8_l1d1b_checkboxf_1', label: 'Checkboxf (Item 2)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l2A_Disorders', pdfKey: 'pt8_l2a_disorders', label: 'Disorders', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l2A_Disorders_1', pdfKey: 'pt8_l2a_disorders_1', label: 'Disorders (Item 2)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l2A_Disorders_2', pdfKey: 'pt8_l2a_disorders_2', label: 'Disorders (Item 3)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l2A_Disorders_3', pdfKey: 'pt8_l2a_disorders_3', label: 'Disorders (Item 4)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l2A_Disorders_4', pdfKey: 'pt8_l2a_disorders_4', label: 'Disorders (Item 5)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l2B_Remarks', pdfKey: 'pt8_l2b_remarks', label: 'Remarks', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l3A_Findings', pdfKey: 'pt8_l3a_findings', label: 'Findings', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l3A_Findings_1', pdfKey: 'pt8_l3a_findings_1', label: 'Findings (Item 2)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l3A_Findings_2', pdfKey: 'pt8_l3a_findings_2', label: 'Findings (Item 3)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l3A_Findings_3', pdfKey: 'pt8_l3a_findings_3', label: 'Findings (Item 4)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l3B_Remarks', pdfKey: 'pt8_l3b_remarks', label: 'Remarks', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l4_ListOtherMedConditions', pdfKey: 'pt8_l4_listothermedconditions', label: 'List Other Med Conditions', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l5A_DoctorOrHDptName', pdfKey: 'pt8_l5a_doctororhdptname', label: 'Doctor or Hdpt Name', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l5B_AptSteFlrNumber', pdfKey: 'pt8_l5b_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l5B_CityOrTown', pdfKey: 'pt8_l5b_cityortown', label: 'City or Town', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l5B_State', pdfKey: 'pt8_l5b_state', label: 'State', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l5B_StreetNumberName', pdfKey: 'pt8_l5b_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l5B_Unit', pdfKey: 'pt8_l5b_unit', label: 'Unit', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l5B_Unit_1', pdfKey: 'pt8_l5b_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l5B_Unit_2', pdfKey: 'pt8_l5b_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 8: Diseases' },
  { key: 'pt8_l5B_ZipCode', pdfKey: 'pt8_l5b_zipcode', label: 'Zip Code', type: 'text', section: 'Part 8: Diseases' },
  { key: 'pt8_l5C_DateOfReferral', pdfKey: 'pt8_l5c_dateofreferral', label: 'Date of Referral', type: 'date', section: 'Part 8: Diseases' },
  { key: 'pt8_l5D_Remarks', pdfKey: 'pt8_l5d_remarks', label: 'Remarks', type: 'text', section: 'Part 8: Diseases' },
  // === Part 9: Vaccinations ===
  { key: 'pt9_l1_FamilyName', pdfKey: 'pt9_l1_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 9: Vaccinations' },
  { key: 'pt9_l1_GivenName', pdfKey: 'pt9_l1_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 9: Vaccinations' },
  { key: 'pt9_l1_MiddleName', pdfKey: 'pt9_l1_middlename', label: 'Middle Name', type: 'text', section: 'Part 9: Vaccinations' },
  { key: 'pt9_l1_NameOfMPorHD', pdfKey: 'pt9_l1_nameofmporhd', label: 'Name of Mpor Hd', type: 'text', section: 'Part 9: Vaccinations' },
  { key: 'pt9_l2_AptSteFlrNumber', pdfKey: 'pt9_l2_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 9: Vaccinations' },
  { key: 'pt9_l2_CityOrTown', pdfKey: 'pt9_l2_cityortown', label: 'City or Town', type: 'text', section: 'Part 9: Vaccinations' },
  { key: 'pt9_l2_State', pdfKey: 'pt9_l2_state', label: 'State', type: 'text', section: 'Part 9: Vaccinations' },
  { key: 'pt9_l2_StreetNumberName', pdfKey: 'pt9_l2_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 9: Vaccinations' },
  { key: 'pt9_l2_Unit', pdfKey: 'pt9_l2_unit', label: 'Unit', type: 'checkbox', section: 'Part 9: Vaccinations' },
  { key: 'pt9_l2_Unit_1', pdfKey: 'pt9_l2_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 9: Vaccinations' },
  { key: 'pt9_l2_Unit_2', pdfKey: 'pt9_l2_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 9: Vaccinations' },
  { key: 'pt9_l2_ZipCode', pdfKey: 'pt9_l2_zipcode', label: 'Zip Code', type: 'text', section: 'Part 9: Vaccinations' },
  { key: 'pt9_l3_DateSigned', pdfKey: 'pt9_l3_datesigned', label: 'Date Signed', type: 'date', section: 'Part 9: Vaccinations' },
  { key: 'pt9_l3_Signature', pdfKey: 'pt9_l3_signature', label: 'Signature', type: 'text', section: 'Part 9: Vaccinations' },
  { key: 'pt9_l4_NameOfMPorHD', pdfKey: 'pt9_l4_nameofmporhd', label: 'Name of Mpor Hd', type: 'text', section: 'Part 9: Vaccinations' },
  { key: 'pt9_l5_DaytimePhone', pdfKey: 'pt9_l5_daytimephone', label: 'Daytime Phone', type: 'text', section: 'Part 9: Vaccinations' },
  { key: 'pt9_l0_TDVaccineCheckBox', pdfKey: 'pt9_l0_tdvaccinecheckbox', label: 'Tdvaccine Check Box', type: 'checkbox', section: 'Part 9: Vaccinations' },
  // === Part 10: Disorders ===
  { key: 'pt10_l0_PVVaccineCheckBox', pdfKey: 'pt10_l0_pvvaccinecheckbox', label: 'Pvvaccine Check Box', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l0_PVVaccineCheckBox_1', pdfKey: 'pt10_l0_pvvaccinecheckbox_1', label: 'Pvvaccine Check Box (Item 2)', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l0_TDVaccineCheckBox', pdfKey: 'pt10_l0_tdvaccinecheckbox', label: 'Tdvaccine Check Box', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l0_VaccineCheckBox', pdfKey: 'pt10_l0_vaccinecheckbox', label: 'Vaccine Check Box', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l0_VaccineCheckBox_1', pdfKey: 'pt10_l0_vaccinecheckbox_1', label: 'Vaccine Check Box (Item 2)', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l0_VaccineCheckBox_2', pdfKey: 'pt10_l0_vaccinecheckbox_2', label: 'Vaccine Check Box (Item 3)', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l10_ContraCheckBox10', pdfKey: 'pt10_l10_contracheckbox10', label: 'Contra Check Box10', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l10_DateGiven_1', pdfKey: 'pt10_l10_dategiven_1', label: 'Date Given (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l10_InsufficientCheckBox10', pdfKey: 'pt10_l10_insufficientcheckbox10', label: 'Insufficient Check Box10', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l10_InsufficientCheckBox9', pdfKey: 'pt10_l10_insufficientcheckbox9', label: 'Insufficient Check Box9', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l10_NotAge10', pdfKey: 'pt10_l10_notage10', label: 'Not Age10', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l10a_DateReceived_1', pdfKey: 'pt10_l10a_datereceived_1', label: 'Date Received (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l10b_DateReceived_2', pdfKey: 'pt10_l10b_datereceived_2', label: 'Date Received (Item 3)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l10c_DateReceived_3', pdfKey: 'pt10_l10c_datereceived_3', label: 'Date Received (Item 4)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l10d_DateReceived_4', pdfKey: 'pt10_l10d_datereceived_4', label: 'Date Received (Item 5)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l11_ContraCheckBox11', pdfKey: 'pt10_l11_contracheckbox11', label: 'Contra Check Box11', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l11_DateGiven_1', pdfKey: 'pt10_l11_dategiven_1', label: 'Date Given (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l11_InsufficientCheckBox11', pdfKey: 'pt10_l11_insufficientcheckbox11', label: 'Insufficient Check Box11', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l11_NotAge11', pdfKey: 'pt10_l11_notage11', label: 'Not Age11', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l11a_DateReceived_1', pdfKey: 'pt10_l11a_datereceived_1', label: 'Date Received (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l11b_DateReceived_2', pdfKey: 'pt10_l11b_datereceived_2', label: 'Date Received (Item 3)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l11c_DateReceived_3', pdfKey: 'pt10_l11c_datereceived_3', label: 'Date Received (Item 4)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l11d_DateReceived_4', pdfKey: 'pt10_l11d_datereceived_4', label: 'Date Received (Item 5)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l12_ContraCheckBox12', pdfKey: 'pt10_l12_contracheckbox12', label: 'Contra Check Box12', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l12_DateGiven_1', pdfKey: 'pt10_l12_dategiven_1', label: 'Date Given (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l12_InsufficientCheckBox12', pdfKey: 'pt10_l12_insufficientcheckbox12', label: 'Insufficient Check Box12', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l12_NotAge12', pdfKey: 'pt10_l12_notage12', label: 'Not Age12', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l12a_DateReceived_1', pdfKey: 'pt10_l12a_datereceived_1', label: 'Date Received (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l12b_DateReceived_2', pdfKey: 'pt10_l12b_datereceived_2', label: 'Date Received (Item 3)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l12c_DateReceived_3', pdfKey: 'pt10_l12c_datereceived_3', label: 'Date Received (Item 4)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l12d_DateReceived_4', pdfKey: 'pt10_l12d_datereceived_4', label: 'Date Received (Item 5)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l13_CheckBox13', pdfKey: 'pt10_l13_checkbox13', label: 'Check Box13', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l13_CompleteSeries', pdfKey: 'pt10_l13_completeseries', label: 'Complete Series', type: 'text', section: 'Part 10: Disorders' },
  { key: 'pt10_l13_ContraCheckBox12', pdfKey: 'pt10_l13_contracheckbox12', label: 'Contra Check Box12', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l13_DateGiven_1', pdfKey: 'pt10_l13_dategiven_1', label: 'Date Given (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l13_InsufficientCheckBox12', pdfKey: 'pt10_l13_insufficientcheckbox12', label: 'Insufficient Check Box12', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l13_NotAge12', pdfKey: 'pt10_l13_notage12', label: 'Not Age12', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l13a_DateReceived_1', pdfKey: 'pt10_l13a_datereceived_1', label: 'Date Received (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l13b_DateReceived_2', pdfKey: 'pt10_l13b_datereceived_2', label: 'Date Received (Item 3)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l13c_DateReceived_3', pdfKey: 'pt10_l13c_datereceived_3', label: 'Date Received (Item 4)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l13d_DateReceived_4', pdfKey: 'pt10_l13d_datereceived_4', label: 'Date Received (Item 5)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_CompleteSeries', pdfKey: 'pt10_l1_completeseries', label: 'Complete Series', type: 'text', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_CompleteSeries_1', pdfKey: 'pt10_l1_completeseries_1', label: 'Complete Series (Item 2)', type: 'text', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_CompleteSeries_2', pdfKey: 'pt10_l1_completeseries_2', label: 'Complete Series (Item 3)', type: 'text', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_CompleteSeries_3', pdfKey: 'pt10_l1_completeseries_3', label: 'Complete Series (Item 4)', type: 'text', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_CompleteSeries_4', pdfKey: 'pt10_l1_completeseries_4', label: 'Complete Series (Item 5)', type: 'text', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_CompleteSeries_5', pdfKey: 'pt10_l1_completeseries_5', label: 'Complete Series (Item 6)', type: 'text', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_CompleteSeries_6', pdfKey: 'pt10_l1_completeseries_6', label: 'Complete Series (Item 7)', type: 'text', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_CompleteSeries_7', pdfKey: 'pt10_l1_completeseries_7', label: 'Complete Series (Item 8)', type: 'text', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_ContraCheckBox1', pdfKey: 'pt10_l1_contracheckbox1', label: 'Contra Check Box1', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_DTCompleteSeries', pdfKey: 'pt10_l1_dtcompleteseries', label: 'Dtcomplete Series', type: 'text', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_DTDateGiven', pdfKey: 'pt10_l1_dtdategiven', label: 'Dtdate Given', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_DTDateReceived1', pdfKey: 'pt10_l1_dtdatereceived1', label: 'Dtdate Received1', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_DTDateReceived2', pdfKey: 'pt10_l1_dtdatereceived2', label: 'Dtdate Received2', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_DTDateReceived3', pdfKey: 'pt10_l1_dtdatereceived3', label: 'Dtdate Received3', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_DTDateReceived4', pdfKey: 'pt10_l1_dtdatereceived4', label: 'Dtdate Received4', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_HBCompleteSeries', pdfKey: 'pt10_l1_hbcompleteseries', label: 'Hbcomplete Series', type: 'text', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_InsufficientCheckBox1', pdfKey: 'pt10_l1_insufficientcheckbox1', label: 'Insufficient Check Box1', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l1_NotAge1', pdfKey: 'pt10_l1_notage1', label: 'Not Age1', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l2_InsufficientCheckBox2', pdfKey: 'pt10_l2_insufficientcheckbox2', label: 'Insufficient Check Box2', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l2_NotAge2', pdfKey: 'pt10_l2_notage2', label: 'Not Age2', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l2_TdCompleteSeries', pdfKey: 'pt10_l2_tdcompleteseries', label: 'Td Complete Series', type: 'text', section: 'Part 10: Disorders' },
  { key: 'pt10_l2_TdContra', pdfKey: 'pt10_l2_tdcontra', label: 'Td Contra', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l2_TdDateGiven', pdfKey: 'pt10_l2_tddategiven', label: 'Td Date Given', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l2_TdDateReceived1', pdfKey: 'pt10_l2_tddatereceived1', label: 'Td Date Received1', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l2_TdDateReceived2', pdfKey: 'pt10_l2_tddatereceived2', label: 'Td Date Received2', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l2_TdDateReceived3', pdfKey: 'pt10_l2_tddatereceived3', label: 'Td Date Received3', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l2_TdDateReceived4', pdfKey: 'pt10_l2_tddatereceived4', label: 'Td Date Received4', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l3_ContraCheckBox3', pdfKey: 'pt10_l3_contracheckbox3', label: 'Contra Check Box3', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l3_DateGiven_1', pdfKey: 'pt10_l3_dategiven_1', label: 'Date Given (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l3_InsufficientCheckBox3', pdfKey: 'pt10_l3_insufficientcheckbox3', label: 'Insufficient Check Box3', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l3_NotAge3', pdfKey: 'pt10_l3_notage3', label: 'Not Age3', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l3a_DateReceived_1', pdfKey: 'pt10_l3a_datereceived_1', label: 'Date Received (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l3b_DateReceived_2', pdfKey: 'pt10_l3b_datereceived_2', label: 'Date Received (Item 3)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l3c_DateReceived_3', pdfKey: 'pt10_l3c_datereceived_3', label: 'Date Received (Item 4)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l3d_DateReceived_4', pdfKey: 'pt10_l3d_datereceived_4', label: 'Date Received (Item 5)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l4_ContraCheckBox4', pdfKey: 'pt10_l4_contracheckbox4', label: 'Contra Check Box4', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l4_DateGiven_1', pdfKey: 'pt10_l4_dategiven_1', label: 'Date Given (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l4_InsufficientCheckBox4', pdfKey: 'pt10_l4_insufficientcheckbox4', label: 'Insufficient Check Box4', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l4_NotAge4', pdfKey: 'pt10_l4_notage4', label: 'Not Age4', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l4a_DateReceived_1', pdfKey: 'pt10_l4a_datereceived_1', label: 'Date Received (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l4b_DateReceived_2', pdfKey: 'pt10_l4b_datereceived_2', label: 'Date Received (Item 3)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l4c_DateReceived_3', pdfKey: 'pt10_l4c_datereceived_3', label: 'Date Received (Item 4)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l4d_DateReceived_4', pdfKey: 'pt10_l4d_datereceived_4', label: 'Date Received (Item 5)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l5_ContraCheckBox5', pdfKey: 'pt10_l5_contracheckbox5', label: 'Contra Check Box5', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l5_DateGiven_1', pdfKey: 'pt10_l5_dategiven_1', label: 'Date Given (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l5_InsufficientCheckBox5', pdfKey: 'pt10_l5_insufficientcheckbox5', label: 'Insufficient Check Box5', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l5_NotAge5', pdfKey: 'pt10_l5_notage5', label: 'Not Age5', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l5a_DateReceived_1', pdfKey: 'pt10_l5a_datereceived_1', label: 'Date Received (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l5b_DateReceived_2', pdfKey: 'pt10_l5b_datereceived_2', label: 'Date Received (Item 3)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l5c_DateReceived_3', pdfKey: 'pt10_l5c_datereceived_3', label: 'Date Received (Item 4)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l5d_DateReceived_4', pdfKey: 'pt10_l5d_datereceived_4', label: 'Date Received (Item 5)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l6_ContraCheckBox6', pdfKey: 'pt10_l6_contracheckbox6', label: 'Contra Check Box6', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l6_HBDateGiven', pdfKey: 'pt10_l6_hbdategiven', label: 'Hbdate Given', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l6_HBDateReceived1', pdfKey: 'pt10_l6_hbdatereceived1', label: 'Hbdate Received1', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l6_HBDateReceived2', pdfKey: 'pt10_l6_hbdatereceived2', label: 'Hbdate Received2', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l6_HBDateReceived3', pdfKey: 'pt10_l6_hbdatereceived3', label: 'Hbdate Received3', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l6_HBDateReceived4', pdfKey: 'pt10_l6_hbdatereceived4', label: 'Hbdate Received4', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l6_InsufficientCheckBox6', pdfKey: 'pt10_l6_insufficientcheckbox6', label: 'Insufficient Check Box6', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l6_NotAge6', pdfKey: 'pt10_l6_notage6', label: 'Not Age6', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l7_ContraCheckBox7', pdfKey: 'pt10_l7_contracheckbox7', label: 'Contra Check Box7', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l7_DateGiven_1', pdfKey: 'pt10_l7_dategiven_1', label: 'Date Given (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l7_InsufficientCheckBox7', pdfKey: 'pt10_l7_insufficientcheckbox7', label: 'Insufficient Check Box7', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l7_NotAge7', pdfKey: 'pt10_l7_notage7', label: 'Not Age7', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l7a_DateReceived_1', pdfKey: 'pt10_l7a_datereceived_1', label: 'Date Received (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l7b_DateReceived_2', pdfKey: 'pt10_l7b_datereceived_2', label: 'Date Received (Item 3)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l7c_DateReceived_3', pdfKey: 'pt10_l7c_datereceived_3', label: 'Date Received (Item 4)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l7d_DateReceived_4', pdfKey: 'pt10_l7d_datereceived_4', label: 'Date Received (Item 5)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l8_ContraCheckBox8', pdfKey: 'pt10_l8_contracheckbox8', label: 'Contra Check Box8', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l8_DateGiven_1', pdfKey: 'pt10_l8_dategiven_1', label: 'Date Given (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l8_InsufficientCheckBox8', pdfKey: 'pt10_l8_insufficientcheckbox8', label: 'Insufficient Check Box8', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l8_NotAge8', pdfKey: 'pt10_l8_notage8', label: 'Not Age8', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l8a_DateReceived_1', pdfKey: 'pt10_l8a_datereceived_1', label: 'Date Received (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l8b_DateReceived_2', pdfKey: 'pt10_l8b_datereceived_2', label: 'Date Received (Item 3)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l8c_DateReceived_3', pdfKey: 'pt10_l8c_datereceived_3', label: 'Date Received (Item 4)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l8d_DateReceived_4', pdfKey: 'pt10_l8d_datereceived_4', label: 'Date Received (Item 5)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l9_ContraCheckBox9', pdfKey: 'pt10_l9_contracheckbox9', label: 'Contra Check Box9', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l9_DateGiven_1', pdfKey: 'pt10_l9_dategiven_1', label: 'Date Given (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l9_InfluVaccineInsufficient9', pdfKey: 'pt10_l9_influvaccineinsufficient9', label: 'Influ Vaccine Insufficient9', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l9_NotAge9', pdfKey: 'pt10_l9_notage9', label: 'Not Age9', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l9a_DateReceived_1', pdfKey: 'pt10_l9a_datereceived_1', label: 'Date Received (Item 2)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l9b_DateReceived_2', pdfKey: 'pt10_l9b_datereceived_2', label: 'Date Received (Item 3)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l9c_DateReceived_3', pdfKey: 'pt10_l9c_datereceived_3', label: 'Date Received (Item 4)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l9d_DateReceived_4', pdfKey: 'pt10_l9d_datereceived_4', label: 'Date Received (Item 5)', type: 'date', section: 'Part 10: Disorders' },
  { key: 'pt10_l0_Remarks', pdfKey: 'pt10_l0_remarks', label: 'Remarks', type: 'text', section: 'Part 10: Disorders' },
  { key: 'pt10_l0_Results', pdfKey: 'pt10_l0_results', label: 'Results', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l0_Results_1', pdfKey: 'pt10_l0_results_1', label: 'Results (Item 2)', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_l0_Results_2', pdfKey: 'pt10_l0_results_2', label: 'Results (Item 3)', type: 'checkbox', section: 'Part 10: Disorders' },
  { key: 'pt10_lUSCIS_Remarks', pdfKey: 'pt10_luscis_remarks', label: 'Remarks', type: 'text', section: 'Part 10: Disorders' },
  // === Part 11: Drug Addiction ===
  { key: 'pt11_l3a_PageNumber', pdfKey: 'pt11_l3a_pagenumber', label: 'Page Number', type: 'text', section: 'Part 11: Drug Addiction' },
  { key: 'pt11_l3b_PartNumber', pdfKey: 'pt11_l3b_partnumber', label: 'Part Number', type: 'text', section: 'Part 11: Drug Addiction' },
  { key: 'pt11_l3c_ItemNumber', pdfKey: 'pt11_l3c_itemnumber', label: 'Item Number', type: 'text', section: 'Part 11: Drug Addiction' },
  { key: 'pt11_l3d_AdditionalInfo', pdfKey: 'pt11_l3d_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 11: Drug Addiction' },
  { key: 'pt11_l4a_PageNumber', pdfKey: 'pt11_l4a_pagenumber', label: 'Page Number', type: 'text', section: 'Part 11: Drug Addiction' },
  { key: 'pt11_l4b_PartNumber', pdfKey: 'pt11_l4b_partnumber', label: 'Part Number', type: 'text', section: 'Part 11: Drug Addiction' },
  { key: 'pt11_l4c_ItemNumber', pdfKey: 'pt11_l4c_itemnumber', label: 'Item Number', type: 'text', section: 'Part 11: Drug Addiction' },
  { key: 'pt11_l4d_AdditionalInfo', pdfKey: 'pt11_l4d_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 11: Drug Addiction' },
  { key: 'pt11_l5a_PageNumber', pdfKey: 'pt11_l5a_pagenumber', label: 'Page Number', type: 'text', section: 'Part 11: Drug Addiction' },
  { key: 'pt11_l5b_PartNumber', pdfKey: 'pt11_l5b_partnumber', label: 'Part Number', type: 'text', section: 'Part 11: Drug Addiction' },
  { key: 'pt11_l5c_ItemNumber', pdfKey: 'pt11_l5c_itemnumber', label: 'Item Number', type: 'text', section: 'Part 11: Drug Addiction' },
  { key: 'pt11_l5d_AdditionalInfo', pdfKey: 'pt11_l5d_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 11: Drug Addiction' },
  { key: 'pt11_l6a_PageNumber', pdfKey: 'pt11_l6a_pagenumber', label: 'Page Number', type: 'text', section: 'Part 11: Drug Addiction' },
  { key: 'pt11_l6b_PartNumber', pdfKey: 'pt11_l6b_partnumber', label: 'Part Number', type: 'text', section: 'Part 11: Drug Addiction' },
  { key: 'pt11_l6c_ItemNumber', pdfKey: 'pt11_l6c_itemnumber', label: 'Item Number', type: 'text', section: 'Part 11: Drug Addiction' },
  { key: 'pt11_l6d_AdditionalInfo', pdfKey: 'pt11_l6d_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 11: Drug Addiction' },
];

export const getInitialFormData = () => {
  const data: Record<string, string> = {};
  formFields.forEach((f) => { if (f.key) data[f.key] = ''; });
  return data;
};

export const i693Config = { formId, formTitle, formSubtitle, formFields, getInitialFormData };
export default i693Config;