// Generated fields for Form I-864EZ
import type { Field } from './types';

export const formId = 'i864ez';
export const formTitle = 'Form I-864EZ';
export const formSubtitle = 'Affidavit of Support Under Section 213A of the INA';

export const formFields: Field[] = [
  // === Part 1: Eligibility ===
  { key: 'pt1_l1a_Checkbox', pdfKey: 'pt1_l1a_checkbox', label: '1.a. YES - I am the petitioner who filed the Form I-130 for the relative.', type: 'checkbox', section: 'Part 1: Eligibility' },
  { key: 'pt1_l1a_Checkbox_1', pdfKey: 'pt1_l1a_checkbox_1', label: '1.a. NO', type: 'checkbox', section: 'Part 1: Eligibility' },
  { key: 'pt1_l1b_Checkbox', pdfKey: 'pt1_l1b_checkbox', label: '1.b. YES - The relative being sponsored is the only person listed on Form I-130.', type: 'checkbox', section: 'Part 1: Eligibility' },
  { key: 'pt1_l1b_Checkbox_1', pdfKey: 'pt1_l1b_checkbox_1', label: '1.b. NO', type: 'checkbox', section: 'Part 1: Eligibility' },
  { key: 'pt1_l1c_Checkbox', pdfKey: 'pt1_l1c_checkbox', label: '1.c. YES - The income I am using to qualify is based entirely on my salary/pension.', type: 'checkbox', section: 'Part 1: Eligibility' },
  { key: 'pt1_l1c_Checkbox_1', pdfKey: 'pt1_l1c_checkbox_1', label: '1.c. NO', type: 'checkbox', section: 'Part 1: Eligibility' },
  // === Part 2: Immigrant Info ===
  { key: 'pt2_l1a_FamilyName', pdfKey: 'pt2_l1a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l1b_GivenName', pdfKey: 'pt2_l1b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l1c_MiddleName', pdfKey: 'pt2_l1c_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l2_AptSteFlrNumber', pdfKey: 'pt2_l2_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l2_CityOrTown', pdfKey: 'pt2_l2_cityortown', label: 'City or Town', type: 'text', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l2_Country', pdfKey: 'pt2_l2_country', label: 'Country', type: 'text', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l2_InCareofName', pdfKey: 'pt2_l2_incareofname', label: 'In Careof Name', type: 'text', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l2_PostalCode', pdfKey: 'pt2_l2_postalcode', label: 'Postal Code', type: 'text', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l2_Province', pdfKey: 'pt2_l2_province', label: 'Province', type: 'text', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l2_State', pdfKey: 'pt2_l2_state', label: 'State', type: 'text', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l2_StreetNumberName', pdfKey: 'pt2_l2_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l2_Unit', pdfKey: 'pt2_l2_unit', label: 'Unit', type: 'checkbox', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l2_Unit_1', pdfKey: 'pt2_l2_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l2_Unit_2', pdfKey: 'pt2_l2_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l2_ZipCode', pdfKey: 'pt2_l2_zipcode', label: 'Zip Code', type: 'text', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l3_DaytimeTelephoneNumber', pdfKey: 'pt2_l3_daytimetelephonenumber', label: 'Daytime Telephone Number', type: 'text', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l4_DateOfBirth', pdfKey: 'pt2_l4_dateofbirth', label: 'Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l5_AlienNumber', pdfKey: 'pt2_l5_aliennumber', label: 'A-Number', type: 'text', section: 'Part 2: Immigrant Info' },
  { key: 'pt2_l6_USCISOnlineAcctNumber', pdfKey: 'pt2_l6_uscisonlineacctnumber', label: 'USCIS Online Account Number', type: 'text', section: 'Part 2: Immigrant Info' },
  // === Part 3: Sponsor Info ===
  { key: 'pt3_l1a_FamilyName', pdfKey: 'pt3_l1a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l1b_GivenName', pdfKey: 'pt3_l1b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l1c_MiddleName', pdfKey: 'pt3_l1c_middlename', label: 'Middle Name', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l2a_InCareofName', pdfKey: 'pt3_l2a_incareofname', label: 'In Careof Name', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l2b_StreetNumberName', pdfKey: 'pt3_l2b_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l2c_AptSteFlrNumber', pdfKey: 'pt3_l2c_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l2c_Unit', pdfKey: 'pt3_l2c_unit', label: 'Unit', type: 'checkbox', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l2c_Unit_1', pdfKey: 'pt3_l2c_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l2c_Unit_2', pdfKey: 'pt3_l2c_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l2d_CityOrTown', pdfKey: 'pt3_l2d_cityortown', label: 'City or Town', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l2e_State', pdfKey: 'pt3_l2e_state', label: 'State', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l2f_ZipCode', pdfKey: 'pt3_l2f_zipcode', label: 'Zip Code', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l2g_Province', pdfKey: 'pt3_l2g_province', label: 'Province', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l2h_PostalCode', pdfKey: 'pt3_l2h_postalcode', label: 'Postal Code', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l2i_Country', pdfKey: 'pt3_l2i_country', label: 'Country', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l3_Checkbox', pdfKey: 'pt3_l3_checkbox', label: 'Part 3, Item 3', type: 'checkbox', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l3_Checkbox_1', pdfKey: 'pt3_l3_checkbox_1', label: 'Part 3, Item 3', type: 'checkbox', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l10_SSN', pdfKey: 'pt3_l10_ssn', label: 'Social Security Number', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l12_Checkbox', pdfKey: 'pt3_l12_checkbox', label: 'Part 3, Item 12', type: 'checkbox', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l12_Checkbox_1', pdfKey: 'pt3_l12_checkbox_1', label: 'Part 3, Item 12', type: 'checkbox', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l12_Checkbox_2', pdfKey: 'pt3_l12_checkbox_2', label: 'Part 3, Item 12', type: 'checkbox', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l12c_AlienNumber', pdfKey: 'pt3_l12c_aliennumber', label: 'A-Number', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l13_Checkbox', pdfKey: 'pt3_l13_checkbox', label: 'Part 3, Item 13', type: 'checkbox', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l13_Checkbox_1', pdfKey: 'pt3_l13_checkbox_1', label: 'Part 3, Item 13', type: 'checkbox', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l2_USCISOnlineAcctNumber', pdfKey: 'pt3_l2_uscisonlineacctnumber', label: 'USCIS Online Account Number', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l4a_StreetNumberNameA', pdfKey: 'pt3_l4a_streetnumbernamea', label: 'Street Number Name A', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l4b_AptSteFlrNumberA', pdfKey: 'pt3_l4b_aptsteflrnumbera', label: 'Apt Ste Flr Number A', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l4b_UnitA', pdfKey: 'pt3_l4b_unita', label: 'Unit A', type: 'checkbox', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l4b_UnitA_1', pdfKey: 'pt3_l4b_unita_1', label: 'Unit A (Item 2)', type: 'checkbox', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l4b_UnitA_2', pdfKey: 'pt3_l4b_unita_2', label: 'Unit A (Item 3)', type: 'checkbox', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l4c_CityOrTown', pdfKey: 'pt3_l4c_cityortown', label: 'City or Town', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l4d_State', pdfKey: 'pt3_l4d_state', label: 'State', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l4e_ZipCode', pdfKey: 'pt3_l4e_zipcode', label: 'Zip Code', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l4f_Province', pdfKey: 'pt3_l4f_province', label: 'Province', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l4g_PostalCode', pdfKey: 'pt3_l4g_postalcode', label: 'Postal Code', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l4h_Country', pdfKey: 'pt3_l4h_country', label: 'Country', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l5_CountryofDomicile', pdfKey: 'pt3_l5_countryofdomicile', label: 'Countryof Domicile', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l6_DateOfBirth', pdfKey: 'pt3_l6_dateofbirth', label: 'Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l9_CountryofBirth', pdfKey: 'pt3_l9_countryofbirth', label: 'Countryof Birth', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l3_CountryNationality', pdfKey: 'pt3_l3_countrynationality', label: 'Country Nationality', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l12c_AlienNumber_1', pdfKey: 'pt3_l12c_aliennumber_1', label: 'A-Number (Item 2)', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l1a_FamilyName_1', pdfKey: 'pt3_l1a_familyname_1', label: 'Family Name (Last Name) (Item 2)', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l1b_GivenName_1', pdfKey: 'pt3_l1b_givenname_1', label: 'Given Name (First Name) (Item 2)', type: 'text', section: 'Part 3: Sponsor Info' },
  { key: 'pt3_l1c_MiddleName_1', pdfKey: 'pt3_l1c_middlename_1', label: 'Middle Name (Item 2)', type: 'text', section: 'Part 3: Sponsor Info' },
  // === Part 4: Household Size ===
  { key: 'pt4_l1a_TotalNumberofImmigrants', pdfKey: 'pt4_l1a_totalnumberofimmigrants', label: 'Total Numberof Immigrants', type: 'text', section: 'Part 4: Household Size' },
  { key: 'pt4_l1b_Spouse', pdfKey: 'pt4_l1b_spouse', label: 'Spouse', type: 'text', section: 'Part 4: Household Size' },
  { key: 'pt4_l1c_Dependent', pdfKey: 'pt4_l1c_dependent', label: 'Dependent', type: 'text', section: 'Part 4: Household Size' },
  { key: 'pt4_l1d_sponsoredpersons', pdfKey: 'pt4_l1d_sponsoredpersons', label: 'Sponsoredpersons', type: 'text', section: 'Part 4: Household Size' },
  { key: 'pt4_l1e_otherDependents', pdfKey: 'pt4_l1e_otherdependents', label: 'Other Dependents', type: 'text', section: 'Part 4: Household Size' },
  { key: 'pt4_l1f_AddTogether', pdfKey: 'pt4_l1f_addtogether', label: 'Add Together', type: 'text', section: 'Part 4: Household Size' },
  // === Part 5: Income & Tax ===
  { key: 'pt5_l1_Checkbox', pdfKey: 'pt5_l1_checkbox', label: 'Part 5, Item 1', type: 'checkbox', section: 'Part 5: Income & Tax' },
  { key: 'pt5_l1_Checkbox_1', pdfKey: 'pt5_l1_checkbox_1', label: 'Part 5, Item 1', type: 'checkbox', section: 'Part 5: Income & Tax' },
  { key: 'pt5_l2b_NameofEmployer', pdfKey: 'pt5_l2b_nameofemployer', label: 'Nameof Employer', type: 'text', section: 'Part 5: Income & Tax' },
  { key: 'pt5_l2c_NameofEmployer', pdfKey: 'pt5_l2c_nameofemployer', label: 'Nameof Employer', type: 'text', section: 'Part 5: Income & Tax' },
  { key: 'pt5_l3b_DateofRetirement', pdfKey: 'pt5_l3b_dateofretirement', label: 'Dateof Retirement', type: 'date', section: 'Part 5: Income & Tax' },
  { key: 'pt5_l4_AnnualIncome', pdfKey: 'pt5_l4_annualincome', label: 'Annual Income', type: 'text', section: 'Part 5: Income & Tax' },
  { key: 'pt5_l5a_Checkbox', pdfKey: 'pt5_l5a_checkbox', label: 'Part 5, Item 5a', type: 'checkbox', section: 'Part 5: Income & Tax' },
  { key: 'pt5_l5a_Checkbox_1', pdfKey: 'pt5_l5a_checkbox_1', label: 'Part 5, Item 5a', type: 'checkbox', section: 'Part 5: Income & Tax' },
  { key: 'pt5_l6a_TaxYear', pdfKey: 'pt5_l6a_taxyear', label: 'Tax Year', type: 'text', section: 'Part 5: Income & Tax' },
  { key: 'pt5_l6a_TotalIncome', pdfKey: 'pt5_l6a_totalincome', label: 'Total Income', type: 'text', section: 'Part 5: Income & Tax' },
  { key: 'pt5_l6b_TaxYear', pdfKey: 'pt5_l6b_taxyear', label: 'Tax Year', type: 'text', section: 'Part 5: Income & Tax' },
  { key: 'pt5_l6b_TotalIncome', pdfKey: 'pt5_l6b_totalincome', label: 'Total Income', type: 'text', section: 'Part 5: Income & Tax' },
  { key: 'pt5_l6c_TaxYear', pdfKey: 'pt5_l6c_taxyear', label: 'Tax Year', type: 'text', section: 'Part 5: Income & Tax' },
  { key: 'pt5_l6c_TotalIncome', pdfKey: 'pt5_l6c_totalincome', label: 'Total Income', type: 'text', section: 'Part 5: Income & Tax' },
  // === Part 6: Sponsor Statement ===
  { key: 'pt6_l1_Checkbox', pdfKey: 'pt6_l1_checkbox', label: '1.a. I can read and understand English, and I have read and understand every question and instruction.', type: 'checkbox', section: 'Part 6: Sponsor Statement' },
  { key: 'pt6_l1_Checkbox_1', pdfKey: 'pt6_l1_checkbox_1', label: '1.b. The interpreter named in Part 7. read to me every question and instruction on this affidavit.', type: 'checkbox', section: 'Part 6: Sponsor Statement' },
  { key: 'pt6_l1b_language', pdfKey: 'pt6_l1b_language', label: 'Language', type: 'text', section: 'Part 6: Sponsor Statement' },
  { key: 'pt6_l2_Attorney', pdfKey: 'pt6_l2_attorney', label: 'Attorney', type: 'text', section: 'Part 6: Sponsor Statement' },
  { key: 'pt6_l2_Checkbox', pdfKey: 'pt6_l2_checkbox', label: '2. At my request, the preparer named in Part 8. prepared this affidavit based only on information I provided.', type: 'checkbox', section: 'Part 6: Sponsor Statement' },
  { key: 'pt6_l3_DaytimeTelephoneNumber', pdfKey: 'pt6_l3_daytimetelephonenumber', label: 'Daytime Telephone Number', type: 'text', section: 'Part 6: Sponsor Statement' },
  { key: 'pt6_l4_MobileTelephoneNumber', pdfKey: 'pt6_l4_mobiletelephonenumber', label: 'Mobile Telephone Number', type: 'text', section: 'Part 6: Sponsor Statement' },
  { key: 'pt6_l6a_ApplicantSignature', pdfKey: 'pt6_l6a_applicantsignature', label: 'Applicant Signature', type: 'text', section: 'Part 6: Sponsor Statement' },
  { key: 'pt6_l6b_DateofSignature', pdfKey: 'pt6_l6b_dateofsignature', label: 'Dateof Signature', type: 'date', section: 'Part 6: Sponsor Statement' },
  // === Part 7: Interpreter ===
  { key: 'pt7_l7_EmailAddress', pdfKey: 'pt7_l7_emailaddress', label: 'Email Address', type: 'text', section: 'Part 7: Interpreter' },
  { key: 'pt7_l0_Language', pdfKey: 'pt7_l0_language', label: 'Language', type: 'text', section: 'Part 7: Interpreter' },
  { key: 'pt7_l1a_InterpretersFamilyName', pdfKey: 'pt7_l1a_interpretersfamilyname', label: 'Interpreters Family Name', type: 'text', section: 'Part 7: Interpreter' },
  { key: 'pt7_l1b_InterpretersGivenName', pdfKey: 'pt7_l1b_interpretersgivenname', label: 'Interpreters Given Name', type: 'text', section: 'Part 7: Interpreter' },
  { key: 'pt7_l4_InterpretersDaytimePhoneNumber', pdfKey: 'pt7_l4_interpretersdaytimephonenumber', label: 'Interpreters Daytime Phone Number', type: 'text', section: 'Part 7: Interpreter' },
  { key: 'pt7_l4_InterpretersDaytimePhoneNumber_1', pdfKey: 'pt7_l4_interpretersdaytimephonenumber_1', label: 'Interpreters Daytime Phone Number (Item 2)', type: 'text', section: 'Part 7: Interpreter' },
  { key: 'pt7_l5_InterpretersEmailAddress', pdfKey: 'pt7_l5_interpretersemailaddress', label: 'Interpreters Email Address', type: 'text', section: 'Part 7: Interpreter' },
  { key: 'pt7_l6a_InterpretersSignature', pdfKey: 'pt7_l6a_interpreterssignature', label: 'Interpreters Signature', type: 'text', section: 'Part 7: Interpreter' },
  { key: 'pt7_l6b_DateofSignature', pdfKey: 'pt7_l6b_dateofsignature', label: 'Dateof Signature', type: 'date', section: 'Part 7: Interpreter' },
  // === Part 8: Preparer ===
  { key: 'pt8_l1a_PreparersFamilyName', pdfKey: 'pt8_l1a_preparersfamilyname', label: 'Preparers Family Name', type: 'text', section: 'Part 8: Preparer' },
  { key: 'pt8_l1b_PreparersGivenName', pdfKey: 'pt8_l1b_preparersgivenname', label: 'Preparers Given Name', type: 'text', section: 'Part 8: Preparer' },
  { key: 'pt8_l2_PreparersBusinessName', pdfKey: 'pt8_l2_preparersbusinessname', label: 'Preparers Business Name', type: 'text', section: 'Part 8: Preparer' },
  { key: 'pt8_l4_PreparersDaytimePhoneNumber', pdfKey: 'pt8_l4_preparersdaytimephonenumber', label: 'Preparers Daytime Phone Number', type: 'text', section: 'Part 8: Preparer' },
  { key: 'pt8_l5_PreparersFaxNumber', pdfKey: 'pt8_l5_preparersfaxnumber', label: 'Preparers Fax Number', type: 'text', section: 'Part 8: Preparer' },
  { key: 'pt8_l6_PreparersEmailAddress', pdfKey: 'pt8_l6_preparersemailaddress', label: 'Preparers Email Address', type: 'text', section: 'Part 8: Preparer' },
  { key: 'pt8_l8a_PreparersSignature', pdfKey: 'pt8_l8a_preparerssignature', label: 'Preparers Signature', type: 'text', section: 'Part 8: Preparer' },
  { key: 'pt8_l8b_DateofSignature', pdfKey: 'pt8_l8b_dateofsignature', label: 'Dateof Signature', type: 'date', section: 'Part 8: Preparer' },
  // === Part 9: Additional Info ===
  { key: 'pt9_l3a_PageNumber', pdfKey: 'pt9_l3a_pagenumber', label: 'Page Number', type: 'text', section: 'Part 9: Additional Info' },
  { key: 'pt9_l3b_PartNumber', pdfKey: 'pt9_l3b_partnumber', label: 'Part Number', type: 'text', section: 'Part 9: Additional Info' },
  { key: 'pt9_l3c_ItemNumber', pdfKey: 'pt9_l3c_itemnumber', label: 'Item Number', type: 'text', section: 'Part 9: Additional Info' },
  { key: 'pt9_l3d_AdditionalInfo', pdfKey: 'pt9_l3d_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 9: Additional Info' },
  { key: 'pt9_l4a_PageNumber', pdfKey: 'pt9_l4a_pagenumber', label: 'Page Number', type: 'text', section: 'Part 9: Additional Info' },
  { key: 'pt9_l4b_PartNumber', pdfKey: 'pt9_l4b_partnumber', label: 'Part Number', type: 'text', section: 'Part 9: Additional Info' },
  { key: 'pt9_l4c_ItemNumber', pdfKey: 'pt9_l4c_itemnumber', label: 'Item Number', type: 'text', section: 'Part 9: Additional Info' },
  { key: 'pt9_l4d_AdditionalInfo', pdfKey: 'pt9_l4d_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 9: Additional Info' },
  { key: 'pt9_l5a_PageNumber', pdfKey: 'pt9_l5a_pagenumber', label: 'Page Number', type: 'text', section: 'Part 9: Additional Info' },
  { key: 'pt9_l5b_PartNumber', pdfKey: 'pt9_l5b_partnumber', label: 'Part Number', type: 'text', section: 'Part 9: Additional Info' },
  { key: 'pt9_l5c_ItemNumber', pdfKey: 'pt9_l5c_itemnumber', label: 'Item Number', type: 'text', section: 'Part 9: Additional Info' },
  { key: 'pt9_l5d_AdditionalInfo', pdfKey: 'pt9_l5d_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 9: Additional Info' },
  { key: 'pt9_l6a_PageNumber', pdfKey: 'pt9_l6a_pagenumber', label: 'Page Number', type: 'text', section: 'Part 9: Additional Info' },
  { key: 'pt9_l6b_PartNumber', pdfKey: 'pt9_l6b_partnumber', label: 'Part Number', type: 'text', section: 'Part 9: Additional Info' },
  { key: 'pt9_l6c_ItemNumber', pdfKey: 'pt9_l6c_itemnumber', label: 'Item Number', type: 'text', section: 'Part 9: Additional Info' },
  { key: 'pt9_l6d_AdditionalInfo', pdfKey: 'pt9_l6d_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 9: Additional Info' },
];

export const getInitialFormData = () => {
  const data: Record<string, string> = {};
  formFields.forEach((f) => { if (f.key) data[f.key] = ''; });
  return data;
};

export const i864ezConfig = { formId, formTitle, formSubtitle, formFields, getInitialFormData };
export default i864ezConfig;