import type { Field } from "./types";

export const formId = "i864";
export const formTitle = "Form I-864";
export const formSubtitle = "Affidavit of Support Under Section 213A of the INA";

export const formFields: Field[] = [

  {
    key: "g28_attached",
    pdfKey: "g28_attached",
    label: "Is Form G-28 attached?",
    type: "checkbox",
    section: "Attorney or Accredited Representative",
  },
  {
    key: "attorney_bar_number",
    pdfKey: "attorney_bar_number",
    label: "Attorney State Bar Number",
    type: "text",
    section: "Attorney or Accredited Representative",
    condition: (d) => !!d.g28_attached,
  },
  {
    key: "g28_uscis_account",
    pdfKey: "g28_uscis_account",
    label: "USCIS Online Account Number (Attorney)",
    type: "text",
    section: "Attorney or Accredited Representative",
    condition: (d) => !!d.g28_attached,
  },

  // ============================================
  // PART 1. Basis for Filing Affidavit of Support
  // ============================================

  {
    key: "p1_relationship",
    pdfKey: "p1_relationship",
    label: "1. I am filing this affidavit of support as:",
    type: "radio",
    section: "Part 1. Basis for Filing Affidavit of Support",
    options: [
      { label: "The petitioner", value: "petition", pdfKey: "p1_relationship_petition" },
      { label: "A joint sponsor", value: "joint_5percent", pdfKey: "p1_relationship_joint_5percent" },
      { label: "A 5% owner of the entity", value: "joint_entity", pdfKey: "p1_relationship_joint_entity" },
      { label: "Substitute sponsor", value: "substitute", pdfKey: "p1_relationship_substitute" },
      { label: "Household member", value: "household_member", pdfKey: "p1_relationship_household_member" },
      { label: "Relative (other)", value: "relative", pdfKey: "p1_relationship_relative" },
    ],
  },
  {
    key: "p1_petitioner_relationship",
    pdfKey: "p1_relationship_detail_petition_b",
    label: "Relationship to the principal immigrant",
    type: "text",
    section: "Part 1. Basis for Filing Affidavit of Support",
    condition: (d) => d.p1_relationship === "petition",
  },
  {
    key: "p1_entity_name",
    pdfKey: "p1_relationship_detail_entity",
    label: "Name of the entity (if 5% owner)",
    type: "text",
    section: "Part 1. Basis for Filing Affidavit of Support",
    condition: (d) => d.p1_relationship === "joint_entity",
  },
  {
    key: "p1_relative_relationship",
    pdfKey: "p1_relationship_detail_relative",
    label: "Relationship to the intending immigrant (if relative)",
    type: "text",
    section: "Part 1. Basis for Filing Affidavit of Support",
    condition: (d) => d.p1_relationship === "relative",
  },
  {
    key: "p1_other_relationship",
    pdfKey: "p1_relationship_detail_other",
    label: "Other relationship (specify)",
    type: "text",
    section: "Part 1. Basis for Filing Affidavit of Support",
    condition: (d) => ["household_member", "relative"].includes(d.p1_relationship),
  },
  {
    key: "p1_legal_guardian",
    pdfKey: "p1_legal_guardian",
    label: "I am the legal guardian of the intending immigrant",
    type: "radio",
    section: "Part 1. Basis for Filing Affidavit of Support",
    options: [
      { label: "Yes", value: "Yes", pdfKey: "p1_legal_guardian_yes" },
      { label: "No", value: "No", pdfKey: "p1_legal_guardian_no" },
    ],
  },

  // ============================================
  // PART 4. Sponsor's Information
  // ============================================
  {
    key: "sponsor_family_name",
    pdfKey: "sponsor_family_name",
    label: "1.a. Family Name (Last Name)",
    type: "text",
    section: "Part 4. Sponsor Information",
    required: true,
  },
  {
    key: "sponsor_given_name",
    pdfKey: "sponsor_given_name",
    label: "1.b. Given Name (First Name)",
    type: "text",
    section: "Part 4. Sponsor Information",
    required: true,
  },
  {
    key: "sponsor_middle_name",
    pdfKey: "sponsor_middle_name",
    label: "1.c. Middle Name",
    type: "text",
    section: "Part 4. Sponsor Information",
  },

  // Mailing Address
  {
    key: "sponsor_in_care_of",
    pdfKey: "sponsor_in_care_of",
    label: "2.a. In Care Of Name",
    type: "text",
    section: "Part 4. Sponsor Information",
  },
  {
    key: "sponsor_street",
    pdfKey: "sponsor_street",
    label: "2.b. Street Number and Name",
    type: "text",
    section: "Part 4. Sponsor Information",
    required: true,
  },
  {
    key: "sponsor_unit_type",
    pdfKey: "sponsor_unit_type",
    label: "2.c. Unit",
    type: "radio",
    section: "Part 4. Sponsor Information",
    options: [
      { label: "Apt.", value: "Apt", pdfKey: "sponsor_unit_apt" },
      { label: "Ste.", value: "Ste", pdfKey: "sponsor_unit_ste" },
      { label: "Flr.", value: "Flr", pdfKey: "sponsor_unit_flr" },
    ],
  },
  {
    key: "sponsor_unit_number",
    pdfKey: "sponsor_unit_number",
    label: "2.d. Apt./Ste./Flr. Number",
    type: "text",
    section: "Part 4. Sponsor Information",
  },
  {
    key: "sponsor_city",
    pdfKey: "sponsor_city",
    label: "2.e. City or Town",
    type: "text",
    section: "Part 4. Sponsor Information",
    required: true,
  },
  {
    key: "sponsor_state",
    pdfKey: "sponsor_state",
    label: "2.f. State",
    type: "combo",
    section: "Part 4. Sponsor Information",
  },
  {
    key: "sponsor_zip",
    pdfKey: "sponsor_zip",
    label: "2.g. ZIP Code",
    type: "text",
    section: "Part 4. Sponsor Information",
    maxLength: 5,
  },
  {
    key: "sponsor_province",
    pdfKey: "sponsor_province",
    label: "2.h. Province",
    type: "text",
    section: "Part 4. Sponsor Information",
  },
  {
    key: "sponsor_postal_code",
    pdfKey: "sponsor_postal_code",
    label: "2.i. Postal Code",
    type: "text",
    section: "Part 4. Sponsor Information",
  },
  {
    key: "sponsor_country",
    pdfKey: "sponsor_country",
    label: "2.j. Country",
    type: "text",
    section: "Part 4. Sponsor Information",
    required: true,
  },

  // Is U.S. Citizen?
  {
    key: "sponsor_is_us_citizen",
    pdfKey: "sponsor_is_us_citizen",
    label: "3. Is your current mailing address the same as your physical address?",
    type: "radio",
    section: "Part 4. Sponsor Information",
    options: [
      { label: "Yes", value: "Yes", pdfKey: "sponsor_is_us_citizen_yes" },
      { label: "No", value: "No", pdfKey: "sponsor_is_us_citizen_no" },
    ],
  },

  // Mailing Address (if different)
  {
    key: "sponsor_mailing_street",
    pdfKey: "sponsor_mailing_street",
    label: "4.a. Street Number and Name (Mailing)",
    type: "text",
    section: "Part 4. Sponsor Information",
    condition: (d) => d.sponsor_is_us_citizen === "No",
  },
  {
    key: "sponsor_mailing_unit_type",
    pdfKey: "sponsor_mailing_unit_type",
    label: "4.b. Unit (Mailing)",
    type: "radio",
    section: "Part 4. Sponsor Information",
    options: [
      { label: "Apt.", value: "Apt", pdfKey: "sponsor_mailing_unit_apt" },
      { label: "Ste.", value: "Ste", pdfKey: "sponsor_mailing_unit_ste" },
      { label: "Flr.", value: "Flr", pdfKey: "sponsor_mailing_unit_flr" },
    ],
    condition: (d) => d.sponsor_is_us_citizen === "No",
  },
  {
    key: "sponsor_mailing_unit_number",
    pdfKey: "sponsor_mailing_unit_number",
    label: "4.c. Apt./Ste./Flr. Number (Mailing)",
    type: "text",
    section: "Part 4. Sponsor Information",
    condition: (d) => d.sponsor_is_us_citizen === "No",

  },
  {
    key: "sponsor_mailing_city",
    pdfKey: "sponsor_mailing_city",
    label: "4.d. City or Town (Mailing)",
    type: "text",
    section: "Part 4. Sponsor Information",
    condition: (d) => d.sponsor_is_us_citizen === "No",

  },
  {
    key: "sponsor_mailing_state",
    pdfKey: "sponsor_mailing_state",
    label: "4.e. State (Mailing)",
    type: "combo",
    section: "Part 4. Sponsor Information",
    condition: (d) => d.sponsor_is_us_citizen === "No",

  },
  {
    key: "sponsor_mailing_zip",
    pdfKey: "sponsor_mailing_zip",
    label: "4.f. ZIP Code (Mailing)",
    type: "text",
    section: "Part 4. Sponsor Information",
    maxLength: 5,
    condition: (d) => d.sponsor_is_us_citizen === "No",

  },
  {
    key: "sponsor_mailing_province",
    pdfKey: "sponsor_mailing_province",
    label: "4.g. Province (Mailing)",
    type: "text",
    section: "Part 4. Sponsor Information",
    condition: (d) => d.sponsor_is_us_citizen === "No",

  },
  {
    key: "sponsor_mailing_postal_code",
    pdfKey: "sponsor_mailing_postal_code",
    label: "4.h. Postal Code (Mailing)",
    type: "text",
    section: "Part 4. Sponsor Information",
    condition: (d) => d.sponsor_is_us_citizen === "No",

  },
  {
    key: "sponsor_mailing_country",
    pdfKey: "sponsor_mailing_country",
    label: "4.i. Country (Mailing)",
    type: "text",
    section: "Part 4. Sponsor Information",
    condition: (d) => d.sponsor_is_us_citizen === "No",

  },

  // Other Info
  {
    key: "sponsor_domicile_country",
    pdfKey: "sponsor_domicile_country",
    label: "5. Country of Domicile",
    type: "text",
    section: "Part 4. Sponsor Information",
  },
  {
    key: "sponsor_dob",
    pdfKey: "sponsor_dob",
    label: "6. Date of Birth (mm/dd/yyyy)",
    type: "date",
    section: "Part 4. Sponsor Information",
    placeholder: "MM/DD/YYYY",
    maxLength: 10,
  },
  {
    key: "sponsor_city_of_birth",
    pdfKey: "sponsor_city_of_birth",
    label: "7. Country of Birth",
    type: "text",
    section: "Part 4. Sponsor Information",
  },
  {
    key: "sponsor_ssn",
    pdfKey: "sponsor_ssn",
    label: "8. U.S. Social Security Number (Required)",
    type: "text",
    section: "Part 4. Sponsor Information",
    maxLength: 9,
  },

  // Citizenship Status
  {
    key: "sponsor_citizenship",
    pdfKey: "sponsor_citizenship",
    label: "9. Immigration Status:",
    type: "radio",
    section: "Part 4. Sponsor Information",
    options: [
      { label: "U.S. Citizen", value: "us_citizen", pdfKey: "sponsor_citizenship_us" },
      { label: "U.S. National", value: "us_national", pdfKey: "sponsor_citizenship_national" },
      { label: "Lawful Permanent Resident", value: "lpr", pdfKey: "sponsor_citizenship_lpr" },
    ],
  },

  {
    key: "sponsor_alien_number",
    pdfKey: "sponsor_alien_number",
    label: "10. Alien Registration Number (A-Number) (if any)",
    type: "text",
    section: "Part 4. Sponsor Information",
    maxLength: 9,
  },
  {
    key: "sponsor_uscis_account",
    pdfKey: "sponsor_uscis_account",
    label: "11. USCIS Online Account Number (if any)",
    type: "text",
    section: "Part 4. Sponsor Information",
    maxLength: 12,
  },

  {
    key: "sponsor_military_active",
    pdfKey: "sponsor_military_active",
    label: "12. I am currently on active duty in the U.S. Armed Forces or U.S. Coast Guard.",
    type: "radio",
    section: "Part 4. Sponsor Information",
    options: [
      { label: "Yes", value: "Yes", pdfKey: "sponsor_military_active_yes" },
      { label: "No", value: "No", pdfKey: "sponsor_military_active_no" },
    ],
  },

  // ============================================
  // PART 3. Information About the Principal Immigrant
  // ============================================
  {
    key: "",
    pdfKey: "",
    label: "1. Principal Immigrant's Full Legal Name (Do not provide a nickname)",
    type: "hidden",
    section: "Part 3. Information About the Principal Immigrant",
  },
  {
    key: "immigrant_family_name",
    pdfKey: "immigrant_family_name",
    label: "1.a. Family Name (Last Name)",
    type: "text",
    section: "Part 3. Information About the Principal Immigrant",
    required: true,
  },
  {
    key: "immigrant_given_name",
    pdfKey: "immigrant_given_name",
    label: "1.b. Given Name (First Name)",
    type: "text",
    section: "Part 3. Information About the Principal Immigrant",
    required: true,
  },
  {
    key: "immigrant_middle_name",
    pdfKey: "immigrant_middle_name",
    label: "1.c. Middle Name (if applicable)",
    type: "text",
    section: "Part 3. Information About the Principal Immigrant",
  },

  // Immigrant Address
  {
    key: "",
    pdfKey: "",
    label: "2. Current Mailing Address",
    type: "hidden",
    section: "Part 3. Information About the Principal Immigrant",
  },
  {
    key: "immigrant_in_care_of",
    pdfKey: "immigrant_in_care_of",
    label: "2.a. In Care Of Name (if any)",
    type: "text",
    section: "Part 3. Information About the Principal Immigrant",
  },
  {
    key: "immigrant_street",
    pdfKey: "immigrant_street",
    label: "2.b. Street Number and Name",
    type: "text",
    section: "Part 3. Information About the Principal Immigrant",
  },
  {
    key: "immigrant_unit_type",
    pdfKey: "immigrant_unit_type",
    label: "2.c. Unit",
    type: "radio",
    section: "Part 3. Information About the Principal Immigrant",
    options: [
      { label: "Apt.", value: "Apt", pdfKey: "immigrant_unit_apt" },
      { label: "Ste.", value: "Ste", pdfKey: "immigrant_unit_ste" },
      { label: "Flr.", value: "Flr", pdfKey: "immigrant_unit_flr" },
    ],
  },
  {
    key: "immigrant_unit_number",
    pdfKey: "immigrant_unit_number",
    label: "2.d. Apt./Ste./Flr. Number",
    type: "text",
    section: "Part 3. Information About the Principal Immigrant",
  },
  {
    key: "immigrant_city",
    pdfKey: "immigrant_city",
    label: "2.e. City or Town",
    type: "text",
    section: "Part 3. Information About the Principal Immigrant",
  },
  {
    key: "immigrant_state",
    pdfKey: "immigrant_state",
    label: "2.f. State",
    type: "combo",
    section: "Part 3. Information About the Principal Immigrant",
  },
  {
    key: "immigrant_zip",
    pdfKey: "immigrant_zip",
    label: "2.g. ZIP Code",
    type: "text",
    section: "Part 3. Information About the Principal Immigrant",
    maxLength: 5,
  },
  {
    key: "immigrant_province",
    pdfKey: "immigrant_province",
    label: "2.h. Province",
    type: "text",
    section: "Part 3. Information About the Principal Immigrant",
  },
  {
    key: "immigrant_postal_code",
    pdfKey: "immigrant_postal_code",
    label: "2.i. Postal Code",
    type: "text",
    section: "Part 3. Information About the Principal Immigrant",
  },
  {
    key: "immigrant_country",
    pdfKey: "immigrant_country",
    label: "2.j. Country",
    type: "text",
    section: "Part 3. Information About the Principal Immigrant",
  },

  {
    key: "",
    pdfKey: "",
    label: "Other Information",
    type: "hidden",
    section: "Part 3. Information About the Principal Immigrant",
  },
  {
    key: "immigrant_country_citizenship",
    pdfKey: "immigrant_country_citizenship",
    label: "3. Country of Citizenship or Nationality",
    type: "text",
    section: "Part 3. Information About the Principal Immigrant",
  },
  {
    key: "immigrant_dob",
    pdfKey: "immigrant_dob",
    label: "4. Date of Birth",
    type: "date",
    section: "Part 3. Information About the Principal Immigrant",
    placeholder: "MM/DD/YYYY",
    maxLength: 10,
  },
  {
    key: "immigrant_alien_number",
    pdfKey: "immigrant_alien_number",
    label: "5. Alien Registration Number (A-Number) (if any)",
    type: "text",
    section: "Part 3. Information About the Principal Immigrant",
    maxLength: 9,
  },
  {
    key: "immigrant_uscis_account",
    pdfKey: "immigrant_uscis_account",
    label: "6. USCIS Online Account Number (if any)",
    type: "text",
    section: "Part 3. Information About the Principal Immigrant",
    maxLength: 12,
  },
  {
    key: "immigrant_daytime_phone",
    pdfKey: "immigrant_daytime_phone",
    label: "7. Daytime Telephone Number",
    type: "text",
    section: "Part 3. Information About the Principal Immigrant",
  },

  // ============================================
  // PART 4. Household Size
  // ============================================
  // {
  //   key: "",
  //   pdfKey: "",
  //   label: " Information About the Immigrants You Are Sponsoring",
  //   type: "hidden",
  //   section: "Part 4. Information About the Immigrants You Are Sponsoring",
  // },
  {
    key: "household_sponsoring_self",
    pdfKey: "household_sponsoring_self",
    label: "1.  I am sponsoring the principal immigrant named in Part 3",
    type: "radio",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
    options: [
      { label: "Yes", value: "Yes", pdfKey: "household_sponsoring_self_yes" },
      { label: "No, I am sponsoring family members in Part 4. as the second joint sponsor or I am sponsoring family members who are immigrating more than six months after the principal immigrant.", value: "No", pdfKey: "household_sponsoring_self_no" },
    ],
  },
  {
    key: "household_sponsoring_family",
    pdfKey: "household_sponsoring_family",
    label: "2. I am sponsoring the following family members immigrating at the same time or within six months of the principal immigrant named in Part 3. (List family members in Item Numbers 4. - 7. Do not include any relative listed on a separate visa petition.)",
    type: "radio",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
    options: [
      { label: "Yes", value: "Yes", pdfKey: "household_sponsoring_family_yes" },
    ],
  },
  {
    key: "household_sponsoring_family_list",
    pdfKey: "household_sponsoring_family_list",
    label: "3. I am sponsoring the following family members who are immigrating more than six months after the principal immigrant.   (List family members in Item Numbers  4. - 7.)",
    type: "radio",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
    options: [
      { label: "Yes", value: "Yes", pdfKey: "household_sponsoring_family_no" },
    ],
  },

  // Repeatable Household Members (You can handle dynamically in UI)
  // For now, static first 3 as per PDF


  // Family Member 1
  {
    key: "",
    pdfKey: "",
    label: "Family Member 1",
    type: "hidden",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member1_family_name",
    pdfKey: "household_member1_family_name",
    label: "Family Name",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member1_given_name",
    pdfKey: "household_member1_given_name",
    label: "Given Name",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member1_middle_name",
    pdfKey: "household_member1_middle_name",
    label: "Middle Name",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member1_relationship",
    pdfKey: "household_member1_relationship",
    label: "Relationship",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member1_alien_number",
    pdfKey: "household_member1_alien_number",
    label: "Alien Number",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
    maxLength: 9,

  },
  {
    key: "household_member1_dob",
    pdfKey: "household_member1_dob",
    label: "Date of Birth",
    type: "date",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
    placeholder: "MM/DD/YYYY",
    maxLength: 10,
  },
  {
    key: "household_member1_uscis_account",
    pdfKey: "household_member1_uscis_account",
    label: "USCIS Online Account Number",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
    maxLength: 12,
  },

  // Family Member 2
  {
    key: "",
    pdfKey: "",
    label: "Family Member 2",
    type: "hidden",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member2_family_name",
    pdfKey: "household_member2_family_name",
    label: "Family Name",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member2_given_name",
    pdfKey: "household_member2_given_name",
    label: "Given Name",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member2_middle_name",
    pdfKey: "household_member2_middle_name",
    label: "Middle Name",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member2_relationship",
    pdfKey: "household_member2_relationship",
    label: "Relationship",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member2_alien_number",
    pdfKey: "household_member2_alien_number",
    label: "Alien Number",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
    maxLength: 9,

  },
  {
    key: "household_member2_dob",
    pdfKey: "household_member2_dob",
    label: "Date of Birth",
    type: "date",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
    placeholder: "MM/DD/YYYY",
    maxLength: 10,
  },
  {
    key: "household_member2_uscis_account",
    pdfKey: "household_member2_uscis_account",
    label: "USCIS Online Account Number",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
    maxLength: 12,
  },

  // Family Member 3
  {
    key: "",
    pdfKey: "",
    label: "Family Member 3",
    type: "hidden",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member3_family_name",
    pdfKey: "household_member3_family_name",
    label: "Family Name",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member3_given_name",
    pdfKey: "household_member3_given_name",
    label: "Given Name",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member3_middle_name",
    pdfKey: "household_member3_middle_name",
    label: "Middle Name",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member3_relationship",
    pdfKey: "household_member3_relationship",
    label: "Relationship",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member3_alien_number",
    pdfKey: "household_member3_alien_number",
    label: "Alien Number",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
    maxLength: 9,

  },
  {
    key: "household_member3_dob",
    pdfKey: "household_member3_dob",
    label: "Date of Birth",
    type: "date",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
    placeholder: "MM/DD/YYYY",
    maxLength: 10,
  },
  {
    key: "household_member3_uscis_account",
    pdfKey: "household_member3_uscis_account",
    label: "USCIS Online Account Number",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
    maxLength: 12,
  },

  // Family Member 4
  {
    key: "",
    pdfKey: "",
    label: "Family Member 4",
    type: "hidden",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member4_family_name",
    pdfKey: "household_member4_family_name",
    label: "Family Name",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member4_given_name",
    pdfKey: "household_member4_given_name",
    label: "Given Name",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member4_middle_name",
    pdfKey: "household_member4_middle_name",
    label: "Middle Name",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member4_relationship",
    pdfKey: "household_member4_relationship",
    label: "Relationship",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },
  {
    key: "household_member4_alien_number",
    pdfKey: "household_member4_alien_number",
    label: "Alien Number",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
    maxLength: 9,
  },
  {
    key: "household_member4_dob",
    pdfKey: "household_member4_dob",
    label: "Date of Birth",
    type: "date",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
    placeholder: "MM/DD/YYYY",
    maxLength: 10,
  },
  {
    key: "household_member4_uscis_account",
    pdfKey: "household_member4_uscis_account",
    label: "USCIS Online Account Number",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
    maxLength: 12,
  },
  {
    key: "household_total_immigrants",
    pdfKey: "household_total_immigrants",
    label: "Total Number of Immigrants",
    type: "text",
    section: "Part 4. Information About the Immigrants You Are Sponsoring",
  },

  // Part 5 Sponsor Household Size
  {
    key: "",
    pdfKey: "",
    label: "NOTE:  Do not count any member of your household more than once.",
    type: "hidden",
    section: "Part 5. Sponsor's Household Size",
  },
  {
    key: "",
    pdfKey: "",
    label: "Persons you are sponsoring in this affidavit:",
    type: "hidden",
    section: "Part 5. Sponsor's Household Size",
  },
  {
    key: "hsize_total_immigrants",
    pdfKey: "hsize_total_immigrants",
    label: "1. Enter the total number of immigrants you are sponsoring on this affidavit which includes the principal immigrant listed in Part 3., any immigrants listed in Part 4., Item Numbers 4. - 7. and, any additional sponsored immigrants you listed in Part 11. Additional Information.  Do not count the principal immigrant if you are only sponsoring family members entering more than six months after the principal immigrant. ",
    type: "text",
    section: "Part 5. Sponsor's Household Size",
  },
  {
    key: "",
    pdfKey: "",
    label: "Persons NOT sponsored in this affidavit:",
    type: "hidden",
    section: "Part 5. Sponsor's Household Size",
  },
  {
    key: "hsize_yourself",
    pdfKey: "hsize_yourself",
    label: "2. Yourself.",
    type: "text",
    section: "Part 5. Sponsor's Household Size",
    value: '1',
  },
  {
    key: "hsize_married",
    pdfKey: "hsize_married",
    label: "3. If you are currently married, enter `1` for your spouse.  (NOTE: Enter “0” if you already counted your spouse in Item Number 1.)",
    type: "text",
    section: "Part 5. Sponsor's Household Size",
  },
  {
    key: "hsize_dependent_children",
    pdfKey: "hsize_dependent_children",
    label: "4. If you have dependent children, enter the number here.  (NOTE: Enter “0” if you already counted your dependent children in Item Number 1.)",
    type: "text",
    section: "Part 5. Sponsor's Household Size",
  },
  {
    key: "hsize_other_dependents",
    pdfKey: "hsize_other_dependents",
    label: "5. If you have any other dependents, enter the number here.  (NOTE: Enter “0” if you already counted your other dependents in Item Number 1.)",
    type: "text",
    section: "Part 5. Sponsor's Household Size",
  },
  {
    key: "hsize_sponsors",
    pdfKey: "hsize_sponsors",
    label: "6. If you have sponsored any other persons on Form I-864 or Form I-864EZ who are now lawful permanent residents and you are still obligated to support, enter the number here.  (NOTE: Enter “0” if you already counted these persons in Item Number 1.)",
    type: "text",
    section: "Part 5. Sponsor's Household Size",
  },
  {
    key: "hsize_same_residence",
    pdfKey: "hsize_same_residence",
    label: "7. If you have siblings, parents, or adult children with the same principal residence who are combining their income with yours by submitting Form I-864A, enter the number here.  (NOTE: Enter “0” if you already counted these persons in Item Number 1.)",
    type: "text",
    section: "Part 5. Sponsor's Household Size",
  },
  {
    key: "hsize_total",
    pdfKey: "hsize_total",
    label: "8. Add together Part 5., Item Numbers 1. - 7. and enter the number here. ",
    type: "text",
    section: "Part 5. Sponsor's Household Size",
  },

  // Part 6 Employment and Income
  {
    key: "",
    pdfKey: "",
    label: "I am currently:",
    type: "hidden",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "emp_employed_chk",
    pdfKey: "emp_employed_chk",
    label: "1. Employed as a/an",
    type: "checkbox",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "emp_employer_name",
    pdfKey: "emp_employer_name",
    label: "2. Name of Employer 1",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "emp_employer_name_2",
    pdfKey: "emp_employer_name_2",
    label: "3. Name of Employer 2 (if applicable)",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  // {
  //   key: "emp_employer_name_3",
  //   pdfKey: "emp_employer_name_3",
  //   label: "4. Name of Employer 3",
  //   type: "text",
  //   section: "Part 6. Sponsor's Employment and Income",
  // },
  {
    key: "emp_self_employed_chk",
    pdfKey: "emp_self_employed_chk",
    label: "4. Self-employed as a/an",
    type: "checkbox",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "emp_self_employed_as",
    pdfKey: "emp_self_employed_as",
    label: "4.a. Self-Employed Occupation",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
    condition: (d) => !!d.emp_self_employed_chk,
  },
  {
    key: "emp_retired_chk",
    pdfKey: "emp_retired_chk",
    label: "5. I am retired",
    type: "checkbox",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "emp_retired_date",
    pdfKey: "emp_retired_date",
    label: "5.a. Retired Since",
    type: "date",
    section: "Part 6. Sponsor's Employment and Income",
    placeholder: "MM/DD/YYYY",
    maxLength: 10,
    condition: (d) => !!d.emp_retired_chk,
  },
  {
    key: "emp_unemployed_chk",
    pdfKey: "emp_unemployed_chk",
    label: "6. I am unemployed",
    type: "checkbox",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "emp_unemployed_date",
    pdfKey: "emp_unemployed_date",
    label: "6.a. Date Unemployed",
    type: "date",
    section: "Part 6. Sponsor's Employment and Income",
    placeholder: "MM/DD/YYYY",
    maxLength: 10,
    condition: (d) => !!d.emp_unemployed_chk,
  },
  {
    key: "emp_current_annual_income",
    pdfKey: "emp_current_annual_income",
    label: "7. Current Individual Annual Income ($)",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  // Household Income Details
  {
    key: "",
    pdfKey: "",
    label: "Income you are using from any other person who was counted in your household size, including, in certain conditions, the intending immigrant. Please indicate name, relationship, and income.",
    type: "hidden",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "",
    pdfKey: "",
    label: "8. Person 1",
    type: "select",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "hh_income1_name",
    pdfKey: "hh_income1_name",
    label: "Name",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "hh_income1_relationship",
    pdfKey: "hh_income1_relationship",
    label: "Relationship",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "hh_income1_amount",
    pdfKey: "hh_income1_amount",
    label: "Current Income",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "",
    pdfKey: "",
    label: "9. Person 2",
    type: "hidden",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "hh_income2_name",
    pdfKey: "hh_income2_name",
    label: "Name",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "hh_income2_relationship",
    pdfKey: "hh_income2_relationship",
    label: "Relationship",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "hh_income2_amount",
    pdfKey: "hh_income2_amount",
    label: "Current Income",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "",
    pdfKey: "",
    label: "10. Person 3",
    type: "hidden",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "hh_income3_name",
    pdfKey: "hh_income3_name",
    label: "Name",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "hh_income3_relationship",
    pdfKey: "hh_income3_relationship",
    label: "Relationship",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "hh_income3_amount",
    pdfKey: "hh_income3_amount",
    label: "Current Income",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "",
    pdfKey: "",
    label: "11. Person 4",
    type: "hidden",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "hh_income4_name",
    pdfKey: "hh_income4_name",
    label: "Name",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "hh_income4_relationship",
    pdfKey: "hh_income4_relationship",
    label: "Relationship",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "hh_income4_amount",
    pdfKey: "hh_income4_amount",
    label: "Current Income",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "",
    pdfKey: "",
    label: "Remarks",
    type: "hidden",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "hh_total_household_income",
    pdfKey: "hh_total_household_income",
    label: "12. My Current Annual Household Income (Total all lines from Part 6. Item Numbers 7. - 11. the total will be compared to Federal Poverty Guidelines on Form I-864P.)",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "hh_people_listed",
    pdfKey: "hh_people_listed",
    label: "13. The people listed in Item Numbers 8. - 11. have completed Form I-864A.  I am filing along with this affidavit all necessary Form I-864As completed by these people.",
    type: "radio",
    section: "Part 6. Sponsor's Employment and Income",
    options: [
      { label: "Yes", value: "Yes", pdfKey: "hh_people_listed" },
    ]
  },
  {
    key: "hh_intending_immigrant_check",
    pdfKey: "hh_intending_immigrant_check",
    label: "14. One or more of the people listed in Item Numbers 8. - 11. do not need to complete Form I-864A because he or she is the intending immigrant and has no accompanying dependents.",
    type: "radio",
    section: "Part 6. Sponsor's Employment and Income",
    options: [
      { label: "Yes", value: "Yes", pdfKey: "hh_intending_immigrant_check" },

    ]
  },

  {
    key: "hh_intending_immigrant_dependents",
    pdfKey: "hh_intending_immigrant_dependents",
    label: "14.a. List the peoples",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },

  {
    key: "tax_filed_3years_chk",
    pdfKey: "tax_filed_3years_chk",
    label: "15. Have you filed a Federal income tax return for each of the three most recent tax years?",
    type: "radio",
    section: "Part 6. Sponsor's Employment and Income",
    options: [
      { label: "Yes", value: "Yes", pdfKey: "tax_filed_3years_chk_yes" },
      { label: "No", value: "No", pdfKey: "tax_filed_3years_chk_no" },
    ]
  },
  {
    key: "tax_year_1",
    pdfKey: "tax_year_1",
    label: "Most Recent Tax Year",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "tax_income_1",
    pdfKey: "tax_income_1",
    label: "Most Recent Tax Year Total Income",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "tax_year_2",
    pdfKey: "tax_year_2",
    label: "2nd Recent Tax Year",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "tax_income_2",
    pdfKey: "tax_income_2",
    label: "2nd Recent Tax Year Total Income",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "tax_year_3",
    pdfKey: "tax_year_3",
    label: "3rd Recent Tax Year",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "tax_income_3",
    pdfKey: "tax_income_3",
    label: "3rd Recent Tax Year Total Income",
    type: "text",
    section: "Part 6. Sponsor's Employment and Income",
  },
  {
    key: "tax_not_required_chk",
    pdfKey: "tax_not_required_chk",
    label: "I was not required to file a Federal income tax return",
    type: "checkbox",
    section: "Part 6. Sponsor's Employment and Income",
  },

  // Part 7 Assets
  {
    key: "",
    pdfKey: "",
    label: "If your income, or the total income for you and your household, from Part 6., Item Numbers 12. or 16. exceeds the Federal Poverty Guidelines for your household size, YOU ARE NOT REQUIRED to complete this Part 7.  Skip to Part 8.",
    type: "hidden",
    section: "Part 7. Use of Assets to Supplement Income (if Applicable)",
  },
  {
    key: "",
    pdfKey: "",
    label: "Your Assets (if applicable)",
    type: "hidden",
    section: "Part 7. Use of Assets to Supplement Income (if Applicable)",
  },
  {
    key: "asset_sponsor_balance",
    pdfKey: "asset_sponsor_balance",
    label: "1. Enter the balance of all cash, savings, and checking accounts.",
    type: "text",
    section: "Part 7. Use of Assets to Supplement Income (if Applicable)",
  },
  {
    key: "asset_sponsor_total",
    pdfKey: "asset_sponsor_total",
    label: "2. Enter the net cash value of real-estate holdings.  (Net value means assessed value minus mortgage debt.) $ ",
    type: "text",
    section: "Part 7. Use of Assets to Supplement Income (if Applicable)",
  },
  {
    key: "asset_sponsor_real_estate",
    pdfKey: "asset_sponsor_real_estate",
    label: "3. Enter the net cash value of all stocks, bonds, certificates of deposit, and any other assets not already included in Item Number 1. or Item Number 2. ",
    type: "text",
    section: "Part 7. Use of Assets to Supplement Income (if Applicable)",
  },
  {
    key: "asset_sponsor_stocks",
    pdfKey: "asset_sponsor_stocks",
    label: "4. Add together Item Numbers 1. - 3. and enter the number here.",
    type: "text",
    section: "Part 7. Use of Assets to Supplement Income (if Applicable)",
  },
  {
    key: "",
    pdfKey: "",
    label: "Assets of your household members (if applicable)",
    type: "hidden",
    section: "Part 7. Use of Assets to Supplement Income (if Applicable)",
  },
  {
    key: "",
    pdfKey: "",
    label: "Your household members who are combining their income with yours, report their assets on Form I-864A Part 4., in Item Number 6.",
    type: "hidden",
    section: "Part 7. Use of Assets to Supplement Income (if Applicable)",
  },
  {
    key: "asset_hh_total",
    pdfKey: "asset_hh_total",
    label: "5. Add together the household members' assets reported on all the Form I-864A Part 4., Item Number 6. and enter the number here.",
    type: "text",
    section: "Part 7. Use of Assets to Supplement Income (if Applicable)",
  },
  {
    key: "",
    pdfKey: "",
    label: "Assets of the principal sponsored immigrant (if applicable).",
    type: "hidden",
    section: "Part 7. Use of Assets to Supplement Income (if Applicable)",
  },
  {
    key: "",
    pdfKey: "",
    label: "The principal sponsored immigrant is the person listed in Part 3., Item Number 1.  Only include the assets if the principal immigrant is being sponsored by this affidavit of support.",
    type: "hidden",
    section: "Part 7. Use of Assets to Supplement Income (if Applicable)",
  },
  {
    key: "asset_pig_balance",
    pdfKey: "asset_pig_balance",
    label: "6. Enter the balance of the principal immigrant's savings and checking accounts.",
    type: "text",
    section: "Part 7. Use of Assets to Supplement Income (if Applicable)",
  },
  {
    key: "asset_pig_real_estate",
    pdfKey: "asset_pig_real_estate",
    label: "7. Enter the net cash value of all the principal immigrant's real estate holdings.  (Net value means investment value minus mortgage debt.)",
    type: "text",
    section: "Part 7. Use of Assets to Supplement Income (if Applicable)",
  },
  {
    key: "asset_pig_stocks",
    pdfKey: "asset_pig_stocks",
    label: "8. Enter the current cash value of the principal immigrant's stocks, bonds, certificates of deposit, and other assets not included in Item Number 6. or Item Number 7.",
    type: "text",
    section: "Part 7. Use of Assets to Supplement Income (if Applicable)",
  },
  {
    key: "asset_pig_total",
    pdfKey: "asset_pig_total",
    label: "9. Add together Item Numbers 6. - 8. and enter the number here.",
    type: "text",
    section: "Part 7. Use of Assets to Supplement Income (if Applicable)",
  },
  {
    key: "",
    pdfKey: "",
    label: "Total Value of Assets",
    type: "hidden",
    section: "Part 7. Use of Assets to Supplement Income (if Applicable)",
  },
  {
    key: "asset_total_value",
    pdfKey: "asset_total_value",
    label: "10. Add together Item Numbers 4., 5., and 9. and enter the number here.",
    type: "text",
    section: "Part 7. Use of Assets to Supplement Income (if Applicable)",
  },

  // Part 8 Contract
  {
    key: "",
    pdfKey: "",
    label: "Sponsor's Statement",
    type: "hidden",
    section: "Part 8. Sponsor's Contract",
  },

  {
    key: "p8_can_read_english",
    pdfKey: "p8_can_read_english",
    label: "I can read and understand English, and I have read and understand every question and instruction on this affidavit and my answer to every question.",
    type: "checkbox",
    section: "Part 8. Sponsor's Contract",
    options: [
      { label: "Yes", value: "Yes", pdfKey: "p8_can_read_english" },
    ],
  },
  {
    key: "p8_interpreter_chk",
    pdfKey: "p8_interpreter_chk",
    label: "I used an interpreter",
    type: "checkbox",
    section: "Part 8. Sponsor's Contract",
    options: [
      { label: "Yes", value: "Yes", pdfKey: "p8_interpreter_chk" },
    ],
  },
  {
    key: "p8_language_used",
    pdfKey: "p8_language_used",
    label: "Language used",
    type: "text",
    section: "Part 8. Sponsor's Contract",
    condition: (d) => !!d.p8_interpreter_chk,
  },
  {
    key: "",
    pdfKey: "",
    label: "Sponsor's Contact Information",
    type: "hidden",
    section: "Part 8. Sponsor's Contract",
  },
  {
    key: "p8_sponsor_phone",
    pdfKey: "p8_sponsor_phone",
    label: "Sponsor's Daytime Phone",
    type: "text",
    section: "Part 8. Sponsor's Contract",
  },
  {
    key: "p8_sponsor_mobile",
    pdfKey: "p8_sponsor_mobile",
    label: "Sponsor's Mobile Telephone Number (if any)",
    type: "text",
    section: "Part 8. Sponsor's Contract",
  },
  {
    key: "p8_sponsor_email",
    pdfKey: "p8_sponsor_email",
    label: "Sponsor's Email",
    type: "text",
    section: "Part 8. Sponsor's Contract",
  },

  // preparer
  {
    key: "p8_preparer_chk",
    pdfKey: "p8_preparer_chk",
    label: "I used a preparer",
    type: "checkbox",
    section: "Part 8. Sponsor's Contract",
  },
  {
    key: "p8_preparer_name",
    pdfKey: "p8_preparer_name",
    label: "Preparer's Name",
    type: "text",
    section: "Part 8. Sponsor's Contract",
    condition: (d) => !!d.p8_preparer_chk,
  },

  {
    key: "p8_sponsor_signature",
    pdfKey: "p8_sponsor_signature",
    label: "Sponsor's Signature",
    type: "text",
    section: "Part 8. Sponsor's Contract",
  },
  {
    key: "p8_sponsor_sign_date",
    pdfKey: "p8_sponsor_sign_date",
    label: "Date of Signature",
    type: "date",
    section: "Part 8. Sponsor's Contract",
    placeholder: "MM/DD/YYYY",
    maxLength: 10,
  },

  // Part 9 Interpreter
  {
    key: "",
    pdfKey: "",
    label: "Interpreter's Full Name",
    type: "hidden",
    section: "Part 9. Interpreter",
  },
  {
    key: "p9_interp_given_name",
    pdfKey: "p9_interp_given_name",
    label: "Interpreter Given Name",
    type: "text",
    section: "Part 9. Interpreter",
  },
  {
    key: "p9_interp_family_name",
    pdfKey: "p9_interp_family_name",
    label: "Interpreter Family Name",
    type: "text",
    section: "Part 9. Interpreter",
  },
  {
    key: "p9_interp_business",
    pdfKey: "p9_interp_business",
    label: "Interpreter Business Name",
    type: "text",
    section: "Part 9. Interpreter",
  },
  {
    key: "",
    pdfKey: "",
    label: "Interpreter's Contact Information",
    type: "hidden",
    section: "Part 9. Interpreter",
  },
  {
    key: "p9_interp_language",
    pdfKey: "p9_interp_language",
    label: "Interpreter Language",
    type: "text",
    section: "Part 9. Interpreter",
  },

  {
    key: "p9_interp_phone",
    pdfKey: "p9_interp_phone",
    label: "Interpreter Phone",
    type: "text",
    section: "Part 9. Interpreter",
  },
  {
    key: "p9_interp_email",
    pdfKey: "p9_interp_email",
    label: "Interpreter Email",
    type: "text",
    section: "Part 9. Interpreter",
  },
  {
    key: "p9_interp_signature",
    pdfKey: "p9_interp_signature",
    label: "Interpreter Signature",
    type: "text",
    section: "Part 9. Interpreter",
  },
  {
    key: "p9_interp_sign_date",
    pdfKey: "p9_interp_sign_date",
    label: "Date of Signature (Interpreter)",
    type: "date",
    section: "Part 9. Interpreter",
    placeholder: "MM/DD/YYYY",
    maxLength: 10,
  },

  // Part 10 Preparer
  {
    key: "p10_prep_given_name",
    pdfKey: "p10_prep_given_name",
    label: "Preparer Given Name",
    type: "text",
    section: "Part 10. Preparer",
  },
  {
    key: "p10_prep_family_name",
    pdfKey: "p10_prep_family_name",
    label: "Preparer Family Name",
    type: "text",
    section: "Part 10. Preparer",
  },
  {
    key: "p10_prep_business",
    pdfKey: "p10_prep_business",
    label: "Preparer Business Name",
    type: "text",
    section: "Part 10. Preparer",
  },
  {
    key: "p10_prep_phone",
    pdfKey: "p10_prep_phone",
    label: "Preparer Phone",
    type: "text",
    section: "Part 10. Preparer",
  },
  {
    key: "p10_prep_fax",
    pdfKey: "p10_prep_fax",
    label: "Preparer Fax",
    type: "text",
    section: "Part 10. Preparer",
  },
  {
    key: "p10_prep_email",
    pdfKey: "p10_prep_email",
    label: "Preparer Email",
    type: "text",
    section: "Part 10. Preparer",
  },
  {
    key: "p10_prep_signature",
    pdfKey: "p10_prep_signature",
    label: "Preparer Signature",
    type: "text",
    section: "Part 10. Preparer",
  },
  {
    key: "p10_prep_sign_date",
    pdfKey: "p10_prep_sign_date",
    label: "Date of Signature (Preparer)",
    type: "date",
    section: "Part 10. Preparer",
    placeholder: "MM/DD/YYYY",
    maxLength: 10,
  },

  // Part 11 Additional Information
  {
    key: "p11_add_info_name_family",
    pdfKey: "p11_add_info_name_family",
    label: "Additional Info: Family Name",
    type: "text",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_name_given",
    pdfKey: "p11_add_info_name_given",
    label: "Additional Info: Given Name",
    type: "text",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_name_middle",
    pdfKey: "p11_add_info_name_middle",
    label: "Additional Info: Middle Name",
    type: "text",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_alien_number",
    pdfKey: "p11_add_info_alien_number",
    label: "Additional Info: Alien Number",
    type: "text",
    section: "Part 11. Additional Information",
    maxLength: 9,
  },
  {
    key: "p11_add_info_page1",
    pdfKey: "p11_add_info_page1",
    label: "Page Number",
    type: "text",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_part1",
    pdfKey: "p11_add_info_part1",
    label: "Part Number",
    type: "text",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_item1",
    pdfKey: "p11_add_info_item1",
    label: "Item Number",
    type: "text",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_desc1",
    pdfKey: "p11_add_info_desc1",
    label: "Additional Information 1",
    type: "textarea",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_page2",
    pdfKey: "p11_add_info_page2",
    label: "Page Number",
    type: "text",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_part2",
    pdfKey: "p11_add_info_part2",
    label: "Part Number",
    type: "text",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_item2",
    pdfKey: "p11_add_info_item2",
    label: "Item Number",
    type: "text",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_desc2",
    pdfKey: "p11_add_info_desc2",
    label: "Additional Information 2",
    type: "textarea",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_page3",
    pdfKey: "p11_add_info_page3",
    label: "Page Number",
    type: "text",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_part3",
    pdfKey: "p11_add_info_part3",
    label: "Part Number",
    type: "text",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_item3",
    pdfKey: "p11_add_info_item3",
    label: "Item Number",
    type: "text",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_desc3",
    pdfKey: "p11_add_info_desc3",
    label: "Additional Information 3",
    type: "textarea",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_page4",
    pdfKey: "p11_add_info_page4",
    label: "Page Number",
    type: "text",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_part4",
    pdfKey: "p11_add_info_part4",
    label: "Part Number",
    type: "text",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_item4",
    pdfKey: "p11_add_info_item4",
    label: "Item Number",
    type: "text",
    section: "Part 11. Additional Information",
  },
  {
    key: "p11_add_info_desc4",
    pdfKey: "p11_add_info_desc4",
    label: "Additional Information 4",
    type: "textarea",
    section: "Part 11. Additional Information",
  },
]

export const getInitialFormData = () => {
  const data: Record<string, string> = {};
  formFields.forEach((f) => (data[f.key] = ""));
  return data;
};

export const i864Config = {
  formId,
  formTitle,
  formSubtitle,
  formFields,
  getInitialFormData,
};

export default i864Config;