// Generated 148 fields for Form I-864A
import type { Field } from './types';

export const formId = 'i864a';
export const formTitle = 'Form I-864A';
export const formSubtitle = 'Contract Between Sponsor and Household Member';

export const formFields: Field[] = [
  // === Part 1: Household Member ===
  { key: 'pt1_l1a_FamilyName', pdfKey: 'pt1_l1a_familyname', label: 'Household Member\'s Family Name (Last Name)', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l1b_GivenName', pdfKey: 'pt1_l1b_givenname', label: 'Household Member\'s Given Name (First Name)', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l1c_MiddleName', pdfKey: 'pt1_l1c_middlename', label: 'Household Member\'s Middle Name', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l2_AptSteFlrNumber', pdfKey: 'pt1_l2_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l2_CityOrTown', pdfKey: 'pt1_l2_cityortown', label: 'City or Town', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l2_Country', pdfKey: 'pt1_l2_country', label: 'Country', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l2_InCareOfName', pdfKey: 'pt1_l2_incareofname', label: 'In Care of Name', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l2_PostalCode', pdfKey: 'pt1_l2_postalcode', label: 'Postal Code', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l2_Province', pdfKey: 'pt1_l2_province', label: 'Province', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l2_State', pdfKey: 'pt1_l2_state', label: 'State', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l2_StreetNumberName', pdfKey: 'pt1_l2_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l2_Unit', pdfKey: 'pt1_l2_unit', label: 'Unit', type: 'checkbox', section: 'Part 1: Household Member' },
  { key: 'pt1_l2_Unit_1', pdfKey: 'pt1_l2_unit_1', label: 'Unit (2)', type: 'checkbox', section: 'Part 1: Household Member' },
  { key: 'pt1_l2_Unit_2', pdfKey: 'pt1_l2_unit_2', label: 'Unit (3)', type: 'checkbox', section: 'Part 1: Household Member' },
  { key: 'pt1_l2_ZipCode', pdfKey: 'pt1_l2_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l3_CB', pdfKey: 'pt1_l3_cb', label: 'Part 1, Item 3', type: 'checkbox', section: 'Part 1: Household Member' },
  { key: 'pt1_l3_CB_1', pdfKey: 'pt1_l3_cb_1', label: 'Part 1, Item 3', type: 'checkbox', section: 'Part 1: Household Member' },
  { key: 'pt1_l4_AptSteFlrNumber', pdfKey: 'pt1_l4_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l4_CityOrTown', pdfKey: 'pt1_l4_cityortown', label: 'City or Town', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l4_Country', pdfKey: 'pt1_l4_country', label: 'Country', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l4_PostalCode', pdfKey: 'pt1_l4_postalcode', label: 'Postal Code', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l4_Province', pdfKey: 'pt1_l4_province', label: 'Province', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l4_State', pdfKey: 'pt1_l4_state', label: 'State', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l4_StreetNumberName', pdfKey: 'pt1_l4_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l4_Unit', pdfKey: 'pt1_l4_unit', label: 'Unit', type: 'checkbox', section: 'Part 1: Household Member' },
  { key: 'pt1_l4_Unit_1', pdfKey: 'pt1_l4_unit_1', label: 'Unit (2)', type: 'checkbox', section: 'Part 1: Household Member' },
  { key: 'pt1_l4_Unit_2', pdfKey: 'pt1_l4_unit_2', label: 'Unit (3)', type: 'checkbox', section: 'Part 1: Household Member' },
  { key: 'pt1_l4_ZipCode', pdfKey: 'pt1_l4_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l5_DateOfBirth', pdfKey: 'pt1_l5_dateofbirth', label: 'Household Member\'s Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 1: Household Member' },
  { key: 'pt1_l6_CountryofBirth', pdfKey: 'pt1_l6_countryofbirth', label: 'Countryof Birth', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l7_SSN', pdfKey: 'pt1_l7_ssn', label: 'Household Member\'s Social Security Number', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l8_AlienNumber', pdfKey: 'pt1_l8_aliennumber', label: 'Household Member\'s A-Number', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l9_USCISOnlineAcctNumber', pdfKey: 'pt1_l9_uscisonlineacctnumber', label: 'USCIS Online Account Number', type: 'text', section: 'Part 1: Household Member' },
  { key: 'pt1_l3e_AlienNumber', pdfKey: 'pt1_l3e_aliennumber', label: 'A-Number', type: 'text', section: 'Part 1: Household Member' },
  // === Part 2: Relationship to Sponsor ===
  { key: 'pt2_l0_Line1-3_Checkbox', pdfKey: 'pt2_l0_line1-3_checkbox', label: 'I am the intending immigrant and also the sponsor\'s spouse.', type: 'checkbox', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l0_Line1-3_Checkbox_1', pdfKey: 'pt2_l0_line1-3_checkbox_1', label: 'I am the intending immigrant and also a member of the sponsor\'s household.', type: 'checkbox', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l0_Line1-3_Checkbox_2', pdfKey: 'pt2_l0_line1-3_checkbox_2', label: 'I am not the intending immigrant. I am the sponsor\'s household member.', type: 'checkbox', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l3_A_Other', pdfKey: 'pt2_l3_a_other', label: 'Specify \'Other\' Relationship', type: 'text', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l3_A_Relationship', pdfKey: 'pt2_l3_a_relationship', label: 'Relationship: Spouse', type: 'checkbox', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l3_A_Relationship_1', pdfKey: 'pt2_l3_a_relationship_1', label: 'Relationship: Son or Daughter (at least 18 years old)', type: 'checkbox', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l3_A_Relationship_2', pdfKey: 'pt2_l3_a_relationship_2', label: 'Relationship: Parent', type: 'checkbox', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l3_A_Relationship_3', pdfKey: 'pt2_l3_a_relationship_3', label: 'Relationship: Brother or Sister', type: 'checkbox', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l3_A_Relationship_4', pdfKey: 'pt2_l3_a_relationship_4', label: 'Relationship: Other Dependent', type: 'checkbox', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l3_DaytimePhone', pdfKey: 'pt2_l3_daytimephone', label: 'Daytime Phone', type: 'text', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l4_Mobilephone', pdfKey: 'pt2_l4_mobilephone', label: 'Mobilephone', type: 'text', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l4a_FamilyName', pdfKey: 'pt2_l4a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l4a_GivenName', pdfKey: 'pt2_l4a_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l4a_MiddleName', pdfKey: 'pt2_l4a_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l5_EmailAddress', pdfKey: 'pt2_l5_emailaddress', label: 'Email Address', type: 'text', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l5_SSN', pdfKey: 'pt2_l5_ssn', label: 'Social Security Number', type: 'text', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l6_ApplicantSignature', pdfKey: 'pt2_l6_applicantsignature', label: 'Applicant Signature', type: 'text', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l6_DateofSignature', pdfKey: 'pt2_l6_dateofsignature', label: 'Dateof Signature', type: 'date', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l6_USCISELISAcctNumber', pdfKey: 'pt2_l6_usciselisacctnumber', label: 'Usciselisacct Number', type: 'text', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l8_DateOfBirth', pdfKey: 'pt2_l8_dateofbirth', label: 'Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l6_ApplicantSignature_1', pdfKey: 'pt2_l6_applicantsignature_1', label: 'Applicant Signature (2)', type: 'text', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l6_DateofSignature_1', pdfKey: 'pt2_l6_dateofsignature_1', label: 'Dateof Signature (2)', type: 'date', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l6_ApplicantSignature_2', pdfKey: 'pt2_l6_applicantsignature_2', label: 'Applicant Signature (3)', type: 'text', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l6_ApplicantSignature_3', pdfKey: 'pt2_l6_applicantsignature_3', label: 'Applicant Signature (4)', type: 'text', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l6_DateofSignature_2', pdfKey: 'pt2_l6_dateofsignature_2', label: 'Dateof Signature (3)', type: 'date', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l6_DateofSignature_3', pdfKey: 'pt2_l6_dateofsignature_3', label: 'Dateof Signature (4)', type: 'date', section: 'Part 2: Relationship to Sponsor' },
  // === Part 3: Employment and Income ===
  { key: 'pt3_l1_Employment', pdfKey: 'pt3_l1_employment', label: 'Employed as a/an', type: 'checkbox', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l1a_Employed', pdfKey: 'pt3_l1a_employed', label: 'Name of Employer Number 1', type: 'text', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l2_CurrentIncome', pdfKey: 'pt3_l2_currentincome', label: 'Current Income', type: 'text', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l2_Employed', pdfKey: 'pt3_l2_employed', label: 'Employed', type: 'text', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l3_Employed', pdfKey: 'pt3_l3_employed', label: 'Employed', type: 'text', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l4_Employment', pdfKey: 'pt3_l4_employment', label: 'Employment', type: 'checkbox', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l4a_SelfEmployedDescription', pdfKey: 'pt3_l4a_selfemployeddescription', label: 'Self Employed Description', type: 'text', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l5_Employment', pdfKey: 'pt3_l5_employment', label: 'Employment', type: 'checkbox', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l5a_EmployedDate', pdfKey: 'pt3_l5a_employeddate', label: 'Employed Date', type: 'date', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l6_Employment', pdfKey: 'pt3_l6_employment', label: 'Employment', type: 'checkbox', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l6a_EmployedDate', pdfKey: 'pt3_l6a_employeddate', label: 'Employed Date', type: 'date', section: 'Part 3: Employment and Income' },
  // === Part 4: Tax Info and Assets ===
  { key: 'pt4_l1_CB', pdfKey: 'pt4_l1_cb', label: 'Part 4, Item 1', type: 'checkbox', section: 'Part 4: Tax Info and Assets' },
  { key: 'pt4_l1_CB_1', pdfKey: 'pt4_l1_cb_1', label: 'Part 4, Item 1', type: 'checkbox', section: 'Part 4: Tax Info and Assets' },
  { key: 'pt4_l2a_TaxYear', pdfKey: 'pt4_l2a_taxyear', label: 'Tax Year', type: 'text', section: 'Part 4: Tax Info and Assets' },
  { key: 'pt4_l2a_TotalIncome', pdfKey: 'pt4_l2a_totalincome', label: 'Total Income', type: 'text', section: 'Part 4: Tax Info and Assets' },
  { key: 'pt4_l2b_TaxYear', pdfKey: 'pt4_l2b_taxyear', label: 'Tax Year', type: 'text', section: 'Part 4: Tax Info and Assets' },
  { key: 'pt4_l2b_TotalIncome', pdfKey: 'pt4_l2b_totalincome', label: 'Total Income', type: 'text', section: 'Part 4: Tax Info and Assets' },
  { key: 'pt4_l2c_TaxYear', pdfKey: 'pt4_l2c_taxyear', label: 'Tax Year', type: 'text', section: 'Part 4: Tax Info and Assets' },
  { key: 'pt4_l2c_TotalIncome', pdfKey: 'pt4_l2c_totalincome', label: 'Total Income', type: 'text', section: 'Part 4: Tax Info and Assets' },
  { key: 'pt4_l3_Assets', pdfKey: 'pt4_l3_assets', label: 'Assets', type: 'text', section: 'Part 4: Tax Info and Assets' },
  { key: 'pt4_l4_Assets', pdfKey: 'pt4_l4_assets', label: 'Assets', type: 'text', section: 'Part 4: Tax Info and Assets' },
  { key: 'pt4_l5_Assets', pdfKey: 'pt4_l5_assets', label: 'Assets', type: 'text', section: 'Part 4: Tax Info and Assets' },
  { key: 'pt4_l6_TotalAssets', pdfKey: 'pt4_l6_totalassets', label: 'Total Assets', type: 'text', section: 'Part 4: Tax Info and Assets' },
  // === Part 5: Sponsor Statement ===
  { key: 'pt5_l0_IntendingMigrants', pdfKey: 'pt5_l0_intendingmigrants', label: 'Intending Migrants', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l0_SponsorName', pdfKey: 'pt5_l0_sponsorname', label: 'Sponsor Name', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l1a_FamilyName', pdfKey: 'pt5_l1a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l1b_GivenName', pdfKey: 'pt5_l1b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l1c_MiddleName', pdfKey: 'pt5_l1c_middlename', label: 'Middle Name', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l1d_DateOfBirth', pdfKey: 'pt5_l1d_dateofbirth', label: 'Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l1e_ANumber', pdfKey: 'pt5_l1e_anumber', label: 'A-Number', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l1f_USCISAcctNumber', pdfKey: 'pt5_l1f_uscisacctnumber', label: 'USCIS Account Number', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l2a_FamilyName', pdfKey: 'pt5_l2a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l2b_GivenName', pdfKey: 'pt5_l2b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l2c_MiddleName', pdfKey: 'pt5_l2c_middlename', label: 'Middle Name', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l2d_DateOfBirth', pdfKey: 'pt5_l2d_dateofbirth', label: 'Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l2e_ANumber', pdfKey: 'pt5_l2e_anumber', label: 'A-Number', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l2f_USCISAcctNumber', pdfKey: 'pt5_l2f_uscisacctnumber', label: 'USCIS Account Number', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l3a_FamilyName', pdfKey: 'pt5_l3a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l3b_GivenName', pdfKey: 'pt5_l3b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l3c_MiddleName', pdfKey: 'pt5_l3c_middlename', label: 'Middle Name', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l3d_DateOfBirth', pdfKey: 'pt5_l3d_dateofbirth', label: 'Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l3e_ANumber', pdfKey: 'pt5_l3e_anumber', label: 'A-Number', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l3f_USCISAcctNumber', pdfKey: 'pt5_l3f_uscisacctnumber', label: 'USCIS Account Number', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l5_Checkbox', pdfKey: 'pt5_l5_checkbox', label: 'Part 5, Item 5', type: 'checkbox', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l5_Checkbox_1', pdfKey: 'pt5_l5_checkbox_1', label: 'Part 5, Item 5', type: 'checkbox', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l5_Checkbox_2', pdfKey: 'pt5_l5_checkbox_2', label: 'Part 5, Item 5', type: 'checkbox', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l5b_language', pdfKey: 'pt5_l5b_language', label: 'Language', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l5c_language', pdfKey: 'pt5_l5c_language', label: 'Language', type: 'text', section: 'Part 5: Sponsor Statement' },
  // === Part 6: Household Statement ===
  { key: 'pt6_l1_Checkbox', pdfKey: 'pt6_l1_checkbox', label: 'Part 6, Item 1', type: 'checkbox', section: 'Part 6: Household Statement' },
  { key: 'pt6_l1_Checkbox_1', pdfKey: 'pt6_l1_checkbox_1', label: 'Part 6, Item 1', type: 'checkbox', section: 'Part 6: Household Statement' },
  { key: 'pt6_l1b_language', pdfKey: 'pt6_l1b_language', label: 'Language', type: 'text', section: 'Part 6: Household Statement' },
  { key: 'pt6_l2_Attorney', pdfKey: 'pt6_l2_attorney', label: 'Attorney', type: 'text', section: 'Part 6: Household Statement' },
  { key: 'pt6_l2_Checkbox', pdfKey: 'pt6_l2_checkbox', label: 'Part 6, Item 2', type: 'checkbox', section: 'Part 6: Household Statement' },
  // === Part 7: Interpreter ===
  { key: 'pt7_l5_DaytimeTelephoneNumber', pdfKey: 'pt7_l5_daytimetelephonenumber', label: 'Daytime Telephone Number', type: 'text', section: 'Part 7: Interpreter' },
  { key: 'pt7_l6_MobileTelephoneNumber', pdfKey: 'pt7_l6_mobiletelephonenumber', label: 'Mobile Telephone Number', type: 'text', section: 'Part 7: Interpreter' },
  { key: 'pt7_l7_EmailAddress', pdfKey: 'pt7_l7_emailaddress', label: 'Email Address', type: 'text', section: 'Part 7: Interpreter' },
  { key: 'pt7_l6a_EmailAddress', pdfKey: 'pt7_l6a_emailaddress', label: 'Email Address', type: 'text', section: 'Part 7: Interpreter' },
  // === Part 8: Preparer ===
  { key: 'pt8_l1a_InterpretersFamilyName', pdfKey: 'pt8_l1a_interpretersfamilyname', label: 'Interpreters Family Name', type: 'text', section: 'Part 8: Preparer' },
  { key: 'pt8_l1b_InterpretersGivenName', pdfKey: 'pt8_l1b_interpretersgivenname', label: 'Interpreters Given Name', type: 'text', section: 'Part 8: Preparer' },
  { key: 'pt8_l2_InterpretersBusinessName', pdfKey: 'pt8_l2_interpretersbusinessname', label: 'Interpreters Business Name', type: 'text', section: 'Part 8: Preparer' },
  { key: 'pt8_l4_InterpretersDaytimePhoneNumber', pdfKey: 'pt8_l4_interpretersdaytimephonenumber', label: 'Interpreters Daytime Phone Number', type: 'text', section: 'Part 8: Preparer' },
  { key: 'pt8_l4_InterpretersDaytimePhoneNumber_1', pdfKey: 'pt8_l4_interpretersdaytimephonenumber_1', label: 'Interpreters Daytime Phone Number (2)', type: 'text', section: 'Part 8: Preparer' },
  { key: 'pt8_l5_InterpretersEmailAddress', pdfKey: 'pt8_l5_interpretersemailaddress', label: 'Interpreters Email Address', type: 'text', section: 'Part 8: Preparer' },
  { key: 'pt8_l0_Language', pdfKey: 'pt8_l0_language', label: 'Language', type: 'text', section: 'Part 8: Preparer' },
  // === Part 9: Additional Information ===
  { key: 'pt9_l0_Iamfluent', pdfKey: 'pt9_l0_iamfluent', label: 'I am fluent in', type: 'text', section: 'Part 9: Additional Information' },
  { key: 'pt9_l0_Iamfluent_1', pdfKey: 'pt9_l0_iamfluent_1', label: 'I am fluent in (2)', type: 'text', section: 'Part 9: Additional Information' },
  { key: 'pt9_l1a_PreparersFamilyName', pdfKey: 'pt9_l1a_preparersfamilyname', label: 'Preparers Family Name', type: 'text', section: 'Part 9: Additional Information' },
  { key: 'pt9_l1b_PreparersGivenName', pdfKey: 'pt9_l1b_preparersgivenname', label: 'Preparers Given Name', type: 'text', section: 'Part 9: Additional Information' },
  { key: 'pt9_l2_PreparersBusinessName', pdfKey: 'pt9_l2_preparersbusinessname', label: 'Preparers Business Name', type: 'text', section: 'Part 9: Additional Information' },
  { key: 'pt9_l4_PreparersDaytimePhoneNumber', pdfKey: 'pt9_l4_preparersdaytimephonenumber', label: 'Preparers Daytime Phone Number', type: 'text', section: 'Part 9: Additional Information' },
  { key: 'pt9_l5_PreparersFaxNumber', pdfKey: 'pt9_l5_preparersfaxnumber', label: 'Preparers Fax Number', type: 'text', section: 'Part 9: Additional Information' },
  { key: 'pt9_l6_PreparersEmailAddress', pdfKey: 'pt9_l6_preparersemailaddress', label: 'Preparers Email Address', type: 'text', section: 'Part 9: Additional Information' },
  // === Part 11 ===
  { key: 'pt11_l3a_PageNumber', pdfKey: 'pt11_l3a_pagenumber', label: 'Page Number', type: 'text', section: 'Part 11' },
  { key: 'pt11_l3b_PartNumber', pdfKey: 'pt11_l3b_partnumber', label: 'Part Number', type: 'text', section: 'Part 11' },
  { key: 'pt11_l3c_ItemNumber', pdfKey: 'pt11_l3c_itemnumber', label: 'Item Number', type: 'text', section: 'Part 11' },
  { key: 'pt11_l4a_PageNumber', pdfKey: 'pt11_l4a_pagenumber', label: 'Page Number', type: 'text', section: 'Part 11' },
  { key: 'pt11_l4b_PartNumber', pdfKey: 'pt11_l4b_partnumber', label: 'Part Number', type: 'text', section: 'Part 11' },
  { key: 'pt11_l4c_ItemNumber', pdfKey: 'pt11_l4c_itemnumber', label: 'Item Number', type: 'text', section: 'Part 11' },
  { key: 'pt11_l5a_PageNumber', pdfKey: 'pt11_l5a_pagenumber', label: 'Page Number', type: 'text', section: 'Part 11' },
  { key: 'pt11_l5b_PartNumber', pdfKey: 'pt11_l5b_partnumber', label: 'Part Number', type: 'text', section: 'Part 11' },
  { key: 'pt11_l5c_ItemNumber', pdfKey: 'pt11_l5c_itemnumber', label: 'Item Number', type: 'text', section: 'Part 11' },
  { key: 'pt11_l5d_AdditionalInfo', pdfKey: 'pt11_l5d_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 11' },
  { key: 'pt11_l5d_AdditionalInfo_1', pdfKey: 'pt11_l5d_additionalinfo_1', label: 'Additional Info (2)', type: 'text', section: 'Part 11' },
  { key: 'pt11_l5d_AdditionalInfo_2', pdfKey: 'pt11_l5d_additionalinfo_2', label: 'Additional Info (3)', type: 'text', section: 'Part 11' },
  { key: 'pt11_l6a_PageNumber', pdfKey: 'pt11_l6a_pagenumber', label: 'Page Number', type: 'text', section: 'Part 11' },
  { key: 'pt11_l6b_PartNumber', pdfKey: 'pt11_l6b_partnumber', label: 'Part Number', type: 'text', section: 'Part 11' },
  { key: 'pt11_l6c_ItemNumber', pdfKey: 'pt11_l6c_itemnumber', label: 'Item Number', type: 'text', section: 'Part 11' },
  { key: 'pt11_l6d_AdditionalInfo', pdfKey: 'pt11_l6d_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 11' },
];

export const getInitialFormData = () => {
  const data: Record<string, string> = {};
  formFields.forEach((f) => { if (f.key) data[f.key] = ''; });
  return data;
};

export const i864aConfig = { formId, formTitle, formSubtitle, formFields, getInitialFormData };
export default i864aConfig;