// Generated 151 fields for Form I-864A
import type { Field } from './types';

export const formId = 'i864a';
export const formTitle = 'Form I-864A';
export const formSubtitle = 'Contract Between Sponsor and Household Member';

export const formFields: Field[] = [
  // === Part 1: Household Member Info ===
  { key: 'pt1_l1a_familyname', pdfKey: 'pt1_l1a_familyname', label: 'Household Member\'s Family Name (Last Name)', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l1b_givenname', pdfKey: 'pt1_l1b_givenname', label: 'Household Member\'s Given Name (First Name)', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l1c_middlename', pdfKey: 'pt1_l1c_middlename', label: 'Middle Name', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l2_aptsteflrnumber', pdfKey: 'pt1_l2_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l2_cityortown', pdfKey: 'pt1_l2_cityortown', label: 'City or Town', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l2_country', pdfKey: 'pt1_l2_country', label: 'Country', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l2_incareofname', pdfKey: 'pt1_l2_incareofname', label: 'Incareofname', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l2_postalcode', pdfKey: 'pt1_l2_postalcode', label: 'Postalcode', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l2_province', pdfKey: 'pt1_l2_province', label: 'Province', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l2_state', pdfKey: 'pt1_l2_state', label: 'State', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l2_streetnumbername', pdfKey: 'pt1_l2_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l2_unit', pdfKey: 'pt1_l2_unit', label: 'Unit', type: 'checkbox', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l2_unit_1', pdfKey: 'pt1_l2_unit_1', label: 'Unit (1)', type: 'checkbox', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l2_unit_2', pdfKey: 'pt1_l2_unit_2', label: 'Unit (2)', type: 'checkbox', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l2_zipcode', pdfKey: 'pt1_l2_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l3_cb', pdfKey: 'pt1_l3_cb', label: 'Cb', type: 'checkbox', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l3_cb_1', pdfKey: 'pt1_l3_cb_1', label: 'Cb (1)', type: 'checkbox', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l4_aptsteflrnumber', pdfKey: 'pt1_l4_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l4_cityortown', pdfKey: 'pt1_l4_cityortown', label: 'City or Town', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l4_country', pdfKey: 'pt1_l4_country', label: 'Country', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l4_postalcode', pdfKey: 'pt1_l4_postalcode', label: 'Postalcode', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l4_province', pdfKey: 'pt1_l4_province', label: 'Province', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l4_state', pdfKey: 'pt1_l4_state', label: 'State', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l4_streetnumbername', pdfKey: 'pt1_l4_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l4_unit', pdfKey: 'pt1_l4_unit', label: 'Unit', type: 'checkbox', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l4_unit_1', pdfKey: 'pt1_l4_unit_1', label: 'Unit (1)', type: 'checkbox', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l4_unit_2', pdfKey: 'pt1_l4_unit_2', label: 'Unit (2)', type: 'checkbox', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l4_zipcode', pdfKey: 'pt1_l4_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l5_dateofbirth', pdfKey: 'pt1_l5_dateofbirth', label: 'Household Member\'s Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l6_countryofbirth', pdfKey: 'pt1_l6_countryofbirth', label: 'Country of Birth', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l7_ssn', pdfKey: 'pt1_l7_ssn', label: 'Social Security Number', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l8_aliennumber', pdfKey: 'pt1_l8_aliennumber', label: 'A-Number', type: 'text', section: 'Part 1: Household Member Info' },
  { key: 'pt1_l9_uscisonlineacctnumber', pdfKey: 'pt1_l9_uscisonlineacctnumber', label: 'Uscisonlineacctnumber', type: 'text', section: 'Part 1: Household Member Info' },
  // === Part 2: Relationship to Sponsor ===
  { key: 'pt2_l3_a_other', pdfKey: 'pt2_l3_a_other', label: 'A_Other', type: 'text', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l3_a_relationship', pdfKey: 'pt2_l3_a_relationship', label: 'A_Relationship', type: 'checkbox', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l3_a_relationship_1', pdfKey: 'pt2_l3_a_relationship_1', label: 'A_Relationship (1)', type: 'checkbox', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l3_a_relationship_2', pdfKey: 'pt2_l3_a_relationship_2', label: 'A_Relationship (2)', type: 'checkbox', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l3_a_relationship_3', pdfKey: 'pt2_l3_a_relationship_3', label: 'A_Relationship (3)', type: 'checkbox', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l3_a_relationship_4', pdfKey: 'pt2_l3_a_relationship_4', label: 'A_Relationship (4)', type: 'checkbox', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l5_ssn', pdfKey: 'pt2_l5_ssn', label: 'Social Security Number', type: 'text', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l6_usciselisacctnumber', pdfKey: 'pt2_l6_usciselisacctnumber', label: 'Usciselisacctnumber', type: 'text', section: 'Part 2: Relationship to Sponsor' },
  { key: 'pt2_l8_dateofbirth', pdfKey: 'pt2_l8_dateofbirth', label: 'Dateofbirth', type: 'date', section: 'Part 2: Relationship to Sponsor' },
  // === Part 3: Employment and Income ===
  { key: 'pt3_l1_employment', pdfKey: 'pt3_l1_employment', label: 'Employment', type: 'checkbox', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l1a_employed', pdfKey: 'pt3_l1a_employed', label: 'Employed', type: 'text', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l2_currentincome', pdfKey: 'pt3_l2_currentincome', label: 'Currentincome', type: 'text', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l2_employed', pdfKey: 'pt3_l2_employed', label: 'Employed', type: 'text', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l3_employed', pdfKey: 'pt3_l3_employed', label: 'Employed', type: 'text', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l4_employment', pdfKey: 'pt3_l4_employment', label: 'Employment', type: 'checkbox', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l4a_selfemployeddescription', pdfKey: 'pt3_l4a_selfemployeddescription', label: 'Selfemployeddescription', type: 'text', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l5_employment', pdfKey: 'pt3_l5_employment', label: 'Employment', type: 'checkbox', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l5a_employeddate', pdfKey: 'pt3_l5a_employeddate', label: 'Employeddate', type: 'date', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l6_employment', pdfKey: 'pt3_l6_employment', label: 'Employment', type: 'checkbox', section: 'Part 3: Employment and Income' },
  { key: 'pt3_l6a_employeddate', pdfKey: 'pt3_l6a_employeddate', label: 'Employeddate', type: 'date', section: 'Part 3: Employment and Income' },
  // === Part 4: Assets ===
  { key: 'pt4_l1_cb', pdfKey: 'pt4_l1_cb', label: 'Cb', type: 'checkbox', section: 'Part 4: Assets' },
  { key: 'pt4_l1_cb_1', pdfKey: 'pt4_l1_cb_1', label: 'Cb (1)', type: 'checkbox', section: 'Part 4: Assets' },
  { key: 'pt4_l2a_taxyear', pdfKey: 'pt4_l2a_taxyear', label: 'Taxyear', type: 'text', section: 'Part 4: Assets' },
  { key: 'pt4_l2a_totalincome', pdfKey: 'pt4_l2a_totalincome', label: 'Totalincome', type: 'text', section: 'Part 4: Assets' },
  { key: 'pt4_l2b_taxyear', pdfKey: 'pt4_l2b_taxyear', label: 'Taxyear', type: 'text', section: 'Part 4: Assets' },
  { key: 'pt4_l2b_totalincome', pdfKey: 'pt4_l2b_totalincome', label: 'Totalincome', type: 'text', section: 'Part 4: Assets' },
  { key: 'pt4_l2c_taxyear', pdfKey: 'pt4_l2c_taxyear', label: 'Taxyear', type: 'text', section: 'Part 4: Assets' },
  { key: 'pt4_l2c_totalincome', pdfKey: 'pt4_l2c_totalincome', label: 'Totalincome', type: 'text', section: 'Part 4: Assets' },
  { key: 'pt4_l3_assets', pdfKey: 'pt4_l3_assets', label: 'Assets', type: 'text', section: 'Part 4: Assets' },
  { key: 'pt4_l4_assets', pdfKey: 'pt4_l4_assets', label: 'Assets', type: 'text', section: 'Part 4: Assets' },
  { key: 'pt4_l5_assets', pdfKey: 'pt4_l5_assets', label: 'Assets', type: 'text', section: 'Part 4: Assets' },
  { key: 'pt4_l6_totalassets', pdfKey: 'pt4_l6_totalassets', label: 'Totalassets', type: 'text', section: 'Part 4: Assets' },
  // === Part 5: Sponsor Statement ===
  { key: 'pt5_l1a_familyname', pdfKey: 'pt5_l1a_familyname', label: 'Family Name', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l1b_givenname', pdfKey: 'pt5_l1b_givenname', label: 'Given Name', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l1c_middlename', pdfKey: 'pt5_l1c_middlename', label: 'Middle Name', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l1d_dateofbirth', pdfKey: 'pt5_l1d_dateofbirth', label: 'Dateofbirth', type: 'date', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l1e_anumber', pdfKey: 'pt5_l1e_anumber', label: 'Anumber', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l1f_uscisacctnumber', pdfKey: 'pt5_l1f_uscisacctnumber', label: 'Uscisacctnumber', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l2a_familyname', pdfKey: 'pt5_l2a_familyname', label: 'Family Name', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l2b_givenname', pdfKey: 'pt5_l2b_givenname', label: 'Given Name', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l2c_middlename', pdfKey: 'pt5_l2c_middlename', label: 'Middle Name', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l2d_dateofbirth', pdfKey: 'pt5_l2d_dateofbirth', label: 'Dateofbirth', type: 'date', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l2e_anumber', pdfKey: 'pt5_l2e_anumber', label: 'Anumber', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l2f_uscisacctnumber', pdfKey: 'pt5_l2f_uscisacctnumber', label: 'Uscisacctnumber', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l3a_familyname', pdfKey: 'pt5_l3a_familyname', label: 'Family Name', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l3b_givenname', pdfKey: 'pt5_l3b_givenname', label: 'Given Name', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l3c_middlename', pdfKey: 'pt5_l3c_middlename', label: 'Middle Name', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l3d_dateofbirth', pdfKey: 'pt5_l3d_dateofbirth', label: 'Dateofbirth', type: 'date', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l3e_anumber', pdfKey: 'pt5_l3e_anumber', label: 'Anumber', type: 'text', section: 'Part 5: Sponsor Statement' },
  { key: 'pt5_l3f_uscisacctnumber', pdfKey: 'pt5_l3f_uscisacctnumber', label: 'Uscisacctnumber', type: 'text', section: 'Part 5: Sponsor Statement' },
  // === Part 6: Household Member Statement ===
  { key: 'pt6_l1_checkbox', pdfKey: 'pt6_l1_checkbox', label: 'Part 6, Item 1', type: 'checkbox', section: 'Part 6: Household Member Statement' },
  { key: 'pt6_l1_checkbox_1', pdfKey: 'pt6_l1_checkbox_1', label: 'Part 6, Item 1', type: 'checkbox', section: 'Part 6: Household Member Statement' },
  { key: 'pt6_l2_checkbox', pdfKey: 'pt6_l2_checkbox', label: 'Part 6, Item 2', type: 'checkbox', section: 'Part 6: Household Member Statement' },
  // === Part 8: Preparer Info ===
  { key: 'pt8_l3_daytimephone', pdfKey: 'pt8_l3_daytimephone', label: 'Daytimephone', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l4_mobilephone', pdfKey: 'pt8_l4_mobilephone', label: 'Mobilephone', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l4a_familyname', pdfKey: 'pt8_l4a_familyname', label: 'Family Name', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l4a_givenname', pdfKey: 'pt8_l4a_givenname', label: 'Given Name', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l4a_middlename', pdfKey: 'pt8_l4a_middlename', label: 'Middle Name', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l5_checkbox', pdfKey: 'pt8_l5_checkbox', label: 'Part 8, Item 5', type: 'checkbox', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l5_checkbox_1', pdfKey: 'pt8_l5_checkbox_1', label: 'Part 8, Item 5', type: 'checkbox', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l5_checkbox_2', pdfKey: 'pt8_l5_checkbox_2', label: 'Part 8, Item 5', type: 'checkbox', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l5_emailaddress', pdfKey: 'pt8_l5_emailaddress', label: 'Emailaddress', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l5b_language', pdfKey: 'pt8_l5b_language', label: 'Language', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l5c_language', pdfKey: 'pt8_l5c_language', label: 'Language', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l6_applicantsignature', pdfKey: 'pt8_l6_applicantsignature', label: 'Applicantsignature', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l6_dateofsignature', pdfKey: 'pt8_l6_dateofsignature', label: 'Dateofsignature', type: 'date', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l1b_language', pdfKey: 'pt8_l1b_language', label: 'Language', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l2_attorney', pdfKey: 'pt8_l2_attorney', label: 'Attorney', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l5_daytimetelephonenumber', pdfKey: 'pt8_l5_daytimetelephonenumber', label: 'Daytimetelephonenumber', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l6_mobiletelephonenumber', pdfKey: 'pt8_l6_mobiletelephonenumber', label: 'Mobiletelephonenumber', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l7_emailaddress', pdfKey: 'pt8_l7_emailaddress', label: 'Emailaddress', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l1a_interpretersfamilyname', pdfKey: 'pt8_l1a_interpretersfamilyname', label: 'Interpretersfamilyname', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l1b_interpretersgivenname', pdfKey: 'pt8_l1b_interpretersgivenname', label: 'Interpretersgivenname', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l2_interpretersbusinessname', pdfKey: 'pt8_l2_interpretersbusinessname', label: 'Interpretersbusinessname', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l4_interpretersdaytimephonenumber', pdfKey: 'pt8_l4_interpretersdaytimephonenumber', label: 'Interpretersdaytimephonenumber', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l4_interpretersdaytimephonenumber_1', pdfKey: 'pt8_l4_interpretersdaytimephonenumber_1', label: 'Interpretersdaytimephonenumber (1)', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l5_interpretersemailaddress', pdfKey: 'pt8_l5_interpretersemailaddress', label: 'Interpretersemailaddress', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l6_applicantsignature_1', pdfKey: 'pt8_l6_applicantsignature_1', label: 'Applicantsignature (1)', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l6_dateofsignature_1', pdfKey: 'pt8_l6_dateofsignature_1', label: 'Dateofsignature (1)', type: 'date', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l6a_emailaddress', pdfKey: 'pt8_l6a_emailaddress', label: 'Emailaddress', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l1a_preparersfamilyname', pdfKey: 'pt8_l1a_preparersfamilyname', label: 'Preparersfamilyname', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l1b_preparersgivenname', pdfKey: 'pt8_l1b_preparersgivenname', label: 'Preparersgivenname', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l2_preparersbusinessname', pdfKey: 'pt8_l2_preparersbusinessname', label: 'Preparersbusinessname', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l4_preparersdaytimephonenumber', pdfKey: 'pt8_l4_preparersdaytimephonenumber', label: 'Preparersdaytimephonenumber', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l5_preparersfaxnumber', pdfKey: 'pt8_l5_preparersfaxnumber', label: 'Preparersfaxnumber', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l6_applicantsignature_2', pdfKey: 'pt8_l6_applicantsignature_2', label: 'Applicantsignature (2)', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l6_applicantsignature_3', pdfKey: 'pt8_l6_applicantsignature_3', label: 'Applicantsignature (3)', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l6_dateofsignature_2', pdfKey: 'pt8_l6_dateofsignature_2', label: 'Dateofsignature (2)', type: 'date', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l6_dateofsignature_3', pdfKey: 'pt8_l6_dateofsignature_3', label: 'Dateofsignature (3)', type: 'date', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l6_preparersemailaddress', pdfKey: 'pt8_l6_preparersemailaddress', label: 'Preparersemailaddress', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l1a_familyname', pdfKey: 'pt8_l1a_familyname', label: 'Family Name', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l1b_givenname', pdfKey: 'pt8_l1b_givenname', label: 'Given Name', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l1c_middlename', pdfKey: 'pt8_l1c_middlename', label: 'Middle Name', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l3a_pagenumber', pdfKey: 'pt8_l3a_pagenumber', label: 'Pagenumber', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l3b_partnumber', pdfKey: 'pt8_l3b_partnumber', label: 'Partnumber', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l3c_itemnumber', pdfKey: 'pt8_l3c_itemnumber', label: 'Itemnumber', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l3e_aliennumber', pdfKey: 'pt8_l3e_aliennumber', label: 'A-Number', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l4a_pagenumber', pdfKey: 'pt8_l4a_pagenumber', label: 'Pagenumber', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l4b_partnumber', pdfKey: 'pt8_l4b_partnumber', label: 'Partnumber', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l4c_itemnumber', pdfKey: 'pt8_l4c_itemnumber', label: 'Itemnumber', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l5a_pagenumber', pdfKey: 'pt8_l5a_pagenumber', label: 'Pagenumber', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l5b_partnumber', pdfKey: 'pt8_l5b_partnumber', label: 'Partnumber', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l5c_itemnumber', pdfKey: 'pt8_l5c_itemnumber', label: 'Itemnumber', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l5d_additionalinfo', pdfKey: 'pt8_l5d_additionalinfo', label: 'Additionalinfo', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l5d_additionalinfo_1', pdfKey: 'pt8_l5d_additionalinfo_1', label: 'Additionalinfo (1)', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l5d_additionalinfo_2', pdfKey: 'pt8_l5d_additionalinfo_2', label: 'Additionalinfo (2)', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l6a_pagenumber', pdfKey: 'pt8_l6a_pagenumber', label: 'Pagenumber', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l6b_partnumber', pdfKey: 'pt8_l6b_partnumber', label: 'Partnumber', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l6c_itemnumber', pdfKey: 'pt8_l6c_itemnumber', label: 'Itemnumber', type: 'text', section: 'Part 8: Preparer Info' },
  { key: 'pt8_l6d_additionalinfo', pdfKey: 'pt8_l6d_additionalinfo', label: 'Additionalinfo', type: 'text', section: 'Part 8: Preparer Info' },
  // === Part 0 ===
  { key: 's_attorneystatebarnumber', pdfKey: 's_attorneystatebarnumber', label: 'S_Attorneystatebarnumber', type: 'text', section: 'Part 0' },
  { key: 's_g28-checkbox1', pdfKey: 's_g28-checkbox1', label: 'S_G28-1', type: 'checkbox', section: 'Part 0' },
  { key: 's_uscisonlineaccountnumber', pdfKey: 's_uscisonlineaccountnumber', label: 'S_Uscisonlineaccountnumber', type: 'text', section: 'Part 0' },
  { key: 's_p2_line1-3_checkbox', pdfKey: 's_p2_line1-3_checkbox', label: 'S_P2_Line1-3_', type: 'checkbox', section: 'Part 0' },
  { key: 's_p5_intendingmigrants', pdfKey: 's_p5_intendingmigrants', label: 'S_P5_Intendingmigrants', type: 'text', section: 'Part 0' },
  { key: 's_p5_sponsorname', pdfKey: 's_p5_sponsorname', label: 'S_P5_Sponsorname', type: 'text', section: 'Part 0' },
  { key: 's_part9_iamfluent', pdfKey: 's_part9_iamfluent', label: 'S_Part9_Iamfluent', type: 'text', section: 'Part 0' },
  { key: 's_p8_language', pdfKey: 's_p8_language', label: 'S_P8_Language', type: 'text', section: 'Part 0' },
];

export const getInitialFormData = () => {
  const data: Record<string, string> = {};
  formFields.forEach((f) => { if (f.key != null) data[f.key] = ''; });
  return data;
};

export const i864aConfig = { formId, formTitle, formSubtitle, formFields, getInitialFormData };
export default i864aConfig;