// Generated fields for Form I-912
import type { Field } from './types';

export const formId = 'i912';
export const formTitle = 'Form I-912';
export const formSubtitle = 'Request for Fee Waiver';

export const formFields: Field[] = [
  // === Part 1: Basis for Request ===
  { key: 'pt1_l0_ImmStatus', pdfKey: 'pt1_l0_immstatus', label: 'Imm Status', type: 'text', section: 'Part 1: Basis for Request' },
  { key: 'pt1_l1_Checkbox', pdfKey: 'pt1_l1_checkbox', label: 'I, my spouse, or head of household is receiving a means-tested benefit.', type: 'checkbox', section: 'Part 1: Basis for Request' },
  { key: 'pt1_l1_Checkbox_1', pdfKey: 'pt1_l1_checkbox_1', label: 'My household income is at or below 150 percent of the Federal Poverty Guidelines.', type: 'checkbox', section: 'Part 1: Basis for Request' },
  { key: 'pt1_l2_Checkbox', pdfKey: 'pt1_l2_checkbox', label: 'I have a financial hardship.', type: 'checkbox', section: 'Part 1: Basis for Request' },
  { key: 'pt1_l3_Checkbox', pdfKey: 'pt1_l3_checkbox', label: 'Part 1, Item 3', type: 'checkbox', section: 'Part 1: Basis for Request' },
  // === Part 2: Requestor Info ===
  { key: 'pt2_l3_AlienNumber', pdfKey: 'pt2_l3_aliennumber', label: 'A-Number', type: 'text', section: 'Part 2: Requestor Info' },
  { key: 'pt2_l3_FamilyName', pdfKey: 'pt2_l3_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 2: Requestor Info' },
  { key: 'pt2_l3_GivenName', pdfKey: 'pt2_l3_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 2: Requestor Info' },
  { key: 'pt2_l3_MiddleName', pdfKey: 'pt2_l3_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Requestor Info' },
  { key: 'pt2_l4_AcctIdentifier', pdfKey: 'pt2_l4_acctidentifier', label: 'Acct Identifier', type: 'text', section: 'Part 2: Requestor Info' },
  { key: 'pt2_lL2_FamilyName', pdfKey: 'pt2_ll2_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 2: Requestor Info' },
  { key: 'pt2_lL2_GivenName', pdfKey: 'pt2_ll2_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 2: Requestor Info' },
  { key: 'pt2_lL2_MiddleName', pdfKey: 'pt2_ll2_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Requestor Info' },
  { key: 'pt2_lL3_FamilyName', pdfKey: 'pt2_ll3_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 2: Requestor Info' },
  { key: 'pt2_lL3_GivenName', pdfKey: 'pt2_ll3_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 2: Requestor Info' },
  { key: 'pt2_lL3_MiddleName', pdfKey: 'pt2_ll3_middlename', label: 'Middle Name', type: 'text', section: 'Part 2: Requestor Info' },
  { key: 'pt2_l5_DateOfBirth', pdfKey: 'pt2_l5_dateofbirth', label: 'Date of Birth (mm/dd/yyyy)', type: 'date', section: 'Part 2: Requestor Info' },
  { key: 'pt2_l6_SSN', pdfKey: 'pt2_l6_ssn', label: 'Social Security Number', type: 'text', section: 'Part 2: Requestor Info' },
  { key: 'pt2_l7_MaritalStatus', pdfKey: 'pt2_l7_maritalstatus', label: 'Marital Status', type: 'checkbox', section: 'Part 2: Requestor Info' },
  { key: 'pt2_l7_MaritalStatus_1', pdfKey: 'pt2_l7_maritalstatus_1', label: 'Marital Status (Item 2)', type: 'checkbox', section: 'Part 2: Requestor Info' },
  { key: 'pt2_l7_MaritalStatus_2', pdfKey: 'pt2_l7_maritalstatus_2', label: 'Marital Status (Item 3)', type: 'checkbox', section: 'Part 2: Requestor Info' },
  { key: 'pt2_l7_MaritalStatus_3', pdfKey: 'pt2_l7_maritalstatus_3', label: 'Marital Status (Item 4)', type: 'checkbox', section: 'Part 2: Requestor Info' },
  { key: 'pt2_l7_MaritalStatus_4', pdfKey: 'pt2_l7_maritalstatus_4', label: 'Marital Status (Item 5)', type: 'checkbox', section: 'Part 2: Requestor Info' },
  { key: 'pt2_l7_MaritalStatus_5', pdfKey: 'pt2_l7_maritalstatus_5', label: 'Marital Status (Item 6)', type: 'checkbox', section: 'Part 2: Requestor Info' },
  { key: 'pt2_l7_MaritalStatus_6', pdfKey: 'pt2_l7_maritalstatus_6', label: 'Marital Status (Item 7)', type: 'checkbox', section: 'Part 2: Requestor Info' },
  { key: 'pt2_l7_OtherText', pdfKey: 'pt2_l7_othertext', label: 'Other Text', type: 'text', section: 'Part 2: Requestor Info' },
  { key: 'pt2_l3_AlienNumber_1', pdfKey: 'pt2_l3_aliennumber_1', label: 'A-Number (Item 2)', type: 'text', section: 'Part 2: Requestor Info' },
  { key: 'pt2_lL2_FamilyName_1', pdfKey: 'pt2_ll2_familyname_1', label: 'Family Name (Last Name) (Item 2)', type: 'text', section: 'Part 2: Requestor Info' },
  { key: 'pt2_lL2_GivenName_1', pdfKey: 'pt2_ll2_givenname_1', label: 'Given Name (First Name) (Item 2)', type: 'text', section: 'Part 2: Requestor Info' },
  { key: 'pt2_lL2_MiddleName_1', pdfKey: 'pt2_ll2_middlename_1', label: 'Middle Name (Item 2)', type: 'text', section: 'Part 2: Requestor Info' },
  // === Part 3: Applications ===
  { key: 'pt3_l1_AlienNumber', pdfKey: 'pt3_l1_aliennumber', label: 'A-Number', type: 'text', section: 'Part 3: Applications' },
  { key: 'pt3_l1_AlienNumber2', pdfKey: 'pt3_l1_aliennumber2', label: 'Alien Number2', type: 'text', section: 'Part 3: Applications' },
  { key: 'pt3_l1_AlienNumber3', pdfKey: 'pt3_l1_aliennumber3', label: 'Alien Number3', type: 'text', section: 'Part 3: Applications' },
  { key: 'pt3_l1_AlienNumber4', pdfKey: 'pt3_l1_aliennumber4', label: 'Alien Number4', type: 'text', section: 'Part 3: Applications' },
  { key: 'pt3_l1_DateofBirth1', pdfKey: 'pt3_l1_dateofbirth1', label: 'Dateof Birth1', type: 'date', section: 'Part 3: Applications' },
  { key: 'pt3_l1_DateofBirth2', pdfKey: 'pt3_l1_dateofbirth2', label: 'Dateof Birth2', type: 'date', section: 'Part 3: Applications' },
  { key: 'pt3_l1_DateofBirth3', pdfKey: 'pt3_l1_dateofbirth3', label: 'Dateof Birth3', type: 'date', section: 'Part 3: Applications' },
  { key: 'pt3_l1_DateofBirth4', pdfKey: 'pt3_l1_dateofbirth4', label: 'Dateof Birth4', type: 'date', section: 'Part 3: Applications' },
  { key: 'pt3_l1_FormsFiled1', pdfKey: 'pt3_l1_formsfiled1', label: 'Forms Filed1', type: 'text', section: 'Part 3: Applications' },
  { key: 'pt3_l1_FormsFiled2', pdfKey: 'pt3_l1_formsfiled2', label: 'Forms Filed2', type: 'text', section: 'Part 3: Applications' },
  { key: 'pt3_l1_FormsFiled3', pdfKey: 'pt3_l1_formsfiled3', label: 'Forms Filed3', type: 'text', section: 'Part 3: Applications' },
  { key: 'pt3_l1_FormsFiled4', pdfKey: 'pt3_l1_formsfiled4', label: 'Forms Filed4', type: 'text', section: 'Part 3: Applications' },
  { key: 'pt3_l1_Name1', pdfKey: 'pt3_l1_name1', label: 'Name1', type: 'text', section: 'Part 3: Applications' },
  { key: 'pt3_l1_Name2', pdfKey: 'pt3_l1_name2', label: 'Name2', type: 'text', section: 'Part 3: Applications' },
  { key: 'pt3_l1_Name3', pdfKey: 'pt3_l1_name3', label: 'Name3', type: 'text', section: 'Part 3: Applications' },
  { key: 'pt3_l1_Name4', pdfKey: 'pt3_l1_name4', label: 'Name4', type: 'text', section: 'Part 3: Applications' },
  { key: 'pt3_l1_TotalForms', pdfKey: 'pt3_l1_totalforms', label: 'Total Forms', type: 'text', section: 'Part 3: Applications' },
  { key: 'pt3_l3_Other', pdfKey: 'pt3_l3_other', label: 'Other', type: 'text', section: 'Part 3: Applications' },
  { key: 'pt3_lL2a_ApplicantsSignature', pdfKey: 'pt3_ll2a_applicantssignature', label: 'Applicants Signature', type: 'text', section: 'Part 3: Applications' },
  // === Part 4: Benefits ===
  { key: 'pt4_l1_Agency1', pdfKey: 'pt4_l1_agency1', label: 'Agency1', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_Agency1_1', pdfKey: 'pt4_l1_agency1_1', label: 'Agency1 (Item 2)', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_Agency2', pdfKey: 'pt4_l1_agency2', label: 'Agency2', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_Agency2_1', pdfKey: 'pt4_l1_agency2_1', label: 'Agency2 (Item 2)', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_Agency3', pdfKey: 'pt4_l1_agency3', label: 'Agency3', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_Agency3_1', pdfKey: 'pt4_l1_agency3_1', label: 'Agency3 (Item 2)', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_Agency4', pdfKey: 'pt4_l1_agency4', label: 'Agency4', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_Agency4_1', pdfKey: 'pt4_l1_agency4_1', label: 'Agency4 (Item 2)', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_DateAward1', pdfKey: 'pt4_l1_dateaward1', label: 'Date Award1', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_DateAward1_1', pdfKey: 'pt4_l1_dateaward1_1', label: 'Date Award1 (Item 2)', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_DateAward2', pdfKey: 'pt4_l1_dateaward2', label: 'Date Award2', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_DateAward2_1', pdfKey: 'pt4_l1_dateaward2_1', label: 'Date Award2 (Item 2)', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_DateAward3', pdfKey: 'pt4_l1_dateaward3', label: 'Date Award3', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_DateAward3_1', pdfKey: 'pt4_l1_dateaward3_1', label: 'Date Award3 (Item 2)', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_DateAward4', pdfKey: 'pt4_l1_dateaward4', label: 'Date Award4', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_DateAward4_1', pdfKey: 'pt4_l1_dateaward4_1', label: 'Date Award4 (Item 2)', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_ExpDate1', pdfKey: 'pt4_l1_expdate1', label: 'Exp Date1', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_ExpDate1_1', pdfKey: 'pt4_l1_expdate1_1', label: 'Exp Date1 (Item 2)', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_ExpDate2', pdfKey: 'pt4_l1_expdate2', label: 'Exp Date2', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_ExpDate2_1', pdfKey: 'pt4_l1_expdate2_1', label: 'Exp Date2 (Item 2)', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_ExpDate3', pdfKey: 'pt4_l1_expdate3', label: 'Exp Date3', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_ExpDate3_1', pdfKey: 'pt4_l1_expdate3_1', label: 'Exp Date3 (Item 2)', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_ExpDate4', pdfKey: 'pt4_l1_expdate4', label: 'Exp Date4', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_ExpDate4_1', pdfKey: 'pt4_l1_expdate4_1', label: 'Exp Date4 (Item 2)', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_FullName1', pdfKey: 'pt4_l1_fullname1', label: 'Full Name1', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_FullName1_1', pdfKey: 'pt4_l1_fullname1_1', label: 'Full Name1 (Item 2)', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_FullName2', pdfKey: 'pt4_l1_fullname2', label: 'Full Name2', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_FullName2_1', pdfKey: 'pt4_l1_fullname2_1', label: 'Full Name2 (Item 2)', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_FullName3', pdfKey: 'pt4_l1_fullname3', label: 'Full Name3', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_FullName3_1', pdfKey: 'pt4_l1_fullname3_1', label: 'Full Name3 (Item 2)', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_FullName4', pdfKey: 'pt4_l1_fullname4', label: 'Full Name4', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_FullName4_1', pdfKey: 'pt4_l1_fullname4_1', label: 'Full Name4 (Item 2)', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_Relationship1', pdfKey: 'pt4_l1_relationship1', label: 'Relationship1', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_Relationship1_1', pdfKey: 'pt4_l1_relationship1_1', label: 'Relationship1 (Item 2)', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_Relationship2', pdfKey: 'pt4_l1_relationship2', label: 'Relationship2', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_Relationship2_1', pdfKey: 'pt4_l1_relationship2_1', label: 'Relationship2 (Item 2)', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_Relationship3', pdfKey: 'pt4_l1_relationship3', label: 'Relationship3', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_Relationship3_1', pdfKey: 'pt4_l1_relationship3_1', label: 'Relationship3 (Item 2)', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_Relationship4', pdfKey: 'pt4_l1_relationship4', label: 'Relationship4', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_Relationship4_1', pdfKey: 'pt4_l1_relationship4_1', label: 'Relationship4 (Item 2)', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_TypeofBene1', pdfKey: 'pt4_l1_typeofbene1', label: 'Typeof Bene1', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_TypeofBene1_1', pdfKey: 'pt4_l1_typeofbene1_1', label: 'Typeof Bene1 (Item 2)', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_TypeofBene2', pdfKey: 'pt4_l1_typeofbene2', label: 'Typeof Bene2', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_TypeofBene2_1', pdfKey: 'pt4_l1_typeofbene2_1', label: 'Typeof Bene2 (Item 2)', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_TypeofBene3', pdfKey: 'pt4_l1_typeofbene3', label: 'Typeof Bene3', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_TypeofBene3_1', pdfKey: 'pt4_l1_typeofbene3_1', label: 'Typeof Bene3 (Item 2)', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_TypeofBene4', pdfKey: 'pt4_l1_typeofbene4', label: 'Typeof Bene4', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l1_TypeofBene4_1', pdfKey: 'pt4_l1_typeofbene4_1', label: 'Typeof Bene4 (Item 2)', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l2a_RelationshipToYou1', pdfKey: 'pt4_l2a_relationshiptoyou1', label: 'Relationship To You1', type: 'text', section: 'Part 4: Benefits' },
  { key: 'pt4_l2b_DateofBirth2', pdfKey: 'pt4_l2b_dateofbirth2', label: 'Dateof Birth2', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l2c_DateofBirth3', pdfKey: 'pt4_l2c_dateofbirth3', label: 'Dateof Birth3', type: 'date', section: 'Part 4: Benefits' },
  { key: 'pt4_l2d_DateofBirth4', pdfKey: 'pt4_l2d_dateofbirth4', label: 'Dateof Birth4', type: 'date', section: 'Part 4: Benefits' },
  // === Part 5: Income ===
  { key: 'pt5_l1_EmploymentStatus', pdfKey: 'pt5_l1_employmentstatus', label: 'Employment Status', type: 'checkbox', section: 'Part 5: Income' },
  { key: 'pt5_l1_EmploymentStatus_1', pdfKey: 'pt5_l1_employmentstatus_1', label: 'Employment Status (Item 2)', type: 'checkbox', section: 'Part 5: Income' },
  { key: 'pt5_l1_EmploymentStatus_2', pdfKey: 'pt5_l1_employmentstatus_2', label: 'Employment Status (Item 3)', type: 'checkbox', section: 'Part 5: Income' },
  { key: 'pt5_l1_EmploymentStatus_3', pdfKey: 'pt5_l1_employmentstatus_3', label: 'Employment Status (Item 4)', type: 'checkbox', section: 'Part 5: Income' },
  { key: 'pt5_l2_chbxyesno', pdfKey: 'pt5_l2_chbxyesno', label: 'Chbxyesno', type: 'checkbox', section: 'Part 5: Income' },
  { key: 'pt5_l2_chbxyesno_1', pdfKey: 'pt5_l2_chbxyesno_1', label: 'Chbxyesno (Item 2)', type: 'checkbox', section: 'Part 5: Income' },
  { key: 'pt5_l2a_DateOfUnemployment', pdfKey: 'pt5_l2a_dateofunemployment', label: 'Date of Unemployment', type: 'date', section: 'Part 5: Income' },
  { key: 'pt5_l3_TotalHouseSize', pdfKey: 'pt5_l3_totalhousesize', label: 'Total House Size', type: 'text', section: 'Part 5: Income' },
  { key: 'pt5_l4_TotalHousehold', pdfKey: 'pt5_l4_totalhousehold', label: 'Total Household', type: 'text', section: 'Part 5: Income' },
  { key: 'pt5_l5_NameHousehold', pdfKey: 'pt5_l5_namehousehold', label: 'Name Household', type: 'text', section: 'Part 5: Income' },
  { key: 'pt5_l9_checkbox', pdfKey: 'pt5_l9_checkbox', label: 'Part 5, Item 9', type: 'checkbox', section: 'Part 5: Income' },
  { key: 'pt5_l9_checkbox_1', pdfKey: 'pt5_l9_checkbox_1', label: 'Part 5, Item 9', type: 'checkbox', section: 'Part 5: Income' },
  { key: 'pt5_l9_Explanation', pdfKey: 'pt5_l9_explanation', label: 'Explanation', type: 'text', section: 'Part 5: Income' },
  // === Part 6: Hardship ===
  { key: 'pt6_l1_Situation', pdfKey: 'pt6_l1_situation', label: 'Situation', type: 'text', section: 'Part 6: Hardship' },
  { key: 'pt6_l3_Checkbox', pdfKey: 'pt6_l3_checkbox', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6: Hardship' },
  { key: 'pt6_l3_Checkbox_1', pdfKey: 'pt6_l3_checkbox_1', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6: Hardship' },
  { key: 'pt6_l3_Checkbox_10', pdfKey: 'pt6_l3_checkbox_10', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6: Hardship' },
  { key: 'pt6_l3_Checkbox_2', pdfKey: 'pt6_l3_checkbox_2', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6: Hardship' },
  { key: 'pt6_l3_Checkbox_3', pdfKey: 'pt6_l3_checkbox_3', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6: Hardship' },
  { key: 'pt6_l3_Checkbox_4', pdfKey: 'pt6_l3_checkbox_4', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6: Hardship' },
  { key: 'pt6_l3_Checkbox_5', pdfKey: 'pt6_l3_checkbox_5', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6: Hardship' },
  { key: 'pt6_l3_Checkbox_6', pdfKey: 'pt6_l3_checkbox_6', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6: Hardship' },
  { key: 'pt6_l3_Checkbox_7', pdfKey: 'pt6_l3_checkbox_7', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6: Hardship' },
  { key: 'pt6_l3_Checkbox_8', pdfKey: 'pt6_l3_checkbox_8', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6: Hardship' },
  { key: 'pt6_l3_Checkbox_9', pdfKey: 'pt6_l3_checkbox_9', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6: Hardship' },
  { key: 'pt6_l3_Other', pdfKey: 'pt6_l3_other', label: 'Other', type: 'text', section: 'Part 6: Hardship' },
  { key: 'pt6_l3_Total', pdfKey: 'pt6_l3_total', label: 'Total', type: 'text', section: 'Part 6: Hardship' },
  // === Part 7: Requestor Statement ===
  { key: 'pt7_l0_Check_box', pdfKey: 'pt7_l0_check_box', label: 'Check_Box', type: 'checkbox', section: 'Part 7: Requestor Statement' },
  { key: 'pt7_l0_Check_box_1', pdfKey: 'pt7_l0_check_box_1', label: 'Check_Box (Item 2)', type: 'checkbox', section: 'Part 7: Requestor Statement' },
  { key: 'pt7_l0_Check_box_2', pdfKey: 'pt7_l0_check_box_2', label: 'Check_Box (Item 3)', type: 'checkbox', section: 'Part 7: Requestor Statement' },
  { key: 'pt7_l0_Check_box_3', pdfKey: 'pt7_l0_check_box_3', label: 'Check_Box (Item 4)', type: 'checkbox', section: 'Part 7: Requestor Statement' },
  { key: 'pt7_l0_Check_box_4', pdfKey: 'pt7_l0_check_box_4', label: 'Check_Box (Item 5)', type: 'checkbox', section: 'Part 7: Requestor Statement' },
  { key: 'pt7_l0_Check_box_5', pdfKey: 'pt7_l0_check_box_5', label: 'Check_Box (Item 6)', type: 'checkbox', section: 'Part 7: Requestor Statement' },
  { key: 'pt7_l2a_TypeOfAsset', pdfKey: 'pt7_l2a_typeofasset', label: 'Type of Asset', type: 'text', section: 'Part 7: Requestor Statement' },
  { key: 'pt7_l2b_TypeOfAsset', pdfKey: 'pt7_l2b_typeofasset', label: 'Type of Asset', type: 'text', section: 'Part 7: Requestor Statement' },
  { key: 'pt7_l2c_TypeOfAsset', pdfKey: 'pt7_l2c_typeofasset', label: 'Type of Asset', type: 'text', section: 'Part 7: Requestor Statement' },
  { key: 'pt7_lL1_chbx', pdfKey: 'pt7_ll1_chbx', label: 'Part 7, Item L1', type: 'checkbox', section: 'Part 7: Requestor Statement' },
  { key: 'pt7_lL1_chbx_1', pdfKey: 'pt7_ll1_chbx_1', label: 'Part 7, Item L1', type: 'checkbox', section: 'Part 7: Requestor Statement' },
  { key: 'pt7_lL1B_Name', pdfKey: 'pt7_ll1b_name', label: 'Name', type: 'text', section: 'Part 7: Requestor Statement' },
  { key: 'pt7_lL2_chbx', pdfKey: 'pt7_ll2_chbx', label: 'Part 7, Item L2', type: 'checkbox', section: 'Part 7: Requestor Statement' },
  { key: 'pt7_lL2_Name', pdfKey: 'pt7_ll2_name', label: 'Name', type: 'text', section: 'Part 7: Requestor Statement' },
  { key: 'pt7_lL3_DaytimeTelePhoneNumber1', pdfKey: 'pt7_ll3_daytimetelephonenumber1', label: 'Daytime Tele Phone Number1', type: 'text', section: 'Part 7: Requestor Statement' },
  { key: 'pt7_lL4_MobileTelePhoneNumber1', pdfKey: 'pt7_ll4_mobiletelephonenumber1', label: 'Mobile Tele Phone Number1', type: 'text', section: 'Part 7: Requestor Statement' },
  { key: 'pt7_lL5_EmailAddress', pdfKey: 'pt7_ll5_emailaddress', label: 'Email Address', type: 'text', section: 'Part 7: Requestor Statement' },
  { key: 'pt7_lL6_Date', pdfKey: 'pt7_ll6_date', label: 'Date', type: 'date', section: 'Part 7: Requestor Statement' },
  // === Part 9: Interpreter ===
  { key: 'pt9_l0_Language', pdfKey: 'pt9_l0_language', label: 'Language', type: 'text', section: 'Part 9: Interpreter' },
  { key: 'pt9_lL1A_FamilyName', pdfKey: 'pt9_ll1a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 9: Interpreter' },
  { key: 'pt9_lL1B_GivenName', pdfKey: 'pt9_ll1b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 9: Interpreter' },
  { key: 'pt9_lL2_BusOrgName', pdfKey: 'pt9_ll2_busorgname', label: 'Bus org Name', type: 'text', section: 'Part 9: Interpreter' },
  { key: 'pt9_lL3A_StreetNumberName', pdfKey: 'pt9_ll3a_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 9: Interpreter' },
  { key: 'pt9_lL3B_AptSteFlrNumber', pdfKey: 'pt9_ll3b_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 9: Interpreter' },
  { key: 'pt9_lL3c_City', pdfKey: 'pt9_ll3c_city', label: 'City', type: 'text', section: 'Part 9: Interpreter' },
  { key: 'pt9_lL3d_State', pdfKey: 'pt9_ll3d_state', label: 'State', type: 'text', section: 'Part 9: Interpreter' },
  { key: 'pt9_lL3e_ZipCode', pdfKey: 'pt9_ll3e_zipcode', label: 'Zip Code', type: 'text', section: 'Part 9: Interpreter' },
  { key: 'pt9_lL3f_PostalCode', pdfKey: 'pt9_ll3f_postalcode', label: 'Postal Code', type: 'text', section: 'Part 9: Interpreter' },
  { key: 'pt9_lL3g_Province', pdfKey: 'pt9_ll3g_province', label: 'Province', type: 'text', section: 'Part 9: Interpreter' },
  { key: 'pt9_lL3h_Country', pdfKey: 'pt9_ll3h_country', label: 'Country', type: 'text', section: 'Part 9: Interpreter' },
  { key: 'pt9_lL4_DaytimeTelePhoneNumber1', pdfKey: 'pt9_ll4_daytimetelephonenumber1', label: 'Daytime Tele Phone Number1', type: 'text', section: 'Part 9: Interpreter' },
  { key: 'pt9_lL4_DaytimeTelePhoneNumber1_1', pdfKey: 'pt9_ll4_daytimetelephonenumber1_1', label: 'Daytime Tele Phone Number1 (Item 2)', type: 'text', section: 'Part 9: Interpreter' },
  { key: 'pt9_lL5_EmailAddress', pdfKey: 'pt9_ll5_emailaddress', label: 'Email Address', type: 'text', section: 'Part 9: Interpreter' },
  { key: 'pt9_lL6b_Date', pdfKey: 'pt9_ll6b_date', label: 'Date', type: 'date', section: 'Part 9: Interpreter' },
  { key: 'pt9_lLB_Unit', pdfKey: 'pt9_llb_unit', label: 'Unit', type: 'checkbox', section: 'Part 9: Interpreter' },
  { key: 'pt9_lLB_Unit_1', pdfKey: 'pt9_llb_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 9: Interpreter' },
  { key: 'pt9_lLB_Unit_2', pdfKey: 'pt9_llb_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 9: Interpreter' },
  // === Part 10: Preparer ===
  { key: 'pt10_lL6a_InterpretersSignature', pdfKey: 'pt10_ll6a_interpreterssignature', label: 'Interpreters Signature', type: 'text', section: 'Part 10: Preparer' },
  { key: 'pt10_lL1A_FamilyName', pdfKey: 'pt10_ll1a_familyname', label: 'Family Name (Last Name)', type: 'text', section: 'Part 10: Preparer' },
  { key: 'pt10_lL1b_GivenName', pdfKey: 'pt10_ll1b_givenname', label: 'Given Name (First Name)', type: 'text', section: 'Part 10: Preparer' },
  { key: 'pt10_lL2_BusOrgName', pdfKey: 'pt10_ll2_busorgname', label: 'Bus org Name', type: 'text', section: 'Part 10: Preparer' },
  { key: 'pt10_lL3a_StreetNumberName', pdfKey: 'pt10_ll3a_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 10: Preparer' },
  { key: 'pt10_lL3b_AptSteFlrNumber', pdfKey: 'pt10_ll3b_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 10: Preparer' },
  { key: 'pt10_lL3b_Unit', pdfKey: 'pt10_ll3b_unit', label: 'Unit', type: 'checkbox', section: 'Part 10: Preparer' },
  { key: 'pt10_lL3b_Unit_1', pdfKey: 'pt10_ll3b_unit_1', label: 'Unit (Item 2)', type: 'checkbox', section: 'Part 10: Preparer' },
  { key: 'pt10_lL3b_Unit_2', pdfKey: 'pt10_ll3b_unit_2', label: 'Unit (Item 3)', type: 'checkbox', section: 'Part 10: Preparer' },
  { key: 'pt10_lL3c_City', pdfKey: 'pt10_ll3c_city', label: 'City', type: 'text', section: 'Part 10: Preparer' },
  { key: 'pt10_lL3d_State', pdfKey: 'pt10_ll3d_state', label: 'State', type: 'text', section: 'Part 10: Preparer' },
  { key: 'pt10_lL3e_ZipCode', pdfKey: 'pt10_ll3e_zipcode', label: 'Zip Code', type: 'text', section: 'Part 10: Preparer' },
  { key: 'pt10_lL3f_PostalCode', pdfKey: 'pt10_ll3f_postalcode', label: 'Postal Code', type: 'text', section: 'Part 10: Preparer' },
  { key: 'pt10_lL3g_Province', pdfKey: 'pt10_ll3g_province', label: 'Province', type: 'text', section: 'Part 10: Preparer' },
  { key: 'pt10_lL3h_Country', pdfKey: 'pt10_ll3h_country', label: 'Country', type: 'text', section: 'Part 10: Preparer' },
  { key: 'pt10_lL4_DaytimeTelePhoneNumber1', pdfKey: 'pt10_ll4_daytimetelephonenumber1', label: 'Daytime Tele Phone Number1', type: 'text', section: 'Part 10: Preparer' },
  { key: 'pt10_lL5_FaxNumber1', pdfKey: 'pt10_ll5_faxnumber1', label: 'Fax Number1', type: 'text', section: 'Part 10: Preparer' },
  { key: 'pt10_lL6_EmailAddress', pdfKey: 'pt10_ll6_emailaddress', label: 'Email Address', type: 'text', section: 'Part 10: Preparer' },
  { key: 'pt10_lL7_chbx', pdfKey: 'pt10_ll7_chbx', label: 'Part 10, Item L7', type: 'checkbox', section: 'Part 10: Preparer' },
  { key: 'pt10_lL7_chbx_1', pdfKey: 'pt10_ll7_chbx_1', label: 'Part 10, Item L7', type: 'checkbox', section: 'Part 10: Preparer' },
  { key: 'pt10_lL7B_chbx', pdfKey: 'pt10_ll7b_chbx', label: 'Part 10, Item L7B', type: 'checkbox', section: 'Part 10: Preparer' },
  { key: 'pt10_lL7B_chbx_1', pdfKey: 'pt10_ll7b_chbx_1', label: 'Part 10, Item L7B', type: 'checkbox', section: 'Part 10: Preparer' },
  { key: 'pt10_lL8B_Date', pdfKey: 'pt10_ll8b_date', label: 'Date', type: 'date', section: 'Part 10: Preparer' },
  // === Part 11: Additional Info ===
  { key: 'pt11_lL2_InterpretersSignature', pdfKey: 'pt11_ll2_interpreterssignature', label: 'Interpreters Signature', type: 'text', section: 'Part 11: Additional Info' },
  { key: 'pt11_l3a_PageNumber', pdfKey: 'pt11_l3a_pagenumber', label: 'Page Number', type: 'text', section: 'Part 11: Additional Info' },
  { key: 'pt11_l3b_PartNumber', pdfKey: 'pt11_l3b_partnumber', label: 'Part Number', type: 'text', section: 'Part 11: Additional Info' },
  { key: 'pt11_l3c_ItemNumber', pdfKey: 'pt11_l3c_itemnumber', label: 'Item Number', type: 'text', section: 'Part 11: Additional Info' },
  { key: 'pt11_l3d_AdditionalInfo', pdfKey: 'pt11_l3d_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 11: Additional Info' },
  { key: 'pt11_l4a_PageNumber', pdfKey: 'pt11_l4a_pagenumber', label: 'Page Number', type: 'text', section: 'Part 11: Additional Info' },
  { key: 'pt11_l4b_PartNumber', pdfKey: 'pt11_l4b_partnumber', label: 'Part Number', type: 'text', section: 'Part 11: Additional Info' },
  { key: 'pt11_l4c_ItemNumber', pdfKey: 'pt11_l4c_itemnumber', label: 'Item Number', type: 'text', section: 'Part 11: Additional Info' },
  { key: 'pt11_l5a_PageNumber', pdfKey: 'pt11_l5a_pagenumber', label: 'Page Number', type: 'text', section: 'Part 11: Additional Info' },
  { key: 'pt11_l5b_PartNumber', pdfKey: 'pt11_l5b_partnumber', label: 'Part Number', type: 'text', section: 'Part 11: Additional Info' },
  { key: 'pt11_l5c_ItemNumber', pdfKey: 'pt11_l5c_itemnumber', label: 'Item Number', type: 'text', section: 'Part 11: Additional Info' },
  { key: 'pt11_l5d_AdditionalInfo', pdfKey: 'pt11_l5d_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 11: Additional Info' },
  { key: 'pt11_l6a_PageNumber', pdfKey: 'pt11_l6a_pagenumber', label: 'Page Number', type: 'text', section: 'Part 11: Additional Info' },
  { key: 'pt11_l6b_PartNumber', pdfKey: 'pt11_l6b_partnumber', label: 'Part Number', type: 'text', section: 'Part 11: Additional Info' },
  { key: 'pt11_l6c_ItemNumber', pdfKey: 'pt11_l6c_itemnumber', label: 'Item Number', type: 'text', section: 'Part 11: Additional Info' },
  // === Part 12 ===
  { key: 'pt12_l4d_AdditionalInfo', pdfKey: 'pt12_l4d_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 12' },
  { key: 'pt12_l6d_AdditionalInfo', pdfKey: 'pt12_l6d_additionalinfo', label: 'Additional Info', type: 'text', section: 'Part 12' },
];

export const getInitialFormData = () => {
  const data: Record<string, string> = {};
  formFields.forEach((f) => { if (f.key) data[f.key] = ''; });
  return data;
};

export const i912Config = { formId, formTitle, formSubtitle, formFields, getInitialFormData };
export default i912Config;