// Generated 213 fields for Form I-912
import type { Field } from './types';

export const formId = 'i912';
export const formTitle = 'Form I-912';
export const formSubtitle = 'Request for Fee Waiver';

export const formFields: Field[] = [
  // === Part 1 ===
  { key: 'pt1_l1_checkbox', pdfKey: 'pt1_l1_checkbox', label: 'Part 1, Item 1', type: 'checkbox', section: 'Part 1' },
  { key: 'pt1_l1_checkbox_1', pdfKey: 'pt1_l1_checkbox_1', label: 'Part 1, Item 1', type: 'checkbox', section: 'Part 1' },
  { key: 'pt1_l2_checkbox', pdfKey: 'pt1_l2_checkbox', label: 'Part 1, Item 2', type: 'checkbox', section: 'Part 1' },
  { key: 'pt1_l3_checkbox', pdfKey: 'pt1_l3_checkbox', label: 'Part 1, Item 3', type: 'checkbox', section: 'Part 1' },
  // === Part 10 ===
  { key: 'pt10_lL6a_interpreterssignature', pdfKey: 'pt10_lL6a_interpreterssignature', label: 'Interpreterssignature', type: 'text', section: 'Part 10' },
  { key: 'pt10_lL1A_familyname', pdfKey: 'pt10_lL1A_familyname', label: 'Family Name', type: 'text', section: 'Part 10' },
  { key: 'pt10_lL1b_givenname', pdfKey: 'pt10_lL1b_givenname', label: 'Given Name', type: 'text', section: 'Part 10' },
  { key: 'pt10_lL2_busorgname', pdfKey: 'pt10_lL2_busorgname', label: 'Busorgname', type: 'text', section: 'Part 10' },
  { key: 'pt10_lL3a_streetnumbername', pdfKey: 'pt10_lL3a_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 10' },
  { key: 'pt10_lL3b_aptsteflrnumber', pdfKey: 'pt10_lL3b_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 10' },
  { key: 'pt10_lL3b_unit', pdfKey: 'pt10_lL3b_unit', label: 'Unit', type: 'checkbox', section: 'Part 10' },
  { key: 'pt10_lL3b_unit_1', pdfKey: 'pt10_lL3b_unit_1', label: 'Unit (1)', type: 'checkbox', section: 'Part 10' },
  { key: 'pt10_lL3b_unit_2', pdfKey: 'pt10_lL3b_unit_2', label: 'Unit (2)', type: 'checkbox', section: 'Part 10' },
  { key: 'pt10_lL3c_city', pdfKey: 'pt10_lL3c_city', label: 'City', type: 'text', section: 'Part 10' },
  { key: 'pt10_lL3d_state', pdfKey: 'pt10_lL3d_state', label: 'State', type: 'text', section: 'Part 10' },
  { key: 'pt10_lL3e_zipcode', pdfKey: 'pt10_lL3e_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 10' },
  { key: 'pt10_lL3f_postalcode', pdfKey: 'pt10_lL3f_postalcode', label: 'Postalcode', type: 'text', section: 'Part 10' },
  { key: 'pt10_lL3g_province', pdfKey: 'pt10_lL3g_province', label: 'Province', type: 'text', section: 'Part 10' },
  { key: 'pt10_lL3h_country', pdfKey: 'pt10_lL3h_country', label: 'Country', type: 'text', section: 'Part 10' },
  { key: 'pt10_lL4_daytimetelephonenumber1', pdfKey: 'pt10_lL4_daytimetelephonenumber1', label: 'Daytimetelephonenumber1', type: 'text', section: 'Part 10' },
  { key: 'pt10_lL5_faxnumber1', pdfKey: 'pt10_lL5_faxnumber1', label: 'Faxnumber1', type: 'text', section: 'Part 10' },
  { key: 'pt10_lL6_emailaddress', pdfKey: 'pt10_lL6_emailaddress', label: 'Emailaddress', type: 'text', section: 'Part 10' },
  { key: 'pt10_lL7B_chbx', pdfKey: 'pt10_lL7B_chbx', label: 'Part 10, Item L7B', type: 'checkbox', section: 'Part 10' },
  { key: 'pt10_lL7B_chbx_1', pdfKey: 'pt10_lL7B_chbx_1', label: 'Part 10, Item L7B', type: 'checkbox', section: 'Part 10' },
  { key: 'pt10_lL7_chbx', pdfKey: 'pt10_lL7_chbx', label: 'Part 10, Item L7', type: 'checkbox', section: 'Part 10' },
  { key: 'pt10_lL7_chbx_1', pdfKey: 'pt10_lL7_chbx_1', label: 'Part 10, Item L7', type: 'checkbox', section: 'Part 10' },
  { key: 'pt10_lL8B_date', pdfKey: 'pt10_lL8B_date', label: 'Date', type: 'date', section: 'Part 10' },
  // === Part 11 ===
  { key: 'pt11_lL2_interpreterssignature', pdfKey: 'pt11_lL2_interpreterssignature', label: 'Interpreterssignature', type: 'text', section: 'Part 11' },
  { key: 'pt11_l3a_pagenumber', pdfKey: 'pt11_l3a_pagenumber', label: 'Pagenumber', type: 'text', section: 'Part 11' },
  { key: 'pt11_l3b_partnumber', pdfKey: 'pt11_l3b_partnumber', label: 'Partnumber', type: 'text', section: 'Part 11' },
  { key: 'pt11_l3c_itemnumber', pdfKey: 'pt11_l3c_itemnumber', label: 'Itemnumber', type: 'text', section: 'Part 11' },
  { key: 'pt11_l3d_additionalinfo', pdfKey: 'pt11_l3d_additionalinfo', label: 'Additionalinfo', type: 'text', section: 'Part 11' },
  { key: 'pt11_l4a_pagenumber', pdfKey: 'pt11_l4a_pagenumber', label: 'Pagenumber', type: 'text', section: 'Part 11' },
  { key: 'pt11_l4b_partnumber', pdfKey: 'pt11_l4b_partnumber', label: 'Partnumber', type: 'text', section: 'Part 11' },
  { key: 'pt11_l4c_itemnumber', pdfKey: 'pt11_l4c_itemnumber', label: 'Itemnumber', type: 'text', section: 'Part 11' },
  { key: 'pt11_l5a_pagenumber', pdfKey: 'pt11_l5a_pagenumber', label: 'Pagenumber', type: 'text', section: 'Part 11' },
  { key: 'pt11_l5b_partnumber', pdfKey: 'pt11_l5b_partnumber', label: 'Partnumber', type: 'text', section: 'Part 11' },
  { key: 'pt11_l5c_itemnumber', pdfKey: 'pt11_l5c_itemnumber', label: 'Itemnumber', type: 'text', section: 'Part 11' },
  { key: 'pt11_l5d_additionalinfo', pdfKey: 'pt11_l5d_additionalinfo', label: 'Additionalinfo', type: 'text', section: 'Part 11' },
  { key: 'pt11_l6a_pagenumber', pdfKey: 'pt11_l6a_pagenumber', label: 'Pagenumber', type: 'text', section: 'Part 11' },
  { key: 'pt11_l6b_partnumber', pdfKey: 'pt11_l6b_partnumber', label: 'Partnumber', type: 'text', section: 'Part 11' },
  { key: 'pt11_l6c_itemnumber', pdfKey: 'pt11_l6c_itemnumber', label: 'Itemnumber', type: 'text', section: 'Part 11' },
  // === Part 12 ===
  { key: 'pt12_l4d_additionalinfo', pdfKey: 'pt12_l4d_additionalinfo', label: 'Additionalinfo', type: 'text', section: 'Part 12' },
  { key: 'pt12_l6d_additionalinfo', pdfKey: 'pt12_l6d_additionalinfo', label: 'Additionalinfo', type: 'text', section: 'Part 12' },
  // === Part 2 ===
  { key: 'pt2_l3_aliennumber', pdfKey: 'pt2_l3_aliennumber', label: 'A-Number', type: 'text', section: 'Part 2' },
  { key: 'pt2_l3_familyname', pdfKey: 'pt2_l3_familyname', label: 'Family Name', type: 'text', section: 'Part 2' },
  { key: 'pt2_l3_givenname', pdfKey: 'pt2_l3_givenname', label: 'Given Name', type: 'text', section: 'Part 2' },
  { key: 'pt2_l3_middlename', pdfKey: 'pt2_l3_middlename', label: 'Middle Name', type: 'text', section: 'Part 2' },
  { key: 'pt2_l4_acctidentifier', pdfKey: 'pt2_l4_acctidentifier', label: 'Acctidentifier', type: 'text', section: 'Part 2' },
  { key: 'pt2_lL2_familyname', pdfKey: 'pt2_lL2_familyname', label: 'Family Name', type: 'text', section: 'Part 2' },
  { key: 'pt2_lL2_givenname', pdfKey: 'pt2_lL2_givenname', label: 'Given Name', type: 'text', section: 'Part 2' },
  { key: 'pt2_lL2_middlename', pdfKey: 'pt2_lL2_middlename', label: 'Middle Name', type: 'text', section: 'Part 2' },
  { key: 'pt2_lL3_familyname', pdfKey: 'pt2_lL3_familyname', label: 'Family Name', type: 'text', section: 'Part 2' },
  { key: 'pt2_lL3_givenname', pdfKey: 'pt2_lL3_givenname', label: 'Given Name', type: 'text', section: 'Part 2' },
  { key: 'pt2_lL3_middlename', pdfKey: 'pt2_lL3_middlename', label: 'Middle Name', type: 'text', section: 'Part 2' },
  { key: 'pt2_l5_dateofbirth', pdfKey: 'pt2_l5_dateofbirth', label: 'Dateofbirth', type: 'date', section: 'Part 2' },
  { key: 'pt2_l6_ssn', pdfKey: 'pt2_l6_ssn', label: 'Social Security Number', type: 'text', section: 'Part 2' },
  { key: 'pt2_l7_maritalstatus', pdfKey: 'pt2_l7_maritalstatus', label: 'Maritalstatus', type: 'checkbox', section: 'Part 2' },
  { key: 'pt2_l7_maritalstatus_1', pdfKey: 'pt2_l7_maritalstatus_1', label: 'Maritalstatus (1)', type: 'checkbox', section: 'Part 2' },
  { key: 'pt2_l7_maritalstatus_2', pdfKey: 'pt2_l7_maritalstatus_2', label: 'Maritalstatus (2)', type: 'checkbox', section: 'Part 2' },
  { key: 'pt2_l7_maritalstatus_3', pdfKey: 'pt2_l7_maritalstatus_3', label: 'Maritalstatus (3)', type: 'checkbox', section: 'Part 2' },
  { key: 'pt2_l7_maritalstatus_4', pdfKey: 'pt2_l7_maritalstatus_4', label: 'Maritalstatus (4)', type: 'checkbox', section: 'Part 2' },
  { key: 'pt2_l7_maritalstatus_5', pdfKey: 'pt2_l7_maritalstatus_5', label: 'Maritalstatus (5)', type: 'checkbox', section: 'Part 2' },
  { key: 'pt2_l7_maritalstatus_6', pdfKey: 'pt2_l7_maritalstatus_6', label: 'Maritalstatus (6)', type: 'checkbox', section: 'Part 2' },
  { key: 'pt2_l7_othertext', pdfKey: 'pt2_l7_othertext', label: 'Othertext', type: 'text', section: 'Part 2' },
  { key: 'pt2_l3_aliennumber_1', pdfKey: 'pt2_l3_aliennumber_1', label: 'A-Number (1)', type: 'text', section: 'Part 2' },
  { key: 'pt2_lL2_familyname_1', pdfKey: 'pt2_lL2_familyname_1', label: 'Family Name (1)', type: 'text', section: 'Part 2' },
  { key: 'pt2_lL2_givenname_1', pdfKey: 'pt2_lL2_givenname_1', label: 'Given Name (1)', type: 'text', section: 'Part 2' },
  { key: 'pt2_lL2_middlename_1', pdfKey: 'pt2_lL2_middlename_1', label: 'Middle Name (1)', type: 'text', section: 'Part 2' },
  // === Part 3 ===
  { key: 'pt3_l1_aliennumber', pdfKey: 'pt3_l1_aliennumber', label: 'A-Number', type: 'text', section: 'Part 3' },
  { key: 'pt3_l1_aliennumber2', pdfKey: 'pt3_l1_aliennumber2', label: 'A-Number2', type: 'text', section: 'Part 3' },
  { key: 'pt3_l1_aliennumber3', pdfKey: 'pt3_l1_aliennumber3', label: 'A-Number3', type: 'text', section: 'Part 3' },
  { key: 'pt3_l1_aliennumber4', pdfKey: 'pt3_l1_aliennumber4', label: 'A-Number4', type: 'text', section: 'Part 3' },
  { key: 'pt3_l1_dateofbirth1', pdfKey: 'pt3_l1_dateofbirth1', label: 'Dateofbirth1', type: 'date', section: 'Part 3' },
  { key: 'pt3_l1_dateofbirth2', pdfKey: 'pt3_l1_dateofbirth2', label: 'Dateofbirth2', type: 'date', section: 'Part 3' },
  { key: 'pt3_l1_dateofbirth3', pdfKey: 'pt3_l1_dateofbirth3', label: 'Dateofbirth3', type: 'date', section: 'Part 3' },
  { key: 'pt3_l1_dateofbirth4', pdfKey: 'pt3_l1_dateofbirth4', label: 'Dateofbirth4', type: 'date', section: 'Part 3' },
  { key: 'pt3_l1_formsfiled1', pdfKey: 'pt3_l1_formsfiled1', label: 'Formsfiled1', type: 'text', section: 'Part 3' },
  { key: 'pt3_l1_formsfiled2', pdfKey: 'pt3_l1_formsfiled2', label: 'Formsfiled2', type: 'text', section: 'Part 3' },
  { key: 'pt3_l1_formsfiled3', pdfKey: 'pt3_l1_formsfiled3', label: 'Formsfiled3', type: 'text', section: 'Part 3' },
  { key: 'pt3_l1_formsfiled4', pdfKey: 'pt3_l1_formsfiled4', label: 'Formsfiled4', type: 'text', section: 'Part 3' },
  { key: 'pt3_l1_name1', pdfKey: 'pt3_l1_name1', label: 'Name1', type: 'text', section: 'Part 3' },
  { key: 'pt3_l1_name2', pdfKey: 'pt3_l1_name2', label: 'Name2', type: 'text', section: 'Part 3' },
  { key: 'pt3_l1_name3', pdfKey: 'pt3_l1_name3', label: 'Name3', type: 'text', section: 'Part 3' },
  { key: 'pt3_l1_name4', pdfKey: 'pt3_l1_name4', label: 'Name4', type: 'text', section: 'Part 3' },
  { key: 'pt3_l1_totalforms', pdfKey: 'pt3_l1_totalforms', label: 'Totalforms', type: 'text', section: 'Part 3' },
  { key: 'pt3_l3_other', pdfKey: 'pt3_l3_other', label: 'Other', type: 'text', section: 'Part 3' },
  { key: 'pt3_lL2a_applicantssignature', pdfKey: 'pt3_lL2a_applicantssignature', label: 'Applicantssignature', type: 'text', section: 'Part 3' },
  // === Part 4 ===
  { key: 'pt4_l1_agency1', pdfKey: 'pt4_l1_agency1', label: 'Agency1', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_agency1_1', pdfKey: 'pt4_l1_agency1_1', label: 'Agency1 (1)', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_agency2', pdfKey: 'pt4_l1_agency2', label: 'Agency2', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_agency2_1', pdfKey: 'pt4_l1_agency2_1', label: 'Agency2 (1)', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_agency3', pdfKey: 'pt4_l1_agency3', label: 'Agency3', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_agency3_1', pdfKey: 'pt4_l1_agency3_1', label: 'Agency3 (1)', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_agency4', pdfKey: 'pt4_l1_agency4', label: 'Agency4', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_agency4_1', pdfKey: 'pt4_l1_agency4_1', label: 'Agency4 (1)', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_dateaward1', pdfKey: 'pt4_l1_dateaward1', label: 'Dateaward1', type: 'date', section: 'Part 4' },
  { key: 'pt4_l1_dateaward1_1', pdfKey: 'pt4_l1_dateaward1_1', label: 'Dateaward1 (1)', type: 'date', section: 'Part 4' },
  { key: 'pt4_l1_dateaward2', pdfKey: 'pt4_l1_dateaward2', label: 'Dateaward2', type: 'date', section: 'Part 4' },
  { key: 'pt4_l1_dateaward2_1', pdfKey: 'pt4_l1_dateaward2_1', label: 'Dateaward2 (1)', type: 'date', section: 'Part 4' },
  { key: 'pt4_l1_dateaward3', pdfKey: 'pt4_l1_dateaward3', label: 'Dateaward3', type: 'date', section: 'Part 4' },
  { key: 'pt4_l1_dateaward3_1', pdfKey: 'pt4_l1_dateaward3_1', label: 'Dateaward3 (1)', type: 'date', section: 'Part 4' },
  { key: 'pt4_l1_dateaward4', pdfKey: 'pt4_l1_dateaward4', label: 'Dateaward4', type: 'date', section: 'Part 4' },
  { key: 'pt4_l1_dateaward4_1', pdfKey: 'pt4_l1_dateaward4_1', label: 'Dateaward4 (1)', type: 'date', section: 'Part 4' },
  { key: 'pt4_l1_expdate1', pdfKey: 'pt4_l1_expdate1', label: 'Expdate1', type: 'date', section: 'Part 4' },
  { key: 'pt4_l1_expdate1_1', pdfKey: 'pt4_l1_expdate1_1', label: 'Expdate1 (1)', type: 'date', section: 'Part 4' },
  { key: 'pt4_l1_expdate2', pdfKey: 'pt4_l1_expdate2', label: 'Expdate2', type: 'date', section: 'Part 4' },
  { key: 'pt4_l1_expdate2_1', pdfKey: 'pt4_l1_expdate2_1', label: 'Expdate2 (1)', type: 'date', section: 'Part 4' },
  { key: 'pt4_l1_expdate3', pdfKey: 'pt4_l1_expdate3', label: 'Expdate3', type: 'date', section: 'Part 4' },
  { key: 'pt4_l1_expdate3_1', pdfKey: 'pt4_l1_expdate3_1', label: 'Expdate3 (1)', type: 'date', section: 'Part 4' },
  { key: 'pt4_l1_expdate4', pdfKey: 'pt4_l1_expdate4', label: 'Expdate4', type: 'date', section: 'Part 4' },
  { key: 'pt4_l1_expdate4_1', pdfKey: 'pt4_l1_expdate4_1', label: 'Expdate4 (1)', type: 'date', section: 'Part 4' },
  { key: 'pt4_l1_fullname1', pdfKey: 'pt4_l1_fullname1', label: 'Fullname1', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_fullname1_1', pdfKey: 'pt4_l1_fullname1_1', label: 'Fullname1 (1)', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_fullname2', pdfKey: 'pt4_l1_fullname2', label: 'Fullname2', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_fullname2_1', pdfKey: 'pt4_l1_fullname2_1', label: 'Fullname2 (1)', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_fullname3', pdfKey: 'pt4_l1_fullname3', label: 'Fullname3', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_fullname3_1', pdfKey: 'pt4_l1_fullname3_1', label: 'Fullname3 (1)', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_fullname4', pdfKey: 'pt4_l1_fullname4', label: 'Fullname4', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_fullname4_1', pdfKey: 'pt4_l1_fullname4_1', label: 'Fullname4 (1)', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_relationship1', pdfKey: 'pt4_l1_relationship1', label: 'Relationship1', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_relationship1_1', pdfKey: 'pt4_l1_relationship1_1', label: 'Relationship1 (1)', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_relationship2', pdfKey: 'pt4_l1_relationship2', label: 'Relationship2', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_relationship2_1', pdfKey: 'pt4_l1_relationship2_1', label: 'Relationship2 (1)', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_relationship3', pdfKey: 'pt4_l1_relationship3', label: 'Relationship3', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_relationship3_1', pdfKey: 'pt4_l1_relationship3_1', label: 'Relationship3 (1)', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_relationship4', pdfKey: 'pt4_l1_relationship4', label: 'Relationship4', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_relationship4_1', pdfKey: 'pt4_l1_relationship4_1', label: 'Relationship4 (1)', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_typeofbene1', pdfKey: 'pt4_l1_typeofbene1', label: 'Typeofbene1', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_typeofbene1_1', pdfKey: 'pt4_l1_typeofbene1_1', label: 'Typeofbene1 (1)', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_typeofbene2', pdfKey: 'pt4_l1_typeofbene2', label: 'Typeofbene2', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_typeofbene2_1', pdfKey: 'pt4_l1_typeofbene2_1', label: 'Typeofbene2 (1)', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_typeofbene3', pdfKey: 'pt4_l1_typeofbene3', label: 'Typeofbene3', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_typeofbene3_1', pdfKey: 'pt4_l1_typeofbene3_1', label: 'Typeofbene3 (1)', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_typeofbene4', pdfKey: 'pt4_l1_typeofbene4', label: 'Typeofbene4', type: 'text', section: 'Part 4' },
  { key: 'pt4_l1_typeofbene4_1', pdfKey: 'pt4_l1_typeofbene4_1', label: 'Typeofbene4 (1)', type: 'text', section: 'Part 4' },
  { key: 'pt4_l2a_relationshiptoyou1', pdfKey: 'pt4_l2a_relationshiptoyou1', label: 'Relationshiptoyou1', type: 'text', section: 'Part 4' },
  { key: 'pt4_l2b_dateofbirth2', pdfKey: 'pt4_l2b_dateofbirth2', label: 'Dateofbirth2', type: 'date', section: 'Part 4' },
  { key: 'pt4_l2c_dateofbirth3', pdfKey: 'pt4_l2c_dateofbirth3', label: 'Dateofbirth3', type: 'date', section: 'Part 4' },
  { key: 'pt4_l2d_dateofbirth4', pdfKey: 'pt4_l2d_dateofbirth4', label: 'Dateofbirth4', type: 'date', section: 'Part 4' },
  // === Part 5 ===
  { key: 'pt5_l1_employmentstatus', pdfKey: 'pt5_l1_employmentstatus', label: 'Employmentstatus', type: 'checkbox', section: 'Part 5' },
  { key: 'pt5_l1_employmentstatus_1', pdfKey: 'pt5_l1_employmentstatus_1', label: 'Employmentstatus (1)', type: 'checkbox', section: 'Part 5' },
  { key: 'pt5_l1_employmentstatus_2', pdfKey: 'pt5_l1_employmentstatus_2', label: 'Employmentstatus (2)', type: 'checkbox', section: 'Part 5' },
  { key: 'pt5_l1_employmentstatus_3', pdfKey: 'pt5_l1_employmentstatus_3', label: 'Employmentstatus (3)', type: 'checkbox', section: 'Part 5' },
  { key: 'pt5_l2_chbxyesno', pdfKey: 'pt5_l2_chbxyesno', label: 'yesno', type: 'checkbox', section: 'Part 5' },
  { key: 'pt5_l2_chbxyesno_1', pdfKey: 'pt5_l2_chbxyesno_1', label: 'yesno (1)', type: 'checkbox', section: 'Part 5' },
  { key: 'pt5_l2a_dateofunemployment', pdfKey: 'pt5_l2a_dateofunemployment', label: 'Dateofunemployment', type: 'date', section: 'Part 5' },
  { key: 'pt5_l3_totalhousesize', pdfKey: 'pt5_l3_totalhousesize', label: 'Totalhousesize', type: 'text', section: 'Part 5' },
  { key: 'pt5_l4_totalhousehold', pdfKey: 'pt5_l4_totalhousehold', label: 'Totalhousehold', type: 'text', section: 'Part 5' },
  { key: 'pt5_l5_namehousehold', pdfKey: 'pt5_l5_namehousehold', label: 'Namehousehold', type: 'text', section: 'Part 5' },
  { key: 'pt5_l9_checkbox', pdfKey: 'pt5_l9_checkbox', label: 'Part 5, Item 9', type: 'checkbox', section: 'Part 5' },
  { key: 'pt5_l9_checkbox_1', pdfKey: 'pt5_l9_checkbox_1', label: 'Part 5, Item 9', type: 'checkbox', section: 'Part 5' },
  { key: 'pt5_l9_explanation', pdfKey: 'pt5_l9_explanation', label: 'Explanation', type: 'text', section: 'Part 5' },
  // === Part 6 ===
  { key: 'pt6_l1_situation', pdfKey: 'pt6_l1_situation', label: 'Situation', type: 'text', section: 'Part 6' },
  { key: 'pt6_l3_checkbox', pdfKey: 'pt6_l3_checkbox', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6' },
  { key: 'pt6_l3_checkbox_1', pdfKey: 'pt6_l3_checkbox_1', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6' },
  { key: 'pt6_l3_checkbox_10', pdfKey: 'pt6_l3_checkbox_10', label: '_10', type: 'checkbox', section: 'Part 6' },
  { key: 'pt6_l3_checkbox_2', pdfKey: 'pt6_l3_checkbox_2', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6' },
  { key: 'pt6_l3_checkbox_3', pdfKey: 'pt6_l3_checkbox_3', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6' },
  { key: 'pt6_l3_checkbox_4', pdfKey: 'pt6_l3_checkbox_4', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6' },
  { key: 'pt6_l3_checkbox_5', pdfKey: 'pt6_l3_checkbox_5', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6' },
  { key: 'pt6_l3_checkbox_6', pdfKey: 'pt6_l3_checkbox_6', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6' },
  { key: 'pt6_l3_checkbox_7', pdfKey: 'pt6_l3_checkbox_7', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6' },
  { key: 'pt6_l3_checkbox_8', pdfKey: 'pt6_l3_checkbox_8', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6' },
  { key: 'pt6_l3_checkbox_9', pdfKey: 'pt6_l3_checkbox_9', label: 'Part 6, Item 3', type: 'checkbox', section: 'Part 6' },
  { key: 'pt6_l3_other', pdfKey: 'pt6_l3_other', label: 'Other', type: 'text', section: 'Part 6' },
  { key: 'pt6_l3_total', pdfKey: 'pt6_l3_total', label: 'Total', type: 'text', section: 'Part 6' },
  // === Part 7 ===
  { key: 'pt7_l2a_typeofasset', pdfKey: 'pt7_l2a_typeofasset', label: 'Typeofasset', type: 'text', section: 'Part 7' },
  { key: 'pt7_l2b_typeofasset', pdfKey: 'pt7_l2b_typeofasset', label: 'Typeofasset', type: 'text', section: 'Part 7' },
  { key: 'pt7_l2c_typeofasset', pdfKey: 'pt7_l2c_typeofasset', label: 'Typeofasset', type: 'text', section: 'Part 7' },
  { key: 'pt7_lL1B_name', pdfKey: 'pt7_lL1B_name', label: 'Name', type: 'text', section: 'Part 7' },
  { key: 'pt7_lL1_chbx', pdfKey: 'pt7_lL1_chbx', label: 'Part 7, Item L1', type: 'checkbox', section: 'Part 7' },
  { key: 'pt7_lL1_chbx_1', pdfKey: 'pt7_lL1_chbx_1', label: 'Part 7, Item L1', type: 'checkbox', section: 'Part 7' },
  { key: 'pt7_lL2_chbx', pdfKey: 'pt7_lL2_chbx', label: 'Part 7, Item L2', type: 'checkbox', section: 'Part 7' },
  { key: 'pt7_lL2_name', pdfKey: 'pt7_lL2_name', label: 'Name', type: 'text', section: 'Part 7' },
  { key: 'pt7_lL3_daytimetelephonenumber1', pdfKey: 'pt7_lL3_daytimetelephonenumber1', label: 'Daytimetelephonenumber1', type: 'text', section: 'Part 7' },
  { key: 'pt7_lL4_mobiletelephonenumber1', pdfKey: 'pt7_lL4_mobiletelephonenumber1', label: 'Mobiletelephonenumber1', type: 'text', section: 'Part 7' },
  { key: 'pt7_lL5_emailaddress', pdfKey: 'pt7_lL5_emailaddress', label: 'Emailaddress', type: 'text', section: 'Part 7' },
  { key: 'pt7_lL6_date', pdfKey: 'pt7_lL6_date', label: 'Date', type: 'date', section: 'Part 7' },
  // === Part 8 ===
  { key: 'pt8_l7a_check_box', pdfKey: 'pt8_l7a_check_box', label: 'Check_Box', type: 'checkbox', section: 'Part 8' },
  { key: 'pt8_l7a_check_box_1', pdfKey: 'pt8_l7a_check_box_1', label: 'Check_Box (1)', type: 'checkbox', section: 'Part 8' },
  { key: 'pt8_l7a_check_box_2', pdfKey: 'pt8_l7a_check_box_2', label: 'Check_Box (2)', type: 'checkbox', section: 'Part 8' },
  { key: 'pt8_l7a_check_box_3', pdfKey: 'pt8_l7a_check_box_3', label: 'Check_Box (3)', type: 'checkbox', section: 'Part 8' },
  { key: 'pt8_l7a_check_box_4', pdfKey: 'pt8_l7a_check_box_4', label: 'Check_Box (4)', type: 'checkbox', section: 'Part 8' },
  { key: 'pt8_l7a_check_box_5', pdfKey: 'pt8_l7a_check_box_5', label: 'Check_Box (5)', type: 'checkbox', section: 'Part 8' },
  // === Part 9 ===
  { key: 'pt9_lL1A_familyname', pdfKey: 'pt9_lL1A_familyname', label: 'Family Name', type: 'text', section: 'Part 9' },
  { key: 'pt9_lL1B_givenname', pdfKey: 'pt9_lL1B_givenname', label: 'Given Name', type: 'text', section: 'Part 9' },
  { key: 'pt9_lL2_busorgname', pdfKey: 'pt9_lL2_busorgname', label: 'Busorgname', type: 'text', section: 'Part 9' },
  { key: 'pt9_lL3A_streetnumbername', pdfKey: 'pt9_lL3A_streetnumbername', label: 'Street Number and Name', type: 'text', section: 'Part 9' },
  { key: 'pt9_lL3B_aptsteflrnumber', pdfKey: 'pt9_lL3B_aptsteflrnumber', label: 'Apt./Ste./Flr. Number', type: 'text', section: 'Part 9' },
  { key: 'pt9_lL3c_city', pdfKey: 'pt9_lL3c_city', label: 'City', type: 'text', section: 'Part 9' },
  { key: 'pt9_lL3d_state', pdfKey: 'pt9_lL3d_state', label: 'State', type: 'text', section: 'Part 9' },
  { key: 'pt9_lL3e_zipcode', pdfKey: 'pt9_lL3e_zipcode', label: 'ZIP Code', type: 'text', section: 'Part 9' },
  { key: 'pt9_lL3f_postalcode', pdfKey: 'pt9_lL3f_postalcode', label: 'Postalcode', type: 'text', section: 'Part 9' },
  { key: 'pt9_lL3g_province', pdfKey: 'pt9_lL3g_province', label: 'Province', type: 'text', section: 'Part 9' },
  { key: 'pt9_lL3h_country', pdfKey: 'pt9_lL3h_country', label: 'Country', type: 'text', section: 'Part 9' },
  { key: 'pt9_lL4_daytimetelephonenumber1', pdfKey: 'pt9_lL4_daytimetelephonenumber1', label: 'Daytimetelephonenumber1', type: 'text', section: 'Part 9' },
  { key: 'pt9_lL4_daytimetelephonenumber1_1', pdfKey: 'pt9_lL4_daytimetelephonenumber1_1', label: 'Daytimetelephonenumber1 (1)', type: 'text', section: 'Part 9' },
  { key: 'pt9_lL5_emailaddress', pdfKey: 'pt9_lL5_emailaddress', label: 'Emailaddress', type: 'text', section: 'Part 9' },
  { key: 'pt9_lL6b_date', pdfKey: 'pt9_lL6b_date', label: 'Date', type: 'date', section: 'Part 9' },
  { key: 'pt9_lLB_unit', pdfKey: 'pt9_lLB_unit', label: 'Unit', type: 'checkbox', section: 'Part 9' },
  { key: 'pt9_lLB_unit_1', pdfKey: 'pt9_lLB_unit_1', label: 'Unit (1)', type: 'checkbox', section: 'Part 9' },
  { key: 'pt9_lLB_unit_2', pdfKey: 'pt9_lLB_unit_2', label: 'Unit (2)', type: 'checkbox', section: 'Part 9' },
  // === Part 0 ===
  { key: 's_p1_immstatus', pdfKey: 's_p1_immstatus', label: 'S_P1_Immstatus', type: 'text', section: 'Part 0' },
  { key: 's_avghousehold', pdfKey: 's_avghousehold', label: 'S_Avghousehold', type: 'text', section: 'Part 0' },
  { key: 's_monthlyincome', pdfKey: 's_monthlyincome', label: 'S_Monthlyincome', type: 'text', section: 'Part 0' },
  { key: 's_total', pdfKey: 's_total', label: 'S_Total', type: 'text', section: 'Part 0' },
  { key: 's_assets1', pdfKey: 's_assets1', label: 'S_Assets1', type: 'text', section: 'Part 0' },
  { key: 's_assets2', pdfKey: 's_assets2', label: 'S_Assets2', type: 'text', section: 'Part 0' },
  { key: 's_assets3', pdfKey: 's_assets3', label: 'S_Assets3', type: 'text', section: 'Part 0' },
  { key: 's_button1', pdfKey: 's_button1', label: 'S_Button1', type: 'text', section: 'Part 0' },
  { key: 's_totalassets', pdfKey: 's_totalassets', label: 'S_Totalassets', type: 'text', section: 'Part 0' },
  { key: 's_p9_language', pdfKey: 's_p9_language', label: 'S_P9_Language', type: 'text', section: 'Part 0' },
];

export const getInitialFormData = () => {
  const data: Record<string, string> = {};
  formFields.forEach((f) => { if (f.key != null) data[f.key] = ''; });
  return data;
};

export const i912Config = { formId, formTitle, formSubtitle, formFields, getInitialFormData };
export default i912Config;